SkriptLang/Skript

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java

Added an option to parse a player/offline player from a string UUID
I added an `(?i)` in the regex cause I'm not sure if the uuid are lower case.

Parse Player/Offline Player with UUID

---

build.gradle
src/main/java/ch/njol/skript/hooks/regions/PreciousStonesHook.java
src/main/resources/plugin.yml

Add PreciousStones support to region expression

PreciousStones integration

---

docs/css/styles.css
docs/template.html

It doesn't change technically anything for pc users and is better for those users who use the docs in mobile (as me). You can look some screenshots of how it looked before and after these little changes:
Before:
After:

A little fix for the docs on mobile

---

src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java
src/main/java/ch/njol/skript/expressions/ExprVelocity.java

This has been sitting secretly in skDragon for a long time for a few people that needed it.
It should have an 'enter' and 'exit' instead of just a general one, go ahead and add that.

Silverfish should be added to BlockChangeEvent

---

src/main/resources/aliases-english.sk

Affects lines 593-613 as color beds were not added yet to aliases

Added Color type beds

---

src/main/java/ch/njol/skript/expressions/ExprVelocity.java

(ExprVelocity)Fixed registration issue

---

src/main/java/ch/njol/skript/expressions/ExprChatFormat.java

Related issues: Adds enhancement #548 
Description:
Adds a settable expression for the chat format of an AsyncPlayerChatEvent.

Add chat format expression

---

src/main/resources/aliases-english.sk
src/main/resources/scripts/drop fixes.sk
src/main/resources/scripts/equip anything.sk
src/main/resources/scripts/item command.sk

Target Minecraft versions: 1.12.1
Requirements: No requirement
Related issues: No related issue
Description:
I just updated the aliases (english) to the latest (2.0.8) and fixed the scripts problem who caused errors on load (equip anything.sk, item command.sk, drop fixes.sk) to work with the new aliases

Updated aliases and fixed scripts

---

src/main/java/ch/njol/skript/expressions/ExprVelocity.java

A simple fix for the velocity expression not letting you use its changers with vectors.

Fix the velocity expression, again.

---

src/main/resources/scripts/equip anything.sk

I utilized the aliases option in this case rather than options. Also for some reason the original example of this didn't work for me.

Update equip anything.sk

---

src/main/java/ch/njol/skript/conditions/CondIsBlocking.java
src/main/java/ch/njol/skript/conditions/CondIsEmpty.java
src/main/java/ch/njol/skript/effects/EffColorArmor.java
src/main/java/ch/njol/skript/effects/EffExit.java
src/main/java/ch/njol/skript/effects/EffPotion.java
src/main/java/ch/njol/skript/effects/mirre/EffScriptOptionLoops.java
src/main/java/ch/njol/skript/events/EvtBookEdit.java
src/main/java/ch/njol/skript/events/EvtBookSign.java
src/main/java/ch/njol/skript/events/EvtChat.java
src/main/java/ch/njol/skript/events/EvtItem.java
src/main/java/ch/njol/skript/events/EvtPeriodical.java
src/main/java/ch/njol/skript/events/SimpleEvents.java
src/main/java/ch/njol/skript/expressions/ExprChatFormat.java
src/main/java/ch/njol/skript/expressions/ExprHash.java
src/main/java/ch/njol/skript/expressions/ExprItem.java
src/main/java/ch/njol/skript/expressions/ExprItems.java
src/main/java/ch/njol/skript/expressions/ExprLevel.java
src/main/java/ch/njol/skript/expressions/ExprRemainingAir.java
src/main/java/ch/njol/skript/expressions/ExprSpeed.java
src/main/java/ch/njol/skript/expressions/ExprTarget.java

Fixed many Since's, descriptions and examples in docs.
Used `<i>unknown</i> (before 2.1)` instead of empty or *`unknown`* Sinces.

About Docs

---

src/main/java/ch/njol/skript/log/SkriptLogger.java

Related issues: #914 
Description:
Updates the issue URL to link to this repo

Update Issue URL

---

src/main/resources/lang/english.lang

Target Minecraft versions: *any*
Requirements: *none*
Related issues: #920 
Description: *Added 'ttp' for tooltip and added 'sgt' for suggest command*

Added json.sk aliases for chat styles.

---

src/main/java/ch/njol/skript/util/AsyncEffect.java

Description:
AsyncEffect stopped working if there was no condition/effect after it, in commit cded560b362e7ff2325bf8b95d74ab24e607ec9a. This fixes that.

Fix AsyncEffect

---

src/main/java/ch/njol/skript/effects/EffPlaySound.java

Related issues: #861
Description:
Add support for spigot sounds in the play sound effect

Add support for spigot sounds in the play sound effect

---

src/main/java/ch/njol/skript/doc/DocumentationID.java
src/main/java/ch/njol/skript/doc/RequiredPlugins.java
src/main/java/ch/njol/skript/events/EvtPeriodical.java
src/main/java/ch/njol/skript/lang/SkriptEventInfo.java

Description:
Added in @DocumentationID and  @RequiredPlugins annotations to help addon authors better document their code base using Skript built in annotations.

Additional documentation annotations

---

src/main/java/ch/njol/skript/expressions/ExprHighestSolidBlock.java
src/main/java/ch/njol/skript/expressions/ExprPlayerWeather.java
src/main/java/ch/njol/skript/expressions/ExprWeather.java
src/main/java/ch/njol/skript/util/WeatherType.java

Requirements: I don't think any
Related issues: #897 and #911 
Description:
Just like the title says, I added two expressions suggested in the two issues mentioned above.
I'm of course open to any suggestions or problems, if any :)

Added ExprHighestSolidBlock and ExprPlayerWeather

---

src/main/java/ch/njol/skript/expressions/ExprShuffledList.java
src/main/java/ch/njol/skript/expressions/ExprSortedList.java

Fix Wrong Shuffled List Registration

---

src/main/java/ch/njol/skript/expressions/ExprPing.java

Requirements: Paper (or any other spigot fork with a getPing method under Player$Spigot)
Description:
You can now get people's ping

Add ping expression

---

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/conditions/CondHasMetadata.java
src/main/java/ch/njol/skript/expressions/ExprDefaultValue.java
src/main/java/ch/njol/skript/expressions/ExprMetadata.java
src/main/java/ch/njol/skript/expressions/ExprMetadataValue.java
src/main/java/ch/njol/skript/expressions/ExprTernary.java
src/main/java/ch/njol/skript/registrations/Converters.java
src/main/java/ch/njol/util/coll/CollectionUtils.java

Related issues: none
Description:
Read more about what metadata is here
https://bukkit.org/threads/tutorial-metadata-what-it-is-and-how-to-use-it.276338/

Add metadata support

---

.gitignore
.idea/fileTemplates/Effect.java
.idea/fileTemplates/Expression.java

I've added some stuff to `.gitignore` and did some trivial changes to the templates to reflect the format & naming style used in most of the project

Improve .gitignore and update the IntelliJ templates

---

README.md
docs/index.html
src/main/java/ch/njol/skript/Skript.java
src/main/java/ch/njol/skript/log/SkriptLogger.java
src/main/resources/features.sk

Changed from `bensku/Skript` to `SkriptLang/Skript`

Update links to the repo

---

src/main/java/ch/njol/skript/expressions/ExprPlayerWeather.java
src/main/java/ch/njol/skript/util/WeatherType.java

I've totally forgotten that in Java you need to `break;` between cases and my code for handling resetting was poor too.. 
Like I've mentioned though, I got a new PC a few days ago so I'm testing everything before PRing. This code *does* work 👍
#1368

Fix player-specific weather

---

src/main/java/ch/njol/skript/lang/Conditional.java

Add an error message for multiple 'else' sections

---

src/main/java/ch/njol/skript/effects/Delay.java

Related issue: https://github.com/SkriptLang/Skript/issues/1394#issuecomment-406562703

Fix the ability to wait a local variable amount of time

---

src/main/java/ch/njol/skript/conditions/CondHasClientWeather.java
src/main/java/ch/njol/skript/expressions/ExprPlayerWeather.java
src/main/java/ch/njol/skript/util/WeatherType.java

Improve ExprPlayerWeather and add CondHasClientWeather

---

src/main/java/ch/njol/skript/ScriptLoader.java

Add support for single files in loadStructures(File)

---

src/main/java/ch/njol/skript/conditions/CondIsSlimeChunk.java

Target Minecraft versions: tested on Paper 1.12.2 and Spigot 1.8.8
Related issues: #678

Add CondIsSlimeChunk

---

src/main/java/ch/njol/skript/expressions/ExprPermissions.java

Fix for lists in permissions https://github.com/SkriptLang/Skript/issues/1456
I really hate this syntax, wish it wasn't added.

Fix for list permissions

---

src/main/java/ch/njol/skript/conditions/CondStartsEndsWith.java

**Description**
`starts with` and `ends with` were reversed:
```java
return ends ? s.startsWith(p) : s.endsWith(p);
```
I fixed this and edited the code for more consistency.

Fix CondStartsWith

---

src/main/java/ch/njol/skript/lang/Variable.java

One way of implementing the idea described in #1440.
Leaving it here as a PR in case you think the warning could be worded better, or anything else

Add a warning for single ':'s in variable names

---

src/main/java/ch/njol/skript/entity/SimpleEntityData.java
src/main/resources/lang/english.lang

Target Minecraft versions: 1.13
Related issues: #1385 
Description:
I hope this is done correctly, but I added the new mobs for 1.13 as I noticed they hadn't been done yet. 
The only one I KNOW isn't done correctly is the tropical fish, as I know they have many variants with their colors and patterns, but I wasn't sure how to do that part.
Special Note:
I have tested this and they DO work.

1.13 new mobs

---

docs/index.html

english level is now over 9000

Improve the Englishness of your docs

---

src/main/java/ch/njol/skript/util/VisualEffect.java
src/main/resources/lang/english.lang

Target Minecraft versions: 1.13.x
Related issues: #1385 
Description:
Added in the new particles and potion/status effects from 1.13.x

1.13 Particles and Potion Effects

---

src/main/java/ch/njol/skript/expressions/ExprName.java

Target Minecraft versions: *any means 1.9+*
Related issues: https://github.com/SkriptLang/Skript/issues/1472
Description: Actually add inventory name change support, not "it's suppose to work"
#Pyon 
This whole class needs to be redone, it's actually horrible. Since the inventory name supports both display name and name the code has to be duplicated, this is the same with others, another reason why it's not the greatest expression class.

Actually add inventory name change support

---

src/main/java/ch/njol/skript/conditions/CondIsSwimming.java
src/main/java/ch/njol/skript/events/SimpleEvents.java

Target Minecraft versions: 1.13+
Requirements: 1.13+
Related issues: #1385 
Description:
Added in the swim event and a swim condition
Both have been tested and work

Swim event & Condition

---

src/main/java/ch/njol/skript/expressions/ExprOfflinePlayers.java
src/main/java/ch/njol/skript/expressions/ExprWorlds.java

isSingle should be constant for ExprOfflinePlayers & ExprWorlds
@Pikachu920 told me to do this.

Make isSingle constant for ExprOfflinePlayers & ExprWorlds

---

src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java

Just a basic PR which should fix the calcExperience function returning invalid values
---
**Target Minecraft Versions :** any
**Requirements :** None
**Related Issues :** #2040

Fix calcExperience returning weird/negatives values

---

README.md

Fix a small typo in readme
---
**Target Minecraft Versions:**  N/A   
**Requirements:**   N/A  
**Related Issues:**  N/A

Fix a small typo in readme

---

README.md

Grammar correction
---
**Target Minecraft Versions:**     None
**Requirements:**     No

http://its-not-its.info/

---

src/main/resources/lang/english.lang

- I forgot to add raiders
- Added the `e` to foxes plural
---
**Target Minecraft Versions:** Targets 1.14+

english.lang - Fixes

---

src/main/java/ch/njol/skript/util/VisualEffect.java

Added in a getter for the effect of VisualEffect. This will help addons use the effect from the VisualEffect type.
---

Exposed VisualEffect "Effect" for addon usage

---

src/main/java/ch/njol/skript/conditions/CondIsBlock.java

Someone I was talking to was looking for a way to check if an item was a block, so here it is. 
A Fancy new condition to check if an item is a block
---
**Target Minecraft Versions:** All

CondIsBlock - New

---

src/main/java/ch/njol/skript/conditions/CondContains.java

- Fix issue where cant check if an inventory contains an item stored in a variable
---
**Related Issues:** #2045

CondContain - Fixes

---

src/main/java/ch/njol/skript/Skript.java

Fixes some of Skript's files not being generated if the scripts folder is still present.
---
**Related Issues:** #1755

Fix File Generation

---

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/effects/EffCancelEvent.java

Found some typo errors so I made this
---

Fix some typos

---

src/main/java/ch/njol/skript/effects/EffLeash.java
src/main/java/ch/njol/skript/expressions/ExprLeashHolder.java

- Fixes console error when trying to get leash holder of a non-leashed entity
- Makes `unleash` actually work
- Adds support for multiple inputs to the leash holder expression
- Improves code quality
---
**Related Issues:** #2166

Fix leash stuff

---

src/main/java/ch/njol/skript/expressions/ExprEntities.java

There was an unnecessary (centerEntity variable) thing in ExprEntities that causes `villagers in radius 5 of loop-value` to return nothing. (loop-value is a location, `location of loop-value` fixes it)
It was added by Njol in this commit: https://github.com/Njol/Skript/commit/5ee575ceab5ea4cb36a807d9931ccfd97e4e3f26#diff-605ca7486acde265dd00ee333375f3d5
But it is stays for nothing now.
I deleted that and also improved the code without any logic change.
---

Improve & fix ExprEntities.java

---

README.md

Updated README to add a download section (some people couldn't find the downloads) also improved something.

Update README, download section and improvements

---

docs/events.html
src/main/java/ch/njol/skript/events/SimpleEvents.java
src/main/java/ch/njol/skript/expressions/ExprAltitude.java

Fixes typos and other links leading to an invalid page in docs

Fix typos and wrong links in SimpleEvents

---

src/main/java/ch/njol/skript/expressions/ExprAffectedEntities.java

Fix doc of affected entities expression

---

src/main/java/ch/njol/skript/expressions/ExprReversedList.java
src/main/java/ch/njol/skript/expressions/ExprShuffledList.java

This pull request adds an expression to reverse a list: `reversed %objects%`
---
**Related Issues:** #2260

Add Reversed List Expression

---

src/main/java/ch/njol/skript/conditions/CondAlphanumeric.java

Adds an ``is alphanumeric`` / ``isn't alphanumeric`` condition into Skript. Did some testing with regular variables and list variables, seems good, but please help me test. Thanks! :)
---
**Related Issues:**     #2324

Alphanumeric Condition

---

src/main/java/ch/njol/skript/expressions/ExprName.java

- Improved code quality
- Improved/updated docs
Looks like the current docs style doesn't support lists, it will look like [**this**](https://i.ibb.co/t8pt8Vg/image.png), but it is meant to look like [**this**](https://i.ibb.co/R25TgT0/image.png).
- Added support for non-living entities
- Added support for changing inventory names
---
**Related Issues:** #2139

Improve ExprName

---

src/main/java/ch/njol/skript/expressions/ExprHash.java

Removed an extra letter that has nothing to do there ^^
---

Solving a little example issue

---

src/main/java/ch/njol/skript/util/slot/InventorySlot.java

Adds a check for calling ``getItem()`` with the index ``-999``
---
**Related Issues:**     #2306

Fix InventorySlot NPE

---

src/main/java/ch/njol/skript/events/EvtLevel.java
src/main/java/ch/njol/skript/events/SimpleEvents.java

This is a rather simple event since it's just a simple check though I believe users could find this useful or at least Njol thought so, at some point.
---
**Target Minecraft Versions:** N/A.
**Requirements:** N/A.
**Related Issues:** N/A.

Add level up/down event

---

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java

Add an option to parse an entity by their UUID
---
**Target Minecraft Versions:** all versions
**Related Issues:** #1352

Parse entity by UUID

---

src/main/resources/scripts/command with cooldown.sk

Made a new command with cooldown.sk that utilises the new command cooldown thingies
The old command cooldown example is outdated. This is my newer version of the script.
---
**Target Minecraft Versions:** Any (1.9+)
**Requirements:** 2.2-dev33+ (Related to above)

Updated command with cooldown.sk

---

src/main/java/ch/njol/skript/expressions/ExprGlowing.java

Replaces ExprGlowing's example with a valid example.
---
**Requirements:**     Any
**Related Issues:**     #2518

Fix ExprGlowing Example

---

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/events/EvtItem.java
src/main/java/ch/njol/skript/events/SimpleEvents.java
src/main/java/ch/njol/skript/expressions/ExprLevelProgress.java
src/main/java/ch/njol/skript/expressions/ExprSpeed.java

As the title suggests. @TheBentoBox 
---

Gender-Neutral Pronouns

---

.github/workflows/gradle.yml

Use Github Actions for building and running test scripts.
---
**Related Issues:** #2541

Configure Github actions for Gradle

---

src/main/java/ch/njol/skript/conditions/CondAI.java
src/main/java/ch/njol/skript/expressions/ExprAI.java

LivingEntity AI Syntax

---

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
src/main/java/ch/njol/skript/conditions/CondIsRiptiding.java
src/main/java/ch/njol/skript/events/SimpleEvents.java

Adds EvtRiptide and CondIsRiptiding
---

EvtRiptide and CondIsRiptiding

---

src/main/java/ch/njol/skript/conditions/CondLeashed.java

Adds a condition to check if an entity is leashed.
---
#Hacktoberfest

Add leashed condition

---

src/main/java/ch/njol/skript/entity/LlamaData.java
src/main/resources/lang/english.lang

Fix some issues with llamas including:
- reversal of llama/trader llama
- colors of trader llamas not working
---
**Target Minecraft Versions:** 1.14+
**Related Issues:** #2573 
- I ended up having to create a second set of llamas in the lang file for the trader llamas with their colors. I tried so many different ways to use the current lang file, but no matter what I tried, I was not able to color the trader llamas, nor delete the llamas properly. 
With this current method I have done, you are able to spawn a llama or trader llama of any color, you are also able to delete specific llamas, based on color or if they're a trader.
ex:
```vb
delete all brown llamas
delete all creamy trader llamas
delete all trader llamas
delete all llamas
```
If anyone has a better way …

LlamaData - fix

---

src/main/java/ch/njol/skript/aliases/ItemData.java

- Fix some matching issues with item meta (match quality going up and down when it should only go down)
---

ItemData - fixes

---

src/main/java/ch/njol/skript/expressions/ExprPlayerWeather.java
src/main/java/ch/njol/skript/util/WeatherType.java

Fix some issues with not properly setting/resetting player's weather
---
**Related Issues:**  #2551

ExprPlayerWeather - fix

---

src/main/java/ch/njol/skript/ScriptLoader.java
src/main/java/ch/njol/skript/expressions/ExprRespawnLocation.java

This PR applies the fix for reloading scripts proposed [here](https://github.com/SkriptLang/Skript/issues/2612#issuecomment-549073854) to hopefully have this problem not leak into any further releases, beta or otherwise.
---
**Related Issues:** #2612

Apply fix for reloading scripts proposed by NickAcPT

---

src/main/java/ch/njol/skript/events/SimpleEvents.java

This PR adds a new event for when the player damages an item
---
**Related Issues:** none that I could find

Player damage item event - new

---

src/main/java/ch/njol/skript/effects/EffExplosion.java

This PR is another explosion related one. It adds the ability to create fiery explosions with the explode effect. I also removed an old check, as there is no point for it.
---

Explosion Effect Updates

---

src/main/java/ch/njol/skript/entity/EntityData.java
src/main/java/ch/njol/skript/expressions/ExprEntities.java
src/test/skript/tests/syntaxes/expressions/ExprEntities.sk

This PR adds chunks to the Entities expression, enabling a user to be able to get the entities in a chunk.
I'm setting this to a draft PR as I think it probably needs some work. I haven't dealt enough with the EntityData class in the past, so I don't feel terribly confident on what I have done there.
I'm looking for any feedback you guys would like to offer.
---

ExprEntities - add chunks

---

gradle.properties
src/main/java/ch/njol/skript/conditions/CondIsCharged.java
src/main/java/ch/njol/skript/effects/EffChargeCreeper.java
src/main/java/ch/njol/skript/effects/EffPotion.java
src/main/java/ch/njol/skript/expressions/ExprArrowsStuck.java
src/main/java/ch/njol/skript/expressions/ExprCreeperMaxFuseTicks.java
src/main/java/ch/njol/skript/expressions/ExprEntities.java
src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java
src/main/java/ch/njol/skript/expressions/LitNewLine.java

Prepare for release 2.5-alpha2

---

gradle.properties
src/main/java/ch/njol/skript/conditions/CondIgnitionProcess.java
src/main/java/ch/njol/skript/effects/EffExplodeCreeper.java

Preparation for release of 2.5-alpha3
---

Prepare for release of 2.5-alpha3

---

src/main/java/ch/njol/skript/effects/EffScriptFile.java

Fixes #2913 by using the proper method to reload script.
---
**Related Issues:** #2913

Fix use of wrong method in EffScriptFile (Fixes #2913)

---

gradle.properties
src/main/java/ch/njol/skript/expressions/ExprScripts.java

Prepare for the release of 2.5-alpha4

Prepare for release of 2.5-alpha4

---

gradle.properties
src/main/java/ch/njol/skript/conditions/CondIsBlockRedstonePowered.java
src/main/java/ch/njol/skript/expressions/ExprRedstoneBlockPower.java

Prepare for release of Skript 2.5-alpha5 (a rather small update, with a focus on the remaining Minecraft 1.16 content, see releases tab for the draft of this release)

Prepare for release of 2.5-alpha5

---

src/main/resources/config.sk
src/main/resources/lang/korean.lang

---
**Target Minecraft Versions:All versions**     
**Requirements:none**     
**Related Issues:none**

Add Korean Language

---

src/main/java/ch/njol/skript/ScriptLoader.java

After talking on Discord with @Pikachu920 just after https://github.com/SkriptLang/Skript/pull/3066 was merged, we decided it was better to not make a copy of the list.
---

Don't copy the configs for calling PreScriptLoadEvent

---

src/main/resources/lang/korean.lang

---
**Target Minecraft Versions: All Versions**     
**Requirements: none**     
**Related Issues: none**

Modifying Korean Language Accuracy

---

src/main/java/ch/njol/skript/classes/data/JavaClasses.java

Spelling error "frational"
---
**Requirements:**

frational -> fractional

---

gradle.properties
src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
src/main/java/ch/njol/skript/conditions/CondHasRelationalVariable.java
src/main/java/ch/njol/skript/conditions/CondIncendiary.java
src/main/java/ch/njol/skript/effects/EffIncendiary.java
src/main/java/ch/njol/skript/events/SimpleEvents.java
src/main/java/ch/njol/skript/expressions/ExprAppliedEnchantments.java
src/main/java/ch/njol/skript/expressions/ExprEnchantItem.java
src/main/java/ch/njol/skript/expressions/ExprEnchantingExpCost.java
src/main/java/ch/njol/skript/expressions/ExprEnchantmentBonus.java
src/main/java/ch/njol/skript/expressions/ExprEnchantmentExpCosts.java
src/main/java/ch/njol/skript/expressions/ExprEnchantmentOffer.java
src/main/java/ch/njol/skript/expressions/ExprEnchantmentOfferCost.java
src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
src/main/java/ch/njol/skript/expressions/ExprExplosionBlockYield.java
src/main/java/ch/njol/skript/expressions/ExprExplosionYield.java
src/main/java/ch/njol/skript/expressions/ExprExplosiveYield.java
src/main/java/ch/njol/skript/expressions/ExprFallDistance.java
src/main/java/ch/njol/skript/expressions/ExprGameRule.java
src/main/java/ch/njol/skript/expressions/ExprRelationalVariable.java
src/main/java/ch/njol/skript/expressions/ExprTimeSince.java

Prepare for release of 2.5-alpha6

---

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java

---
**Target Minecraft Versions:** 1.11+    
**Requirements:**   none  
**Related Issues:**   #3162

Add the hit block event value to the on projectile hit: event

---

src/main/java/ch/njol/skript/expressions/ExprScripts.java

Should fix the issue.
**Related Issues:**     #3193

Fix PatternSyntaxException in ExprScripts

---

src/main/java/ch/njol/skript/registrations/EventValues.java

---
spelling error
**Target Minecraft Versions:**
**Requirements:**

exculdes -> excludes

---

src/main/java/ch/njol/skript/expressions/ExprLastLoginTime.java

Added 'last login time' and 'first login time' to get when the player last/first logged in the server

---

src/main/resources/lang/korean.lang

fixing "scripts loaded" correct ordinal error for value
---
**Target Minecraft Versions: All** 
**Requirements: none** 
**Related Issues: none**

Fix korean.lang

---

src/main/resources/lang/english.lang

This PR aims to fix some errors that are noticeable in the test scripts, just some missing entries in the lang file.
---

Add missing lang file entries

---

build.gradle

This PR updates the skriptTestDev server to 1.16.1
---
**Target Minecraft Versions:** 1.16.1

Update skriptTestDev server to 1.16.1

---

gradle.properties
src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/conditions/CondHasRelationalVariable.java
src/main/java/ch/njol/skript/effects/EffStopServer.java
src/main/java/ch/njol/skript/events/SimpleEvents.java
src/main/java/ch/njol/skript/expressions/ExprBlockData.java
src/main/java/ch/njol/skript/expressions/ExprFertilizedBlocks.java
src/main/java/ch/njol/skript/expressions/ExprHealReason.java
src/main/java/ch/njol/skript/expressions/ExprLastLoginTime.java
src/main/java/ch/njol/skript/expressions/ExprRelationalVariable.java
src/test/skript/tests/syntaxes/expressions/ExprRelationalVariable.sk

This PR is to prepare for the release of alpha7
- Temporarily disabling persistent data features until it is fixed/working properly.
---

Prepare for release of 2.5-beta1

---

src/main/java/ch/njol/skript/bukkitutil/EntityUtils.java
src/main/java/ch/njol/skript/entity/EntityData.java
src/test/skript/tests/regressions/3253-entitydata fixes.sk

This PR aims to do some changes to EnityData:
- Introduce an EntityUtils class, which can simplify some of the steps in EntityData, as well as provide some simple methods for getting/setting age of entities that can be used in future expressions/effects/conditions/etc.
- Fix an issue with some age comparisons of entities (see #3252)
This has been well tested and works very nicely :)
---
**Related Issues:** #3252

Updates to EntityData

---

gradle.properties
src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
src/main/java/ch/njol/skript/hooks/economy/expressions/ExprBalance.java

Prepare for release of 2.5-beta3

---

src/main/java/ch/njol/skript/util/BlockStateBlock.java
src/main/java/ch/njol/skript/util/DelayedChangeBlock.java

This PR aims to update some classes due to some changes in Paper
---

BlockStateBlock - update to match Paper's update

---

gradle.properties
src/main/java/ch/njol/skript/conditions/CondIsLoaded.java

Prepare for release of 2.5-beta4

---

gradle.properties

Prepare for release of 2.5

---

src/main/java/ch/njol/skript/expressions/ExprFilter.java

I added a `', ` to close the apostrophe and make this a bit easier to read and understand :)
---
**Target Minecraft Versions:**  Any

Updated docs description on ExprFilter

---

gradle.properties
src/main/java/ch/njol/skript/conditions/CondIsFuel.java
src/main/java/ch/njol/skript/conditions/CondIsOccluding.java
src/main/java/ch/njol/skript/conditions/CondIsPassable.java
src/main/java/ch/njol/skript/conditions/CondIsUnbreakable.java
src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
src/main/java/ch/njol/skript/conditions/CondProjectileCanBounce.java
src/main/java/ch/njol/skript/conditions/CondStartsEndsWith.java
src/main/java/ch/njol/skript/effects/EffForceAttack.java
src/main/java/ch/njol/skript/effects/EffOpenBook.java
src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
src/main/java/ch/njol/skript/effects/EffSwingHand.java
src/main/java/ch/njol/skript/events/EvtEntity.java
src/main/java/ch/njol/skript/events/SimpleEvents.java
src/main/java/ch/njol/skript/expressions/ExprArrowKnockbackStrength.java
src/main/java/ch/njol/skript/expressions/ExprArrowPierceLevel.java
src/main/java/ch/njol/skript/expressions/ExprBlocks.java
src/main/java/ch/njol/skript/expressions/ExprDropsOfBlock.java
src/main/java/ch/njol/skript/expressions/ExprHealAmount.java
src/main/java/ch/njol/skript/expressions/ExprLastAttacker.java
src/main/java/ch/njol/skript/expressions/ExprLastDamage.java
src/main/java/ch/njol/skript/expressions/ExprMaxMinecartSpeed.java
src/main/java/ch/njol/skript/expressions/ExprMendingRepairAmount.java
src/main/java/ch/njol/skript/expressions/ExprMinecartDerailedFlyingVelocity.java
src/main/java/ch/njol/skript/expressions/ExprNumbers.java
src/main/java/ch/njol/skript/expressions/ExprProjectileBounceState.java
src/main/java/ch/njol/skript/expressions/ExprProjectileCriticalState.java
src/main/java/ch/njol/skript/expressions/ExprRandomUUID.java
src/main/java/ch/njol/skript/expressions/ExprSeaLevel.java

Prepare for release of 2.5.1

---

gradle.properties
src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/conditions/CondIsInteractable.java
src/main/java/ch/njol/skript/conditions/CondIsWhitelisted.java
src/main/java/ch/njol/skript/conditions/CondMatches.java
src/main/java/ch/njol/skript/effects/EffMessage.java
src/main/java/ch/njol/skript/effects/EffPotion.java
src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java
src/main/java/ch/njol/skript/expressions/ExprBlockData.java
src/main/java/ch/njol/skript/expressions/ExprItemFrameSlot.java
src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
src/main/java/ch/njol/skript/expressions/ExprPotionEffect.java
src/main/java/ch/njol/skript/expressions/ExprPotionEffects.java
src/main/java/ch/njol/skript/expressions/ExprSubstring.java
src/main/java/ch/njol/skript/expressions/ExprTypeOf.java
src/main/java/ch/njol/skript/expressions/ExprWhitelist.java

This PR aims to update Skript to 2.5.2

Prepare for release of 2.5.2

---

src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java

Updates ceil function description
---
**Related Issues:** #3806

Update ceil function description

---

.github/contributing.md

Just fixing the missing link.
---

fix missing link in contributing.md

---

src/main/java/ch/njol/skript/aliases/ItemData.java
src/main/java/ch/njol/skript/bukkitutil/BukkitUnsafe.java
src/main/java/ch/njol/util/EnumTypeAdapter.java

Add dynamic enum support
What will be useful in Bukkit+Forge server likes Mohist CatServer Mgama Archlight
---
**Target Minecraft Versions:** 1.16.5
**Related Issues:** https://github.com/Mohist-Community/Mohist/issues/1246

Add dynamic enum support

---

build.gradle
src/main/java/ch/njol/skript/util/BlockStateBlock.java
src/main/java/ch/njol/skript/util/DelayedChangeBlock.java

Update Paper 1.16.4 -> 1.16.5

---

build.gradle
src/test/skript/environments/main/paper-1.16.5.json
src/test/skript/tests/regressions/3253-entitydata fixes.sk

This PR simply updates the  testing environment from 1.16.3 -> 1.16.5

Update testing environment 1.16.3 -> 1.16.5

---

src/main/java/ch/njol/skript/lang/SkriptParser.java

This was a mistake from #3852, my bad.
---
**Related Issues:** #3852

Fix SelfRegisteringSkriptEvents not loading

---

src/main/java/ch/njol/skript/conditions/CondContains.java

CondContains called `Expression#getArray` instead of using the expression's checker.
---
**Related Issues:** #4046

Fix CondContains with 'or' ExpressionList

---

src/main/java/ch/njol/skript/Skript.java

Removes the code in Skript#onDisable that is supposed to prevent memory leaks when using the /reload command, but it gave more problems than it solved.
---

Remove reload memory leak preventing code

---

src/main/java/ch/njol/skript/command/ScriptCommand.java
src/main/java/ch/njol/skript/effects/EffChange.java
src/main/java/ch/njol/skript/lang/SkriptParser.java
src/main/java/ch/njol/skript/log/ParseLogHandler.java

Fixes invalid errors caused by #4104.
Since that PR did not work out so great, it would be nice if this one could get some proper testing :)
---
**Related Issues:** #4104

Fallout of 4104

---

src/main/java/ch/njol/skript/conditions/CondIsSlimeChunk.java

Uses Chunk#isSlimeChunk if possible
---
**Target Minecraft Versions:** Any where the method exists
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4106

Fix CondIsSlimeChunk

---

src/main/java/ch/njol/skript/ScriptLoader.java
src/main/java/ch/njol/skript/expressions/ExprArgument.java
src/main/java/ch/njol/skript/lang/Effect.java
src/main/java/ch/njol/skript/lang/EffectSectionEffect.java
src/main/java/ch/njol/skript/lang/Statement.java

Makes EffectSections usable in effect commands, EffDoIf and alike.
---

Make EffectSections available in effect commands and more

---

src/main/java/ch/njol/skript/util/Direction.java

The code was outdated, it had to be updated to use a newer material system from Bukkit (I kept backwards compatibility).
---
**Related Issues:** #3876

Fix cannot get data class of modern material exception

---

src/main/java/ch/njol/skript/expressions/ExprMe.java

See https://github.com/SkriptLang/Skript/issues/2710#issuecomment-653282101, I did option D
**For changelog writer, see https://github.com/SkriptLang/Skript/pull/4265#issuecomment-898260017**
---
**Related Issues:** #2710

Make return type of ExprMe player

---

src/main/java/ch/njol/skript/conditions/CondContains.java
src/test/skript/tests/syntaxes/conditions/CondContains.sk

Fixes another issue with CondContains which caused the tests of #3961 to fail
---
**Related Issues:** #3961

More CondContains fixes

---

src/main/java/ch/njol/skript/expressions/ExprWorld.java

Add support for "world of %chunk%" expression.
#4217 
---
**Related Issues:** #4215

Add world of chunk support

---

src/main/java/ch/njol/skript/lang/Variable.java
src/test/skript/tests/regressions/4143-nested-variables-erroring-in-2.6-beta1.sk

Fixes an NPE when using variables in effect commands. The issue is not present in release, as it is caused by #3979 which was merged after the release of 2.6.
NPE: https://pastebin.com/SpHTLDds
---
**Related Issues:** #3979

Fix effect commands variable NPE on master branch

---

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java

This PR adds more info to location toString method to show the yaw, pitch and world of location
---
**Related Issues:**  #4427 (non-fixing)

🚀 Add more info to location toString

---

src/test/skript/environments/extra/paper-1.10.2.json
src/test/skript/environments/extra/paper-1.11.2.json
src/test/skript/environments/extra/paper-1.13.2.json
src/test/skript/environments/extra/paper-1.14.4.json
src/test/skript/environments/extra/paper-1.17.1.json
src/test/skript/environments/extra/paper-1.17.json
src/test/skript/environments/main/paper-1.12.2.json
src/test/skript/environments/main/paper-1.16.5.json
src/test/skript/environments/main/paper-1.9.4.json

This PR fixes build failure due to Paper API update to v2
---
**Related Issues:**  #4439

🛠 Fix Paper API v2

---

src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java

This PR fixes a bug explained in this issue #4431
---
**Related Issues:**  #4431

🛠 Fix timespan from date expr

---

src/main/resources/lang/default.lang

---
**Target Minecraft Versions:**  1.18 +
**Requirements:**  1.18 +

Add 1.18 biomes in default.lang

---

src/test/skript/README.md

Update the test syntaxes documentation.
View at https://github.com/TheLimeGlass/Skript/blob/patch-11/src/test/skript/README.md

Update test system README.md

---

src/main/java/ch/njol/skript/registrations/EventValues.java

This boolean was accidentally inverted, I've renamed the variable to clear up confusion as well.
---
**Related Issues:** #4565

Fix another EventValue selection checkInstanceOf issue

---

src/main/java/ch/njol/skript/expressions/ExprYawPitch.java
src/main/java/ch/njol/util/VectorMath.java

Fixes ExprYawPitch changing with plural arguments.
Example exception when using plural arguments for changing: https://pastebin.com/T1xGtYpe
---

Add VectorMath#copyVector and fix ExprYawPitch changing

---

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/classes/data/DefaultConverters.java

This will return the left side block by spigot default 
---
- #4681

⚒️ Fix double chest inventory holder converter

---

gradle.properties
src/main/java/ch/njol/skript/expressions/ExprHanging.java
src/main/java/ch/njol/skript/expressions/ExprPlayerProtocolVersion.java
src/main/java/ch/njol/skript/expressions/ExprSaturation.java

Prepare for 2.6.2 release

---

src/main/resources/lang/default.lang

Temporarily changes the pattern of the composter visual effect to avoid literal conflict. A better change will be made soon, hopefully.
---
**Related Issues:** #4773 (non-fixing)

Temporarily change composter particle pattern

---

gradle.properties

Updates the Skript version in gradle.properties on the master branch too.
---

Update version on master branch

---

gradle.properties
src/main/java/ch/njol/skript/entity/ThrownPotionData.java

Cherry pick commits for 2.6.4
---
**Target Minecraft Versions:**  1.13-
**Related Issues:**  
- #4933

🚀 Update Dev/2.6 -> 2.6.4

---

src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
src/main/java/ch/njol/skript/effects/EffDrop.java
src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java

This PR fixes some of Skript's most CRUCIAL events!
I had to use Material#isAir so I turned that one EffDrop method into public API
---
**Target Minecraft Versions:** Any (probably cherrypick for 2.6.4)
**Requirements:** Any
**Related Issues:** N/A (not sure how someone didn't catch this 🤣)

Fix silverfish events

---

src/main/java/ch/njol/skript/util/BlockStateBlock.java
src/main/java/ch/njol/skript/util/DelayedChangeBlock.java

Fixes 1.19 builds being broken (see https://github.com/SkriptLang/Skript/pull/4911/commits/4264eb052632c6f9d729c2187ebe1d512948c447 for an example)

Implement missing methods for Block implementations

---

README.md

This adds a section for our new [Testing Community](https://discord.gg/ZPsZAg6ygu) to the README!
---
**Related Issues:** None?

Add testing community section to README

---

src/main/resources/config.sk
src/main/resources/lang/english.lang
src/main/resources/lang/polish.lang

I took the changes by @3meraldK from #4544, applied my own suggestions on it, then I compared the results and the version submitted by @Zabujca997 in #4891 side-by-side, line-by-line, overwriting lines that in my opinion sounded better, adding some small adjustments.
On top of that I read everything in English and in Polish again to see how the translation compares with the English counterparts. This is the result.
@3meraldK, @Zabujca997, feel free to leave me a review :)
---

Add translation to the Polish language

---

src/main/java/ch/njol/skript/conditions/CondWithinRadius.java

This PR adds a condition for checking if a location is within a certain radius around another location.
---
**Related Issues:** #5201

Add Location Within Radius condition

---

src/main/java/ch/njol/skript/expressions/ExprSubstring.java

Fixing #5196
Renamed expression as per @Fusezion Suggestion.
---
**Related Issues:** #5196

change subtext doc name to substring to find easier

---

src/main/java/ch/njol/skript/events/EvtItem.java

This PR aims to add support for `on entity drop` event
Also did some code cleanup as per suggested by Ayham :) 
---

EvtItem - add support for EntityDropItemEvent

---

src/main/java/ch/njol/skript/Skript.java

Allow the readme.txt to be generated in lang folder

Allow the readme.txt to be generated in lang folder

---

README.md

🚀 Update docs link in README

---

src/main/java/ch/njol/skript/lang/function/FunctionReference.java
src/main/java/ch/njol/skript/lang/function/Functions.java
src/main/java/ch/njol/skript/lang/function/Namespace.java

This PR fixes an NPE which results when trying to use functions in an effect command
---

Fix Function NPE

---

src/main/java/ch/njol/skript/lang/Variable.java

This PR fixes a bug where Skript would error when trying to use variables in effect commands, like so:
---
**Requirements:** any

Fix Variables in Effect Commands

---

src/main/java/ch/njol/skript/expressions/ExprRawString.java

This PR fixes a bug where the 'raw string' expression would return the formatted string of a non-literal
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5515

Fix Raw String of non-literal

---

src/test/skript/README.md

Add info about clearing your tests in the test README
Preview at https://github.com/SkriptLang/Skript/blob/feature/test-clearing/src/test/skript/README.md

Add info about clearing your tests in the test README

---

src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java

This PR adds `on falling block falling` event to Skript!
---
***Waiting on merge of #5358 for rebase***

New Event: Falling Block Fall

---

src/main/java/ch/njol/skript/doc/HTMLGenerator.java
src/main/java/ch/njol/skript/lang/function/JavaFunction.java

Blame Pikachu :p
---
- closes https://github.com/SkriptLang/skript-docs/issues/26

🛠 Fix docs searching keywords not included in classinfos and functions

---

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
src/main/java/ch/njol/skript/events/SimpleEvents.java

(cherry picked from commit 3dd5394e53e247face129d726be2d5e709e90fd4)
cherry pick for 2.7.0 release due to high demand
see https://github.com/SkriptLang/Skript/pull/5474

[2.7.0 target] Add InventoryDragEvent (#5474) to 2.7.0 release

---

src/main/java/ch/njol/skript/expressions/ExprRawString.java

This PR switches [Java 9's replace method](https://docs.oracle.com/javase/9/docs/api/java/util/regex/Matcher.html#replaceAll-java.util.function.Function-) with Skript's method
---
**Related Issues:** #5794

Fix ExprRawString using a Java 9 feature

---

src/main/java/ch/njol/skript/effects/EffStopSound.java

Cherry picked version of https://github.com/SkriptLang/Skript/pull/5758 for 2.7.0

[2.7.0 target cherry pick] Fix the stop sound effect pattern

---

src/main/java/ch/njol/skript/events/EvtItem.java

When you search pickup on the docs, the on pick up doesn't display. Added keywords to help find it easier.

Allow on pickup to be found easier on docs

---

src/main/java/ch/njol/skript/effects/EffPush.java

Catch the exception when pushing entity by non finite vector

---

src/main/java/ch/njol/skript/expressions/ExprRawString.java

2.7.0 target for https://github.com/SkriptLang/Skript/pull/5795

[2.7.0 target] Fix ExprRawString using a Java 9 feature

---

src/main/java/ch/njol/skript/expressions/ExprTarget.java

Method not returning after meeting the MODE condition and continuing on super.init which causing the UnsuportedOperationException
---
- #5761

🛠 Fix ExprTarget UOE

---

src/main/java/ch/njol/skript/expressions/ExprTarget.java

(cherry picked from commit 7be44daf7b3292cc9c1175ef7bb9ec1db93ffbc7)
2.7.0 target of https://github.com/SkriptLang/Skript/pull/5844
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5761

[2.7.0 target] Fix ExprTarget UOE

---

src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
src/test/skript/tests/regressions/pull-5748-fix bugs in the random number expression.sk

(cherry picked from commit 457a47d66c48c1d29ad43d960537ddba868b8343)
Cherry pick for 2.7.0 of https://github.com/SkriptLang/Skript/pull/5748

[2.7.0 target] Fix bugs in the random number expression (#5748)

---

src/main/java/ch/njol/skript/effects/EffActionBar.java

2.7.0 target of https://github.com/SkriptLang/Skript/pull/5833
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5776

[2.7.0 target] Fix EffActionBar NullPointException when message is null

---

src/main/java/ch/njol/skript/util/Utils.java

Cherry pick [#5798](https://github.com/SkriptLang/Skript/pull/5798) for 2.7.0
(cherry picked from commit 6caf20c5fe8acd49179e385e1819bd8ca0e57c7e)

[2.7.0 target] Fixes error not properly being caught (#5798)

---

src/main/resources/lang/default.lang

Fixes current actions not passing due to this
---

🚀 Add Teleport Cause EXIT_BED

---

src/main/resources/lang/default.lang

Cherry picked  (#5887) for 2.7 branch, also fixes actions for #5886
---

[2.7] 🚀 Add Teleport Cause EXIT_BED

---

src/main/java/ch/njol/skript/Skript.java

**Cherry picked #5892 for 2.7**
Remove delayed task call around variable loading
It is already in a delayed task.
---

[2.7] Address Variable Loading Changes (#5892)

---

src/main/java/ch/njol/skript/expressions/ExprBookPages.java
src/test/skript/tests/syntaxes/expressions/ExprBookPages.sk

[2.7.0 target] Enhancement/books 5863

---

src/main/java/ch/njol/skript/SkriptConfig.java
src/main/resources/config.sk

2.7.0 target for #5917 
---
**Related Issues:** #5917

[2.7.0 target] Disable Timings for 1.19.4+ 5917

---

src/main/java/ch/njol/skript/effects/EffEnchant.java

⚒ [2.7] Fix enchanting multiple items

---

src/main/java/ch/njol/skript/structures/StructCommand.java

🛠 [2.7] Fix Duplicated Spaces in StructCommand (#5416)

---

src/main/java/ch/njol/skript/conditions/CondIsInfinite.java
src/main/java/ch/njol/skript/effects/EffPotion.java
src/main/java/ch/njol/skript/util/PotionEffectUtils.java

🍒 [2.7] Add infinite and icon to potion effects

---

src/main/java/ch/njol/skript/ScriptLoader.java
src/main/java/ch/njol/skript/structures/StructCommand.java
src/main/java/ch/njol/skript/structures/StructOptions.java
src/main/java/org/skriptlang/skript/lang/entry/EntryContainer.java
src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java
src/main/java/org/skriptlang/skript/lang/entry/util/LiteralEntryData.java
src/main/java/org/skriptlang/skript/lang/entry/util/TriggerEntryData.java
src/main/java/org/skriptlang/skript/lang/entry/util/VariableStringEntryData.java
src/main/java/org/skriptlang/skript/lang/script/Script.java
src/main/java/org/skriptlang/skript/lang/structure/Structure.java

Cherry picked #5669 for 2.7
---

🍒 [2.7] Structure API Finalization (#5669)

---

src/main/java/ch/njol/skript/SkriptEventHandler.java
src/main/java/ch/njol/skript/lang/SkriptEvent.java

Cherry picked #5699 for 2.7
---

🍒 [2.7] Fixes an exception from being thrown on async events

---

src/main/java/ch/njol/skript/effects/EffPotion.java

Cherry pick #5992 for 2.7 branch
---

⚒ [2.7] EffPotion - fix potion duration issue

---

src/main/java/ch/njol/skript/effects/EffKeepInventory.java
src/main/java/ch/njol/skript/effects/EffRespawn.java
src/main/java/ch/njol/skript/expressions/ExprLevel.java

Cherry picked #5658 for 2.7
---

🛠 [2.7] Fix keep inv/exp and other bugs related to death event (#5658)

---

gradle.properties

Bump version to 2.7.1 due to the following needing added;
- Issues that are found in current 2.7.0 version.
- Aliases needing to be updated to 1.20

Bump version to 2.7.1

---

src/main/java/ch/njol/skript/effects/EffSendTitle.java

Allow for `send title ... to player for 1.5 seconds with fade in 0 seconds and with fade out 0 seconds`
---

Allow and with for the title effect

---

src/main/java/ch/njol/skript/config/Config.java

Cleaned up some old bits in the `Config` class.
- Removed redundant field initialiser
- Removed unused `line` field
- Moved ConfigReader to a try-with-resources
- Switched the input stream source to `Files.newInputStream` (FileInputStreams have a finalizer on older java versions and distributions, making them a lot more resource intensive; this was removed eventually so it probably won't impact most users)
- Cleaned up some whitespace
- Merged some try/catch blocks
- Gave the variables proper names :')
---

Tidy up parts of config class.

---

CLOCKWORK_RELEASE_MODEL.md
README.md

This PR adds the new release model document to the repository. It also includes a quick reference to it in the README (there may be a better spot for it).
I plan to open another PR after this one to continue improving our other documents.
---
**Related Issues:** n/a

Add Release Model Document

---

src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java

* Avoid NPE and clean up class
* Update ExprEntityAttribute.java
* Update src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
* Update src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
---------
---

(Cherry Pick) Fix NPE with invalid attributes and clean up ExprEntityAttribute (#5978)

---

src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java

It seems I made a silly and forgot to start the LogHandler.
---

Fix Logging Issues In ExpressionEntryData

---

gradle.properties

- Updates version property to 2.7.2
- Updates aliases submodule
This should be merged as the last commit for 2.7.2 (e.g. https://github.com/SkriptLang/Skript/pull/6159 should be merged first if we want it)
---

Prepare For Release (2.7.2)

---

src/main/java/ch/njol/skript/events/SimpleEvents.java

Fix arm swing description to address all. Weird small description fix.
---

Fix arm swing description

---

src/main/java/ch/njol/skript/SkriptEventHandler.java

This PR updates the SkriptEventHandler to run `SkriptEvent#check` asynchronously if `SkriptEvent#canExecuteAsynchronously` returns true, For events that can execute asynchronously, this forces the thread the pause as it waits for the main thread to finish execution and report back. This leads to delays as shown in https://github.com/APickledWalrus/skript-placeholders/issues/50. Asynchronous events should have full control over what is and what is not executed on the main thread. 
This is a behavioral change to the API, but I believe it is in the best interest for this to be merged as a patch. I doubt there has been any significant usage (if any at all) of this API as well.
Thoughts are welcome :)
---

Allow asynchronous SkriptEvent#check execution

---

gradle.properties

Updates version to `2.7.3`
---

Prepare for Release (2.7.3)

---

gradle.properties
src/main/java/ch/njol/skript/SkriptEventHandler.java
src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
src/main/java/ch/njol/skript/expressions/ExprSets.java
src/test/skript/tests/regressions/6205-location comparison.sk

Merges `dev/patch` into `master` for 2.7.3
---

Merge `dev/patch` into `master` (2.7.3)

---

gradle.properties
src/main/java/ch/njol/skript/SkriptEventHandler.java
src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
src/main/java/ch/njol/skript/expressions/ExprSets.java
src/test/skript/tests/regressions/6205-location comparison.sk

i squashed the first time 😬 
---

Merge `dev/patch` into `master` (2.7.3, take 2)

---

src/main/java/ch/njol/skript/util/BlockUtils.java

Fixes BlockUtils throwing a NullPointerException on toString when using Skript's own BlockStateBlock.
```
[13:21:28] [Server thread/ERROR]: #!#! Stack trace:
[13:21:28] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[13:21:28] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.BlockUtils.blockToString(BlockUtils.java:149)
[13:21:28] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.classes.data.BukkitClasses$3.toString(BukkitClasses.java:226)
[13:21:28] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.classes.data.BukkitClasses$3.toString(BukkitClasses.java:212)
[13:21:28] [Server thread/ERROR]: #!#!     at …
```

Fix BlockUtils with BlockStateBlock

---

src/main/java/ch/njol/skript/command/Commands.java

https://github.com/SkriptLang/Skript/pull/6211 was mistakenly squashed
---

Merge `master` into `dev/feature` (attempt 2 :))

---

src/main/java/ch/njol/skript/command/CommandHelp.java

This PR updates the CommandHelp class to only instantiate Message objects when necessary, rather than on creation. This is to prevent using an incomplete lang node with the Message object, which leads to these misleading errors being logged when the verbosity is set to `debug`:
---

Optimize CommandHelp instantiation to prevent misleading errors

---

gradle.properties

- Updates Version
- Updates skript-aliases submodule
---

Prepare For Release (2.8.0)

---

gradle.properties

updates version and aliases submodule
---

Prepare For Release (2.8.3)

---

src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
src/main/java/ch/njol/skript/expressions/ExprAnvilText.java

This PR aims to fix the example of the ExprAnvilText expression.
While in there, I also wanted to update the Location function examples... to give a better understanding of how the function works.
(I previously had these examples on SkriptHub but id rather refer people to official docs)
---

Examples Update

---

src/main/java/ch/njol/skript/conditions/CondIsPathfinding.java

Adds pathfinding condition
---
**Requirements:** Paper

Adds pathfinding condition

---

src/main/resources/lang/default.lang

This PR aims to get a head start on attributes coming in Minecraft 1.20.5
Please do not merge until just before release of next Skript update
In the event MC adds more attributes in the coming weeks, Ill update this PR 
---

Add MC 1.20.5 Attributes

---

gradle.properties

Prepare for Release (2.8.4)

---

src/main/java/ch/njol/skript/entity/EntityData.java

This PR aims to fix an issue with attempting to spawn a non-spawnable entity (such as "mob") and it throwing an error
---
**Related Issues:** #6428

EntityData - fix issue with attempting to spawn non spawnable types

---

src/main/resources/lang/default.lang

This PR aims to add the charged creeper as an option in the lang
---
**Related Issues:** #6435

default.lang - add charged creeper

---

src/main/java/ch/njol/skript/util/BlockStateBlock.java
src/main/java/ch/njol/skript/util/DelayedChangeBlock.java

Fixes build failures due to Block interface changes.
---

Fix building / Implement missing Block methods

---

src/main/java/ch/njol/skript/entity/SimpleEntityData.java
src/main/resources/lang/default.lang

This PR aims to add new 1.20.5 entities
---

Add 1.20.5 entities

---

gradle.properties

Bump version to 2.8.5

---

src/main/resources/lang/default.lang

This PR aims to add some Minecraft 1.21 attributes
---
**Target Minecraft Versions:** 1.21+

default.lang - add MC 1.21 attributes

---

src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
src/test/skript/tests/regressions/6811-inventory-holder-location-doublechest.sk

I have added a converter check for DoubleChest. Aswell as a regression test.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/6811

Added holder instanceof DoubleChest check to converter

---

.github/workflows/archive-docs.yml

Fix archive docs requiring release-docs job
---

Fix archive docs requiring release-docs job

---

src/main/resources/lang/default.lang

This PR adds a few missing lang entries
---

Add Missing 1.21 Lang Entries

---

src/main/resources/lang/default.lang

This PR simply fixes issues in the lang file regarding missing entity potion effects that were added.
---

Fixes lang file issues

---

src/main/java/ch/njol/skript/entity/EntityData.java
src/main/java/org/skriptlang/skript/bukkit/displays/DisplayModule.java
src/test/skript/tests/regressions/7187-display entities conversion.sk

Fixes #7187
adds regression test
fixes block display of blockdata by removing regex check for entity data parser
---
**Related Issues:** #7187

Add entity to display converter

---

src/main/java/ch/njol/skript/registrations/EventValues.java

Fix registering EventValues for addons

---

src/main/java/ch/njol/skript/expressions/ExprExperienceCooldownChangeReason.java

Added a missing space in the documentation of the Experience Cooldown Change Reason expression.
---
**Requirements:** same as target branch

Added missing space.

---

src/main/java/ch/njol/skript/sections/SecFor.java

When the syntax changed, an example was missed.
---

Fix outdated for-each loop example.

---

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java

Add event-block to command struct

---

.github/ISSUE_TEMPLATE/bug-report.yml

This PR aims to update the Guidelines of when creating an issue, to ensure users dont make issues for unsupported versions
---

Github Issue Update

---

src/main/java/ch/njol/skript/expressions/ExprSets.java
src/test/skript/tests/regressions/7327-expr-sets-return.sk

This PR aims to fix an issue with the return type in ExprSets.
I got the idea for the fix from ExprEntities
---
**Related Issues:** #7326

ExprSets - fix return issue

---

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
src/main/java/ch/njol/skript/conditions/CondLeashWillDrop.java
src/main/java/ch/njol/skript/effects/EffDropLeash.java
src/main/java/ch/njol/skript/events/EvtLeash.java
src/main/java/ch/njol/skript/expressions/ExprUnleashReason.java
src/main/resources/lang/default.lang

This PR adds leash event and its methods into Skript!
Javadocs:
- https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/PlayerLeashEntityEvent.html
- https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/EntityUnleashEvent.html
- https://jd.papermc.io/paper/1.20/org/bukkit/event/player/PlayerUnleashEntityEvent.html
---
**Related Issues:** #6420

Add Leash Event and Its Methods

---

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
src/main/java/ch/njol/skript/conditions/CondIsValid.java
src/main/java/ch/njol/skript/config/Config.java
src/main/java/ch/njol/skript/expressions/ExprNode.java
src/main/java/ch/njol/skript/expressions/ExprScriptsOld.java
src/main/resources/lang/default.lang

The final requested housekeeping changes for the whole branch.
(Also fixes a little issue I spotted in the old scripts expression.)
---

Fix final housekeeping changes.

---

src/main/java/ch/njol/skript/test/runner/TestFunctions.java

Fix trailing underscore (thank you sovde)

---

.gitmodules

specifies the branch minimized-aliases for the skript-aliases submodule
---

Make sure the alias submodule updates via the correct branch

---

src/main/java/ch/njol/skript/test/runner/EffTestPluralClassInfos.java

This PR aims to remove some test elements from the docs.
If there are any more you know of, let me know and I'll add them to this PR.
Exhibit A:
---

Remove some test elements from the docs

---

src/test/skript/tests/syntaxes/expressions/ExprColorOf.sk

This PR aims to fix failing tests.
---
**Related Issues:** #7529

ExprColorOf.sk - fix failing tests

---

src/main/java/ch/njol/skript/test/platform/Environment.java

Alternative solution for #7457 without breaking changes.
---

Force Test Server Locale to English

---

src/test/java/org/skriptlang/skript/test/tests/utils/DateTest.java

Fix DateTest failing occasionally

---

gradle.properties
src/main/java/ch/njol/skript/classes/data/BukkitClasses.java

Prepare for 2.10.2

---

src/main/java/ch/njol/skript/events/EvtBeaconEffect.java
src/main/java/ch/njol/skript/events/EvtBeaconToggle.java

This PR aims to fix 2 skript event classes that has annotation docs instead of the register event method docs
---

Event Annotation/Doc Fix

---

.gitignore

Sovde said to make a new issue adding vscode gitignore
---

.vscode gitignore

---

src/main/java/ch/njol/skript/expressions/ExprSecCreateWorldBorder.java

While working with ExprSecCreateWorldBorder, I found the original documentation and behavior very confusing.  It was unclear how virtual worldborders should be used, and setting them up properly for players
---

Clarify Create Virtual WorldBorder docs and behavior

---

src/test/skript/tests/regressions/2581-all potions are water.sk
src/test/skript/tests/regressions/4938-time played.sk
src/test/skript/tests/regressions/6907-playsound entity method doesn't exist.sk
src/test/skript/tests/syntaxes/effects/EffVisualEffect.sk
src/test/skript/tests/syntaxes/expressions/ExprEntityAttribute.sk

Removes mentions of unsupported versions from tests
---

Cleanup Tests

---

gradle.properties
src/main/java/ch/njol/skript/lang/SkriptParser.java
src/test/skript/tests/syntaxes/structures/StructFunction.sk

Prep for 2.12 release

---

gradle.properties

Prepare for release (2.12.2)
