src/main/java/ch/njol/skript/command/ScriptCommand.java
This is a minor change to how Skript registers commands for scripts. Instead of registering the command map to the created Bukkit command, the command is registered to Bukkit's command map.
I made this change from @Zbob750's advice after discovering an issue with [Skript commands and command blocks on PaperSpigot](https://github.com/PaperMC/Paper/issues/256). Despite PaperSpigot having since added a workaround, I figured it would be better to fix this for Skript.
By registering via the command map, all Skript commands and their aliases gain a duplicate with the `skript:` prefix. For example, this Skript command:
```
command /servertime:
description: Get's the server's IRL time/date
aliases: /stime, /date
executable by: players and console
trigger:
broadcast "&7*** Current server …
```
=> Register commands via command map rather than vice versa

src/main/java/ch/njol/skript/expressions/ExprAlphabetList.java
Fix #43, add alphabetically sorting of strings.
=> Fix #43, add alphabetically sorting of strings

src/main/resources/aliases-english.sk
Allows Skripts to pick both kinds of rabbit and mutton meat (raw and cooked). Consistent with `any beef` and `any chicken` aliases.
* Local Spigot 1.11 server
* `CraftBukkit version git-Spigot-f950f8e-9dee108 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
* Plugins (1): Skript dev22e
* Using default Skript config and aliases
* No Skript addons
Tested with Skript:
```
on right click:
if held item is any mutton or any rabbit meat:
message "*** Held: %held item%"
```
=> Add `any mutton` and `any rabbit meat` aliases

src/main/java/ch/njol/skript/effects/EffOpenInventory.java, src/main/java/ch/njol/skript/effects/EffReplace.java, src/main/java/ch/njol/skript/expressions/ExprInventorySlot.java, src/main/java/ch/njol/skript/expressions/ExprOpenInventory.java, src/main/java/ch/njol/skript/expressions/ExprUUID.java
* Fixed previous commit on `EffReplace` that was trowing a `SkriptAPIException` for using `getSingle()` wrongly, [Stacktrace here](https://hastebin.com/ripaseguhu.bash). Also added an option to replace items in inventory as it was in TODO.
```
replace (all|every|) %itemstacks% in %inventories% with %itemstack%
replace (all|every|) %itemstacks% with %itemstack% in %inventories%
```
* Fixed `EffOpenInventory` surrounding with try/catch as Bukkit throw `IllegalArgumentException` when a player can't open a specific inventory.
* Added support for `entities` in `ExprUUID`.
* Added new expressions to get the slot of a inventory and to get a top inventory.
```
[the] slot %number% of %inventory%
%inventory%'[s] slot %number%
[the] (current|open|top) inventory of %player%
%player%'[s] …
```
=> 2 new expressions and fix for EffReplace and EffOpenInventory

src/main/java/ch/njol/skript/bukkitutil/PassengerUtils.java, src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/classes/data/DefaultComparators.java, src/main/java/ch/njol/skript/effects/EffDrop.java, src/main/java/ch/njol/skript/effects/EffVehicle.java, src/main/java/ch/njol/skript/entity/BoatData.java, src/main/java/ch/njol/skript/entity/SimpleEntityData.java, src/main/java/ch/njol/skript/events/EvtItem.java, src/main/java/ch/njol/skript/expressions/ExprLastSpawnedEntity.java, src/main/java/ch/njol/skript/expressions/ExprPassenger.java, src/main/resources/lang/english.lang
**Changes**:
* Added boat support for `1.10+`:
* Patterns: `boat, any boat, oak boat, spruce boat, birch boat, jungle boat, acacia boat, dark oak boat`
* `boat` and `any boat` works like a supertype when comparing, but `boat` spawns a `oak boat` and `any boat` spawns a random boat in spawn effects.
* Also added boat to the default comparator of entity's materials to work when compared "with items".
* Boats will return it's type when returned as string, like `oak boat`.
* Added multiple passenger support for `1.11.2+`.
* The syntax still the same, the difference is for 1.11.2+ will return a list instead of a single entity and can accept all changers (add, remove, set...).
* For 1.11 and lower will be the same as previously: single entity and it can only be setted.
* Changed the syntax of …
=> Boat support, multiple passengers, "last dropped item" expression, new event values and fixes.

src/main/java/ch/njol/skript/effects/Delay.java, src/main/java/ch/njol/skript/util/AsyncEffect.java
This class allows you to make an effect that doesn't walk to the next trigger item until the execute method is done running. It also adds the current event to the delayed events list. If needed, I can make it optionally require the execute method to call `done()` (a new method which just walks to the next trigger item) from within it. This would be good if the execute method does an operation without blocking the current thread. I also added a public static method to [Delay](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/effects/Delay.java), so I could add the event to the delayed events list without something "hacky" like Reflection.
Class used to test this:
```java
@Name("Test")
@Description("test")
@Examples({"test"})
@Since("test")
public class EffTest …
```
=> Add a handy class that makes doing Asynchronous Effects easily.

src/main/java/ch/njol/skript/lang/Variable.java
Fixed variable list deletion for mysql  and possibly other databases. Attempting to delete variable lists from a database would lead to nothing happening. This fixes that.
=> Fixed list deletion for databases

src/main/java/ch/njol/skript/variables/DatabaseStorage.java, src/main/resources/config.sk
Target Minecraft versions: All supported by Skript
Requirements: SQLibrary installed as always
Related issues: Add enhancement #666 
Description:
Adds support for changing the table name of variables stored in a database. If no table name is specified, it will default to `variables21` because many are using that table right now because it was formerly hardcoded as that. The table name is specified right along side the database name in config.sk. Both MySQL & SQLite variable storages support custom table names.
=> Add support for changing the table name for variables stored in databases

src/main/java/ch/njol/skript/command/Commands.java
Target Minecraft versions: All that Skript supports
Related issues: Fixes #802 
Description:
Changes the message `A command with the name /ch.njol.skript.command.ScriptCommand@<some string> is already defined in <script>.sk` to `A command with the name of <command name> is already defined in <script>.sk`
=> Properly print command name in command already exists script error

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/SkriptCommand.java, src/main/java/ch/njol/skript/conditions/CondScriptLoaded.java
Related issues: Adds enhancement #797 
Description:
Adds a condition to check if scripts are loaded. Syntaxes: `script[s] [%-strings%] (is|are) loaded`, `script[s] [%-strings%] (isn't|is not|aren't|are not) loaded`
=> Add a condition to check if script[s] are/aren't loaded

src/main/java/ch/njol/skript/effects/EffKill.java
Related issues: Fixes #783
Description:
The kill effect was not killing pigs via damage because pigs are vehicles. I fixed this by checking if it also was not damageable. When I was trying to reproduce the bug, I also noticed that ender dragons + their parts were not being killed properly because ender dragons won't die via damage (at least in my testing) and the parts couldn't be cast to living entities to get their max health.
=> Make the kill effect kill ender dragon (parts too) and pigs properly

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/EvtBookEdit.java, src/main/java/ch/njol/skript/events/EvtBookSign.java, src/main/java/ch/njol/skript/expressions/ExprBookAuthor.java, src/main/java/ch/njol/skript/expressions/ExprBookPages.java, src/main/java/ch/njol/skript/expressions/ExprBookTitle.java
Related issues: Adds enhancement #106 
Description:
Adds an on book sign event, an on book edit event, and _book title, author, & pages (specific pages also) expressions_.
=> Add book events and expressions

src/main/java/ch/njol/skript/registrations/Classes.java, src/main/resources/lang/english.lang, src/main/resources/lang/german.lang
Related issues: Add enhancement #646 
Description:
Localizes how null values (nothing) show up in strings.
=> Localize how null values show up in strings

src/main/java/ch/njol/skript/lang/function/Function.java, src/main/java/ch/njol/skript/lang/function/FunctionEvent.java
Related issues: Adds enhancement #610 
Description:
On [Function#execute](https://github.com/xXAndrew28Xx/Skript/blob/master/src/main/java/ch/njol/skript/lang/function/Function.java#L90-L109) it will now call the event and pass the function on to it.
=> Call the function event on Function#execute and pass the Function onto the event

src/main/java/ch/njol/skript/expressions/ExprHash.java
This PR corrects `@Since` for ExprHash.
(see [my comment](https://github.com/bensku/Skript/commit/8739d231a80b99e627f27f01d7b7b2ffa700a84c#commitcomment-24490474) on last commit)
=> Fix @Since for ExprHash

src/main/java/ch/njol/skript/Skript.java
Description:
Currently, if a plugin hook fails Skript gives a vague `Error while loading plugin hooks` error and doesn't print the stacktrace unless Skript's verbosity is set to debug. This PR makes it print regardless of Skript's verbosity settings.
=> Always print a stacktrace when a plugin hook error occurs

src/main/java/ch/njol/skript/Skript.java
Description:
Fixes a typo in the exception format
=> Fix Typo in Exception Format

README.md
Requirements: No
Description:
Small update to the README to include Skript Hub as a Relevant Link.
Thanks!
=> Added Skript Hub to the Relevant Links Section

.gitignore, src/main/java/ch/njol/skript/expressions/ExprPermissions.java
Target Minecraft versions: **any**
Requirements: **none**
Related issues: #900
Description:
This PR adds a way to loop all permission that a player has,
Test Skript:
```
on join:
set {_perms::*} to all permissions of player
message "Welcome %player%! You have %amount of {_perms::*}% permissions."
message "Here they are: "
loop player's permission:
message " -> %loop-value%"
if player has permission "bukkit.command.me": # a default permission
message "You have permission ""bukkit.command.me"""
else:
message "You do not have permission ""bukkit.command.me"""
```
ps. it worked just fine in IntellJ IDEA.
=> Add "All Permissions" expression

src/main/java/ch/njol/skript/expressions/ExprChatRecipients.java
Having both return types will default to only allowing single pass-throughs because it's the first of it's type in the acceptChange method, It will not accept multiple in this case.
Tested and found out in a bug issue I had on Discord in skript-chat #skriptdev.
=> Fixing ExprChatRecipients to allow multiple entries

src/main/java/ch/njol/skript/SkriptConfig.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/resources/config.sk
Related issues: #981
Description:
Adds a config option to disable the `List is missing 'and' or 'or', defaulting to 'and'` warning. Tested and works as expected.
=> Add config option to disable warning

src/main/java/ch/njol/skript/expressions/ExprTime.java
Related issues: #983 
Description:
Allows the time expression to use time periods to make it more user-friendly. Tested and working.
=> Enhance time expression

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
Target Minecraft versions: 1.8
Related issues: Many, many requests and issues
Description:
This PR allows for the newest Skript versions to load on 1.8. This is still not support and will revert the situation to what is was before dev29's release.
=> Allow newer versions of Skript to be loaded on 1.8

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
Target Minecraft versions: 1.9+
Related issues: PR #1014 
Description:
Just noticed that Skript#isRunningMinecraft actually returns true is you are on that version *or higher*, so the previous PR broke visual effects on 1.9-1.12. I've now changed to checking if the particle class exists instead.
Sorry for not testing my previous PR thoroughly. I thought would be trivial (damn misleading method names...). At least I noticed before a new release.
=> Fix Previous PR

src/main/java/ch/njol/skript/lang/function/Functions.java, src/main/java/ch/njol/skript/lang/function/Parameter.java
Related issues: #1007
Allows the usage of indexes in parameter names.
=> Allow variables with index in function parameters

src/main/java/ch/njol/skript/effects/EffKill.java
Related issues: #977, #937, #934
Description:
This PR aims to (hopefully) fix the problems when killing entities that extend Damageable but cannot be killed by the damage method (blame Spigot). It also adds `kill %entities% without drops` which will directly execute the Entity#remove method on the entity. 
Tested on 1.12.2 and 1.9.0 (thanks to @Nicofisi for testing).
=> Fix and enhance kill effect

src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java
Related issues: Adds enhancement #1041 
Description:
Adds an expression that returns a Date (ch.njol.skript.util.Date) that is a timespan before/after the current Date.
Syntaxes:
```
%timespan% (ago|in the past)
%timespan% (later|from now)
```
=> Add %timespan% ago/later expression (#1041)

src/main/java/ch/njol/skript/expressions/ExprYawPitch.java
Related issues: Fixes #1033
Description:
Before, the changer would convert 0 to 360, when 0 was a perfectly acceptable value for [Location#setYaw](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Location.html#setYaw-float-).
=> In changer of ExprYawPitch, if 0 is passed, keep it as 0

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/effects/EffReplace.java
Related issues: #1072
Description:
now you can use $ signs without weird behavior yay
=> Fix $ sign issues in options and replace effect

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java, src/main/java/ch/njol/skript/effects/EffPlaySound.java, src/main/java/ch/njol/skript/util/VisualEffectDummy.java
Target Minecraft versions: 1.8, 1.9
Related issues: #1076 
Description:
1.8 oriented fixes:
- register visualeffect type with a dummy class if org.bukkit.Particle is missing
1.8 and 1.9 oriented fixes:
- SoundCategory didn't exist on either version, so only use it if the class exists
=> Fix sounds on 1.8 and 1.9

src/main/java/ch/njol/skript/variables/FlatFileStorage.java
Related issues: Fixes the bug explained in #1049 
Description: Variables are saved to the right .csv file on server stop.
=> Fix variable saving

src/main/java/ch/njol/skript/SkriptConfig.java, src/main/java/ch/njol/skript/lang/VariableString.java, src/main/java/ch/njol/skript/variables/FlatFileStorage.java, src/main/resources/config.sk
Related issues: didn't find any
Description:
Adds an option to the config to disable "Starting a variable's name with an expression is discouraged..." warnings.
=> Config option to disable "Starting a variable's name with an expression" warnings

src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java
Currently, the e.damage function does not call the Damage Event, allowing users to bypass any cancellations of the events that they thought that they have in place. A simple test for this is as follows;
```
on damage:
cancel event
command /hurtme [<text>]:
trigger:
damage player by 5
```
From my testing, the player will still be damaged, despite the damage event being cancelled. This change will force Skript to respect the cancellation of the event, prior to the damage being dealt.
*before submitting, remove all help text like this*
Target Minecraft versions: *any means 1.9+*
Requirements: *is Paper required? are there plugin requirements?*
Related issues: *include issue numbers (if any) like #NUMBER*
Description:
*fill something useful that describes your pull request here*
=> Adds Damage Event call to the Damage Effects

src/main/java/ch/njol/skript/lang/Variable.java
Description:
It has become increasingly popular for addons to make async effects that store results in a variable. Right now, you have to use reflection to access the name field. This PR adds a getter so that the reliance on reflection can be removed for newer versions
=> Add getter for Variable's name

src/main/java/ch/njol/skript/SkriptConfig.java, src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/java/ch/njol/skript/command/ScriptCommandEvent.java, src/main/java/ch/njol/skript/effects/EffCancelCooldown.java, src/main/java/ch/njol/skript/expressions/ExprCmdCooldownInfo.java, src/main/java/ch/njol/skript/expressions/ExprCmdElapsedRemainingTime.java, src/main/resources/config.sk
Related issues: PR that originally added it, #1047
Description:
- Adds `last usage date` and changers to the cooldown info expressions.
- Adds `cancel cooldown` effect
- Adds `cooldown storage` option in commands which accept a variable name (surrounding {} is optional)
- Add config.sk option to not delete the `last usage date` after command execution after cooldown period expired.
- Rename `ExprCmdElapsedRemainingTime.java` to `ExprCmdCooldownInfo.java`
Examples:
```
command /vote:
cooldown: 24 hours
cooldown storage: {lastvote::%uuid of sender%}
cooldown message: You may not vote for another %remaining time%.
trigger:
if last usage date is set:
send "You last voted on %last usage date%, which was %elapsed time% ago."
send "Voting Link: …
```
=> Improve command cooldowns

src/main/java/ch/njol/skript/lang/SkriptParser.java
Related issues: fixes #876 
Description:
This pull request fixes the issue that has made Skript way too lenient about plurality of expressions. 
Tested version : PaperSpigot 1.12.2
Addons : MundoSK
Test script : 
```
on script load:
set {_list::*} to 1, 2, 3, 4 and 5
set {_other-list::*} to integers from 0 to 10
send "%size of {_list::*}%" to console
send "%size of {_other-list::*}%" to console
```
Before this pull request, MundoSK's `[border] (size|diameter) of %world%` syntax (hence the presence of MundoSK) would have conflicted and Skript wouldn't have noticed. Now, Skript parses the correct expression and doesn't throw an exception, as it used to do. 
The above code prints `5` and `11` as expected.
=> Fix parser issue with plurality

.travis.yml
Description:
Caches the `.gradle` directory when TravisCI is building. TravisCI can verify that pull requests compile and pass tests properly. @bensku would need to enable it in his https://travis-ci.org account.
=> Use TravisCI again

src/main/java/ch/njol/skript/effects/EffKill.java
Related issues: #937
Description:
This PR removes the logic calling Entity#remove on certain entities and instead attempts to damage the entity, before finally conditionally calling Entity#remove if the entity lives through the damage (via Entity#isValid).
=> Implement a more permanent solution to not all entities being damageable

src/main/java/ch/njol/skript/Skript.java
Description:
Unfortunately, many addon devs are lazy and/or inexperienced with the Skript API and don't provide proper `toString`s for their syntax. This makes finding the root of erroring code a lot harder than it has to be. This PR adds the trigger, it's line number and it's script to Skript#exception to help make it easier to track down erroring code.
example:
```
[14:27:11 ERROR]: #!#! [Skript] Severe Error:
[14:27:11 ERROR]: #!#!
[14:27:11 ERROR]: #!#! Something went horribly wrong with Skript.
[14:27:11 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:27:11 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version). …
```
=> Print trigger when an exception is printed

src/main/java/ch/njol/skript/effects/EffMessage.java
Requirements: Same as before (bungee chat api)
Related issues: #1153 
Description:
Tested cases:
=> Fix the send message effect to be compatible with a list of strings

src/main/java/ch/njol/skript/lang/function/ScriptFunction.java
Related issues: There was one, but it's been closed and I can't find it
Description:
before:
```
function return(number: number) :: string:
if {_number} is 1:
return "uh oh sticky!"
on script load:
broadcast return(1) # uh oh sticky!
broadcast return(2) # uh oh sticky!
```
after:
```
function return(number: number) :: string:
if {_number} is 1:
return "uh oh sticky!"
on script load:
broadcast return(1) # uh oh sticky!
broadcast return(2) # nothing
```
=> Fix sticky function returns

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/events/bukkit/PreScriptLoadEvent.java
Related issues: None on this repo, but it can help addon devs fix issues like the one described in https://github.com/btk5h/skript-mirror/issues/27
Description:
This PR adds a PreScriptLoadEvent that is called when before a script starts loading, if ScriptLoader#callPreLoadEvent is true (modeled after how the bukkit event for functions is only called if Functions#callFunctionEvents is true). This is useful because it allows addon devs to mutate the currentScript Config before it begins loading, to alleviate issues like load order (similar to the ones with functions). 
Here is an example of using this:
```
public class ScriptLoadListener {
@EventHandler
public void onScriptLoad(PreScriptLoadEvent e) {
for (Node node : …
```
=> Add PreScriptLoad event

src/main/java/ch/njol/skript/lang/VariableString.java
Related issues: #1149
Description:
Makes this:
```
command test <string>:
trigger:
broadcast "%join """" with """"%"
```
warn saying this:
```
[17:50:27 WARN]: join "" with "" is already a text, so you should not put it in one (e.g. join "" with "" instead of "%join "" with ""%") (tests.sk, line 28: broadcast "%join """" with """"%"')
```
If anyone has suggestions for a better error message, please speak up because the current one sucks
=> add warning for String expression variablestrings

src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java, src/main/java/ch/njol/skript/lang/function/Function.java, src/main/java/ch/njol/skript/lang/function/FunctionReference.java, src/main/java/ch/njol/skript/lang/function/JavaFunction.java, src/main/java/ch/njol/skript/lang/function/ScriptFunction.java
Description:
#1161 broke returns of recursive functions. This PR fixes sticky functions in a way that does not break recursive functions.
=> Fix returns in recursive functions

src/main/java/ch/njol/skript/expressions/ExprTPS.java, src/main/java/ch/njol/util/coll/CollectionUtils.java
Target Minecraft versions: Any (kinda)
Requirements: A recent version of Paper, the getTPS method relatively recently moved so this will only work on Paper versions released after that move.
Description:
Adds a TPS expresssion that returns the last 3 tps numbers. If you can think of a way to support older Paper versions without reflection, i'll add it.
=> Add tps expression

src/main/java/ch/njol/skript/expressions/ExprFilter.java
Description:
This is basically the where filter from skquery but improved quite a bit.
Improvements:
- A classinfo is no longer required for the input expression (you can just use `input`)
- Using a specific classinfo in the input expression will force the loop type:
```
loop "1", "2" and "3" where [player input is false]:
broadcast "%loop-player%" # usually no loop would match, but since I used player input, it is valid
```
- Should properly work with changers now
Example code:
```
send "you are an admin" to all players where [input has permission "staff"]
loop blocks in radius 10 of player where [block input is air]:
broadcast "%loop-block%"
kill all players where [{hacker::%input's uuid%} is set]
```
=> Add filter expression

src/main/java/ch/njol/skript/expressions/ExprInventory.java, src/main/java/ch/njol/skript/expressions/ExprItemsIn.java
Related issues: Beginners everywhere wondering why an inventory is a single value
Description:
In it's current form, if you try to loop an inventory like this:
```
on click:
loop inventory of player:
broadcast "woah man!"
```
you will get an error saying that an inventory is only a single value and thus cannot be looped. This PR changes the inventory expression to return the items (actually the slots) of an inventory when used in a loop, but maintains the old behavior otherwise.
Example:
```
on click:
loop inventory of player:
broadcast "%loop-slot%"
```
=> Support looping of inventories

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/entity/EntityData.java, src/main/java/ch/njol/skript/lang/ExpressionInfo.java, src/main/java/ch/njol/skript/lang/SkriptEvent.java, src/main/java/ch/njol/skript/lang/SkriptEventInfo.java, src/main/java/ch/njol/skript/lang/SyntaxElementInfo.java, src/main/java/ch/njol/skript/util/VisualEffect.java
Description:
In the previous system calling: 
```kotlin
class.`package`.name
``` 
in kotlin for a SimpleEvent or SimpleExpression would result in 
```
ch.njol.skript.lang.util
```
being returned regardless of if an addon was the origin of the SimpleEvent or SimpleExpression. The addition of the originClassPath allows for a proper class path to the original plugin. This is very useful for documentation generation tools as it prevents other addons SimpleEvents and SimpleExpressions from getting mixed up with Skripts.
=> Add an originClassPath for SyntaxElementInfo

src/main/java/ch/njol/skript/expressions/ExprHighestSolidBlock.java
`World#getHighestBlockAt` turned out to actually return the first light-transparent block *above* the highest solid block. I need to test my code before PRing next time 👍
=> Fix ExprHighestSolidBlock

build.gradle
Removes 3 commented unneeded maven repos, and one uncommented although it was unneeded too. I'm creating this PR since the uncommented one went down today, making Skript impossible to bulid - https://travis-ci.com/Nicofisi/Skript/builds/78580876 https://i.imgur.com/eRdlFue.png
It'd be best if this was merged ASAP, today
=> Remove unused repositories from build.gradle

src/main/java/ch/njol/skript/effects/EffMakeSay.java
Requirements: No
Related issues: https://github.com/SkriptLang/Skript/issues/1291
Description:
Adds an effect that forces players to say messages in the chat.
=> Add Make Say effect

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java, src/main/java/ch/njol/skript/doc/Documentation.java, src/main/java/ch/njol/skript/effects/EffReplace.java, src/main/java/ch/njol/skript/effects/EffVisualEffect.java, src/main/java/ch/njol/skript/events/EvtAtTime.java, src/main/java/ch/njol/skript/events/EvtGameMode.java, src/main/java/ch/njol/skript/expressions/ExprAmountOfItems.java, src/main/java/ch/njol/skript/expressions/ExprChunk.java, src/main/java/ch/njol/skript/expressions/ExprColorOf.java, src/main/java/ch/njol/skript/expressions/ExprCommandSender.java, src/main/java/ch/njol/skript/expressions/ExprDamageCause.java, src/main/java/ch/njol/skript/expressions/ExprDifference.java, src/main/java/ch/njol/skript/expressions/ExprExperience.java, src/main/java/ch/njol/skript/expressions/ExprInventoryAction.java, src/main/java/ch/njol/skript/expressions/ExprLastSpawnedEntity.java, src/main/java/ch/njol/skript/expressions/ExprLocationAt.java, src/main/java/ch/njol/skript/expressions/ExprTeleportCause.java, src/main/java/ch/njol/skript/expressions/ExprTimeState.java, src/main/java/ch/njol/skript/hooks/regions/conditions/CondCanBuild.java, src/main/java/ch/njol/skript/hooks/regions/conditions/CondRegionContains.java, src/main/java/ch/njol/skript/hooks/regions/events/EvtRegionBorder.java, src/main/java/ch/njol/skript/hooks/regions/expressions/ExprBlocksInRegion.java, src/main/java/ch/njol/skript/hooks/regions/expressions/ExprMembersOfRegion.java, src/main/java/ch/njol/skript/hooks/regions/expressions/ExprRegionsAt.java
This pull request fixes many links in the docs, probably they are wrong because they were used in Njol's docs.
**For example:**
The `direction type` link in [ExprDirection](https://skriptlang.github.io/Skript/expressions.html#ExprDirection) is correct
but the `item type` link in [ExprAmountOfItems](https://skriptlang.github.io/Skript/expressions.html#ExprAmountOfItems) is wrong,
The fix is:
```diff
- https://skriptlang.github.io/classes/#itemtype
+ https://skriptlang.github.io/classes.html#itemtype
```
I also changed this, probably should be changed already but still i will note:
https://github.com/SkriptLang/Skript/pull/1438/files#diff-c2d9fabc5bac072b3b2469ae4342cda3
([Documentation.java, line 192](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/doc/Document …
=> Fix documentation links

README.md
Description:
This is an update to the README in order to move addon developers away from using the [GitHub Maven repo](https://github.com/bensku/mvn-repo) and to instead use JitPack. Right now the GitHub Maven repo requires manual updates and doesn't have dev37. Changing to JitPack will remove the need for manual updates and will instead automatically update.
=> Update README to use JitPack for addons

src/main/java/ch/njol/skript/conditions/CondHasScoreboardTag.java, src/main/java/ch/njol/skript/expressions/ExprScoreboardTags.java
Target Minecraft versions: 1.11+
Requirements: Spigot
Related issues: https://github.com/SkriptLang/Skript/issues/346
Description:
https://minecraft.gamepedia.com/Scoreboard#Tags
=> Add scoreboard tags support

src/main/java/ch/njol/skript/expressions/ExprNumbers.java, src/main/java/ch/njol/skript/expressions/ExprTimes.java
- Move `%number% times` into a separate expression
- Warn when a hardcoded 'loop 1 time' or 'loop 0 times' is met.
- Error when a hardcoded 'loop <0 times' is met.
- Do nothing when a non-hardcoded 'loop <1 times' is met.
Originally the code allowed for the expression to [only be used in loops](https://gist.github.com/Nicofisi/cb9acaa666576b2c57f601c03ad7850b), but I removed that restriction since @Snow-Pyon mentioned that other addons depend on this syntax (how?)
The only issue that I see now is that every error & warning message mentions the `loop` but it actually can be used outside of loops. I'm very open to any suggestions about these messages.
I used `Number`s instead of `Integer`s since @Pikachu920 mentioned that there are some known bugs related to an Integer return type / …
=> '%number% times' improvements

src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
*The branch is named incorrectly, meant to be property-conditions as they are something completely different, my bad*
Description:
With this little change more conditions can be `PropertyCondition`s, which is good because classes like [CondCanFly](https://github.com/SkriptLang/Skript/blob/47af5a699571b3bdc0c112a675daff24cae8bbb1/src/main/java/ch/njol/skript/conditions/CondCanFly.java) could simply be written as:
```java
public class CondCanFly extends PropertyCondition<Player> {
static {
register(CondCanFly.class, PropertyType.CAN, "fly", "players");
}
@Override
public boolean check(Player player) {
return player.getAllowFlight();
}
@Override
protected String getPropertyName() {
return "fly";
}
@Override
public …
```
=> Add various property condition types

src/main/java/ch/njol/skript/events/SimpleEvents.java
Props to Nicofisi helping me understand how to make pull requests <3
Requirements: The jump event requires paper
Related issues: /
Description:
SwapHandItems event is used for when the player is using the dedicated key (default F) to swap their main and offhand items. It only fires while not viewing an inventory.
The PlayerJumpEvent event differs from spigot's PlayerMoveEvent and is less resource straining.
Related issues:
https://github.com/SkriptLang/Skript/issues/1445
https://github.com/SkriptLang/Skript/issues/444
=> Add Swap Hand Items and Jump (simple-)events

src/main/java/ch/njol/skript/effects/EffDoIf.java
Related issues: none
Description: 
This executes an effect if a condition is true. The syntax is `[(do|execute)] <.+> if <.+>` where the first regex is an effect and the second is the condition.
Ex:
```java
on join:
give diamond to player if player has permission "rank.vip"
```
Standalone this effect does not conflict with ternaries but if a ternary is used within the effect parenthesis must be used:
```
#invalid
give diamond if {diamond::%player%} is true else emerald to player if player has permission "rank.vip"
#valid
give (diamond if {diamond::%player%} is true else emerald) to player if player has permission "rank.vip"
=> Add EffDoIf

src/main/java/ch/njol/skript/effects/EffActionBar.java
Target Minecraft versions: 1.9+ 
Related issues: Closes #1351 & Closes #1589 (Poorer implimentation that required paper)
Description:
This pull request adds action bar support for all spigot versions on all supported versions of skript 😄 
Syntax: 
`send [the] action bar [with text] %string% to %players%`
=> Add Action Bar Support (not just paper)

src/main/java/ch/njol/skript/effects/EffChange.java, src/main/java/ch/njol/skript/effects/EffSuppressWarnings.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/lang/VariableString.java, src/main/java/ch/njol/skript/util/ScriptOptions.java
Target Minecraft versions: *Any*
Requirements: *N/A*
Related issues: Closes #1260 
Description:
This pull request adds script-specific warning suppression for the following warnings:
* Variable Conflict
* Variable will not be saved
* List missing conjunctions
* Starting Variable with expression
This is accomplished through EffSuppressWarnings:
`[local[ly]] suppress [the] (1¦conflict|2¦variable save|3¦[missing] conjunction[s]|4¦starting [with] expression[s]) warning[s]`
This effect uses the ScriptOptions class to manage what scripts are suppressing what errors.
=> Add Warning Suppressing Effect

src/main/java/ch/njol/skript/effects/EffKill.java
When killing a player, the current implementation will remove a player from the server or have a chance of. This is not intended to happen as this will remove the player's data, a big no no.
Someone on Discord under tag `oflords#2025` reported this issue in the skript help channels in SkUnity. Stating that this happened. This should never even come close to happening when attempting to kill a player.
There are lots of weird things that happen when the player's data is removed including, freezing, removal from tab, having their skin default, them being kicked, them glitching, other players disappearing or worse themselves from others and many more.
=> Handle player killing properly

src/main/java/ch/njol/skript/effects/EffConnect.java, src/main/java/ch/njol/skript/util/Utils.java
Requirements: Bungeecord
Description:
This PR adds an effect that allows scripters to send players to a bungeecord server via plugin messages, like so: `send all players to server "hub"`
This is a PR because I'd like to get @bensku's opinion on the use of `CompletableFuture`s as opposed to spigot's convoluted standard approach.
=> Add connect effect

src/main/java/ch/njol/skript/util/Color.java
Related issues: #1627 
Description:
For whatever reason, this class is restricting Skript from loading in older versions.
And since I was already changing this class, decided to make some changes to it. The main changes are:
* The Bukkit Color isn't referenced anymore (we can use DyeColor#getColor for that).
* Removal of methods using magic values.
The main reason why I am PRing this is due to the removal of these methods, I'd like to know if you guys think it's better to just deprecate them. I am pretty sure any addon nor Skript itself uses these methods so they were just there but I'd still like input on it.
=> Changes to the Color util due to compatibility issues

docs/css/styles.css
Seems to fix the issue regarding the nav bar sometimes jumping up when clicking between elements at the bottom. I just added the same fields that control the outer `nav`'s positioning to the inner `div` as well. 
I've done web design before but I'm still not enough of a CSS aficionado to know why this was necessary, but it does seem to fix it when I edit the CSS live after the issue occurs. @Blueyescat confirmed as well.
=> Fix nav bar occasionally jumping on the docs

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/expressions/ExprDifficulty.java, src/main/java/ch/njol/skript/expressions/ExprSpawn.java, src/main/resources/lang/english.lang
Description: I was surprised when I saw that Skript doesn't have any world difficulty support, so here it is.
Notes:
- I also removed a weird un-needed throw of UnsupportedOperationException when I was looking for similar syntax by Njol to compare from. #SuperOldJava
- I haven't tested if the `normal` difficulty English type name conflicts with `normal` from the villager types. Skript "should" handle it properly since this is implemented properly, and there is support for checking similar names.
=> Add Difficulty

src/main/java/ch/njol/skript/entity/TropicalFishData.java, src/main/resources/lang/english.lang
Target Minecraft versions: 1.13+
Related issues: #1385 
Description:
Adds support for tropical fish, which should add support for every entity once #1486 is merged.
This wasn't tested yet (I bet it doesn't even compile, I'll fix that later), I've made it just to receive input about how it is handled as soon as possible.
=> Add tropical fish support

build.gradle
Fix on WorldEdit building.
Skript fails to build without this fix. WorldEdit changed from Jitpack to CodeMC on their bStats maven url. https://github.com/sk89q/WorldEdit/commit/bf98dcff094c80b5aa789885b07a0b1f7d70dbf6
This fix allows Skript to successfully build again. Talked to the bStats developer and he said if it looks for the repo in Jitpack before CodeMC it will fail. This allows the build to search CodeMC and not fail build.
The bStats developer also says that the repo.bstats.org url hasn't been used in a long time and won't be anymore, just CodeMC and Jitpack.
No one responded in Discord to my conversation I placed about this.
Image of build failure without this:
=> Fix on WorldEdit building failure.

src/main/java/ch/njol/skript/effects/EffPlaySound.java
Updates `EffPlaySound` to default volume and pitch to 1 instead of 0.
---
**Target Minecraft Versions:** any    
**Requirements:** none    
**Related Issues:** resolves #1677
=> Use 1 as default volume and pitch in EffPlaySound

src/main/java/ch/njol/skript/effects/EffFeed.java
Makes EffFeed add to the player's food level instead of setting the food level (e.g. `feed the player by 5 beefs` used to set the player's hunger to 5)
=> Improve EffFeed

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/SkriptConfig.java, src/main/java/ch/njol/skript/aliases/Aliases.java, src/main/java/ch/njol/skript/config/validate/EnumEntryValidator.java, src/main/java/ch/njol/skript/effects/EffOpenInventory.java, src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java, src/main/java/ch/njol/skript/events/EvtGameMode.java, src/main/java/ch/njol/skript/util/chat/MessageComponent.java
This PR specifies English locale in some case conversion methods to don't cause issues with some languages. For example Skript converts the value of the config option `plugin priority` to upper case using the default language. If the OS language is Turkish, that causes it to be converted to `HİGH` etc. and an enum named `HİGH` doesn't exist, causes this error: `The plugin priority has to be one of lowest, low, normal, high, or highest.` and doesn't provide a default value. This happens when converting to lower case, too: `I` -> `ı`
Also this problem exists in many plugins. Skript already used to specify Locales but looks like it is forgotten in some cases. The thing is specify English language if the text is certain to be English.
As a note this problem can be solved using these …
=> Specify English Locale in some case conversion methods

src/main/java/ch/njol/skript/effects/EffOpenInventory.java
Added the hopper, dropper and dispenser to the open inventory effect
---
**Target Minecraft Versions:**     any (1.9+_
**Requirements:**     none
**Related Issues:**    none
I changed the numbers of the parsing from the 20's down to 2,3,4,5,6
I never really understood why its that way.
I tested it, works fine, has no affect on it.
If anyone feels more inventory types should be added, let me know, and I'll quickly throw them in.
=> added Hopper/Dropper/Dispenser to open inventory effect

src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/java/ch/njol/skript/effects/EffCancelCooldown.java, src/main/java/ch/njol/skript/expressions/ExprCmdCooldownInfo.java
- Converted this syntax
```hs
[the] (0¦remaining [time]|1¦elapsed [time]|2¦cooldown [time] [length]|3¦last usage [date]|4¦cooldown 
bypass perm[ission]) [of] [the] [(cooldown|wait)] [((of|for)[the] [current] command)]
```
to
```hs
[the] remaining [time] [of [the] (cooldown|wait) [(of|for) [the] [current] command]]
[the] elapsed [time] [of [the] (cooldown|wait) [(of|for) [the] [current] command]]
[the] ((cooldown|wait) time|[wait] time of [the] (cooldown|wait) [(of|for) [the] [current] command])
[the] last usage [date] [of [the] (cooldown|wait) [(of|for) [the] [current] command]]
[the] [cooldown] bypass perm[ission] [of [the] (cooldown|wait) [(of|for) [the] [current] command]]
```
- Removed curly braces from single-line statements
- Converted space indents to tabs
- Fixed that `last usage …
=> Clean up cooldown stuff

src/main/java/ch/njol/skript/expressions/ExprDamagedItem.java
Can be used to give/set a damaged item.
ie:
```
give player diamond sword with damage value 750
set {_item} to wood hoe with damage value 10
set player's tool to player's tool with damage value 50
```
No one would use that last example, but it works.
In 1.12.2 or lower, you can use this to give/set a damaged item or set a block to a block with a data value.
ie:
```
set target block to target block with data value 7
set target block to potato plant with data value 3
```
---
**Related Issues:** I'm sure this may relate to a few issues, but #1682 directly
=> ExprDamagedItem

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
In the `can build check event`, there is no event value for player.
This was previously reported and said it couldn't be fixed, because until 1.13 there was no `getPlayer()` method. This has now been added.
---
**Target Minecraft Versions:**  1.13+
**Related Issues:** #375
=> Event-CanBuildCheck

src/main/java/ch/njol/skript/classes/VectorArithmethic.java, src/main/java/ch/njol/skript/effects/EffVectorRotateAroundAnother.java, src/main/java/ch/njol/skript/effects/EffVectorRotateXYZ.java, src/main/java/ch/njol/skript/expressions/ExprLocationFromVector.java, src/main/java/ch/njol/skript/expressions/ExprLocationVectorOffset.java, src/main/java/ch/njol/skript/expressions/ExprVectorAngleBetween.java, src/main/java/ch/njol/skript/expressions/ExprVectorArithmetic.java, src/main/java/ch/njol/skript/expressions/ExprVectorBetweenLocations.java, src/main/java/ch/njol/skript/expressions/ExprVectorCrossProduct.java, src/main/java/ch/njol/skript/expressions/ExprVectorCylindrical.java, src/main/java/ch/njol/skript/expressions/ExprVectorDotProduct.java, src/main/java/ch/njol/skript/expressions/ExprVectorFromXYZ.java, src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java, src/main/java/ch/njol/skript/expressions/ExprVectorLength.java, src/main/java/ch/njol/skript/expressions/ExprVectorNormalize.java, src/main/java/ch/njol/skript/expressions/ExprVectorOfLocation.java, src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java, src/main/java/ch/njol/skript/expressions/ExprVectorSpherical.java, src/main/java/ch/njol/skript/expressions/ExprVectorSquaredLength.java, src/main/java/ch/njol/skript/expressions/ExprVectorXYZ.java, src/main/java/ch/njol/skript/expressions/ExprVectorYawPitch.java, src/main/java/ch/njol/skript/expressions/ExprVelocity.java
Cleans up all the vector related stuff; import orders, method orders, unnecessary finals, parameter names, toStrings, getReturnTypes, used CollectionUtils for returns, docs, syntaxes, and other code standard things.
~~Small breaking change: now it is mandatory to use `normalized %vector%` instead of `normalize %vector%`, as suggested by bensku in the related issue.~~
Not sure if i made more breaking changes but probably i didn't
I didn't merge the vector coordinates expression with the MC expression, because allowing `x coord/position/location of vector` doesn't make sense. I used x [component] of vector instead. Anyways it will make the docs confusing if i merge them.
I didn't merge the yaw/pitch expressions too because will look weird in the docs. But only problem i see is `yaw of …
=> Clean up vector stuff

src/main/java/ch/njol/skript/effects/EffBreakNaturally.java
(Reposting - see #1726 for further notes)
New effect for breaking blocks naturally, with an option to add a tool (Ex: If a player's tool is air, breaking stone will drop nothing, if their tool is a pick, it'll drop cobble stone)
---
**Target Minecraft Versions:**  Any version
=> EffBreakNaturally 

src/main/java/ch/njol/skript/classes/ClassInfo.java, src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/effects/EffPlaySound.java, src/main/java/ch/njol/skript/effects/EffStopSound.java, src/main/java/ch/njol/skript/lang/Expression.java, src/main/java/ch/njol/skript/lang/SkriptEventInfo.java, src/main/resources/lang/english.lang
* Fixes the issues with play sound effect and improves its code
* Adds more description and examples to the play sound effect
* Adds multiple sounds support to the play sound effect
* Adds multiple locations support to the play sound effect
* Adds ability to specify sound category in the play sound effect
* Adds ability to playing sounds to players without specifying a location as suggested by @TheLimeGlass in #1921.
* Adds stop sound effect
* Adds sound category enum type, used in play and stop sound effects
* Adds requiredPlugins method to ClassInfo because i needed it for the sound category type
* Fixes inconsistent empty line indentations in BukkitClasses, cleans up its code
---
**Target Minecraft Versions:** any, 1.10.2+ for Stop Sound, 1.11+ for sound categories
**Requirements:** …
=> Improve sound stuff

src/main/java/ch/njol/skript/entity/SimpleEntityData.java, src/main/resources/lang/english.lang
Register Zombie after Husk and Drowned to make sure both of those work.
---
**Target Minecraft Versions:** All (but mainly to fix a 1.13+ issue with Drowned)
**Related Issues:** Issue #2087 
I noticed that the Husk needed to be registered before zombie for it to work. When I added the 1.13 entities last year I did not do the same for the drowned and therefor its not working as expected.
I threw the 1.14 enchantments in here too.
=> SimpleEntityData - Fixes

src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
Fixes non working send block change for 1.13+
---
**Target Minecraft Versions:** The fix targets 1.13+ but still works on all versions
**Related Issues:** #2039
=> EffSendBlockChange - Fix

src/main/java/ch/njol/skript/effects/EffDrop.java
- Fix issue with not being able to drop from a list variable
- Based on what I could see and my testing, the issue came from `"%itemtypes/experience%"`, it looks like the issue was the fact we have 2 types, one which is plural (item types) and one which is singular (experience). My guess the reason its denying the list variable, is because the variable could be either a list of items or a single experience, and at the time of init, the variable's contents are unknown. By allowing multiple experiences this issue is fixed.
---
**Related Issues:** #1917
=> EffDrop - Fixes

src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
There was an issue where when setting a block to stairs, it would place a stair block, and a mirrored stair block above it.
I was told this was an issue due to Stairs and Trapdoors were extending the Bisected class.
Fixed this issue by ignoring stairs and trap doors when checking for bisected blocks.
---
**Target Minecraft Versions:** Target fix for 1.13+
**Related Issues:**  #1977
=> NewBlockCompat - Fixes

src/main/java/ch/njol/skript/expressions/ExprPlayerlistHeaderFooter.java
This pull request adds the ability to modify the tab list header and footer with vanilla spigot with the following syntax:
```vbs
[the] %players% (player|tab) list (1¦header|2¦footer)
```
---
**Requirements:** Spigot 1.13+
**Related Issues:** #1353
=> Add tablist header and footer modification expression

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/effects/EffScriptFile.java
Adds the following self-explanatory syntax which allows users to programmatically enable/disable/reload scripts:
```vbs
(enable|load) s(c|k)ript [file] %string% [[logging] in %objects%]
reload s(c|k)ript [file] %string% [[logging] in %objects%]
(disable|unload) s(c|k)ript [file] %string%
```
---
**Related Issues:** #822
=> Enable/Disable/Reload Scripts Programmatically 

src/main/java/ch/njol/skript/expressions/ExprDrops.java
- Added block break event drops (clearing only)
---
**Target Minecraft Versions:** 1.12+
**Related Issues:** #659
=> ExprDrops - Changes

src/main/java/ch/njol/skript/effects/EffVisualEffect.java
currently clicking 'visual effect' on the play effect effect brings you to `/classes.html#visualeffect` (not found), this fixes that
=> fix for visual effect page not found

docs/templates/navbar.html
this renames "Triggers" on the navbar to "Events", why isn't it already like this?
=> triggers -> events

src/main/java/ch/njol/skript/entity/SimpleEntityData.java, src/main/java/ch/njol/skript/expressions/ExprName.java
Due to the removal of Inventory#getTitle in 1.14, inventory names were no longer available.
With the help of Wheezy I was able to bring this back.
---
**Related Issues:** #2069 
- When I added the MOB entity class, I didn't realize it wasn't in 1.9.4 so I put a condition in for that as well. I know it's not related but it was such a tiny little fix I didn't want to another small PR for that.
=> Fix inventory name

src/main/java/ch/njol/skript/conditions/CondIsAlive.java
Adds non-living entity support to the Is Alive condition and improves its code, docs and syntax.
Using "alive" or "dead" on a non-living entity looks weird, even if this is fine since we use `kill` to delete non-living entities in Minecraft and Skript, i still wanted to add some alternative words: "available" and "valid"
---
=> Add non-living entity support to CondIsAlive

src/main/java/ch/njol/skript/bukkitutil/ClickEventTracker.java, src/main/java/ch/njol/skript/events/EvtClick.java
Click events are a long standing pain point in Skript. They're not reliable enough across all supported Minecraft versions. Some use cases, like clicks on entities, are almost univerally broken.
This pull request abandons lookup tables for click event deduplication. Instead, scripts will simply never receive more than one click event per tick from one player. Skript transparently cancels all events if the first one is cancelled.
There are potential problems with this change:
* Loss of functionality with event-item and 'click with'
* Event-item gets item in *random* hand
* 'click with' is now same as 'click holding'
* Two actual clicks within one tick may be sent by Minecraft client, at least in theory
* Only hacked clients, though?
* Bad connections may split click events from one action …
=> Rework click events to be less hacky

src/main/java/ch/njol/skript/effects/EffBan.java
Since the ban effect does not include a kick, and some users may not know that, it should be mentioned in the documentation.
---
**Related Issues:**     https://github.com/SkriptLang/Skript/issues/2344
=> Add notice that ban effect does not include kick

src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/resources/lang/english.lang, src/main/resources/lang/german.lang
This pull request removed the "Correct Usage:" prefix in front of the usage message in commands due to it being un-customizable.
---
**Related Issues:** #1844
=> Remove Correct Usage Prefix

src/main/java/ch/njol/skript/SkriptCommand.java
Adds a sanity check for invalid script parameters given to getScriptFromName(String script), i.e. it's not ```example.sk```, it's not ```example```. If something like ```spigot.yml``` were to be given to the function, it would return null
---
**Related Issues:**     https://github.com/SkriptLang/Skript/issues/2103
=> Add check for non-skript files

src/main/resources/config.sk
Since the ender dragon example effect command is currently invalid with current versions of Minecraft, it should be replaced with something else.
The rationale for replacing this effect with a money-related one is because griefing/lag is already covered by the explosion force example, and messing around with players is already covered by the ban example.
---
**Related Issues:**     https://github.com/SkriptLang/Skript/issues/1531
=> Replace ender dragon example effect command

src/main/java/ch/njol/skript/effects/EffSpawn.java
Simple change that just adds ```summon``` as an alias to the ```spawn``` effect. I added this since I found it odd that Skript doesn't already have this (since it mostly follows Minecraft nomenclature as much as possible), and Minecraft by default spawns mobs in via ```/summon``` and not ```/spawn```
---
**Target Minecraft Versions:**  Any
=> Add summon as an alias to the spawn effect

src/main/resources/lang/english.lang
Adds ``zombie`` as an alias to ``undead`` for ``undead horse`` in ``english.lang``
---
**Target Minecraft Versions:**     Versions that have horses
**Related Issues:**     #1389
=> Zombie Horse Alias

src/main/java/ch/njol/skript/entity/PandaData.java
Fixes an issue where ThreadLocalRandom generates a random number out of bounds of the Gene array, and also fixes the comparison issue for pandas by adding more checks to match()
(Note: Making separate issues for Cats and Pandas since the causes are different)
---
**Target Minecraft Versions:**     Any MC version with Pandas
**Related Issues:**     #2440
=> PandaData Fixes

src/main/java/ch/njol/skript/entity/CatData.java
Fixes the comparison of cats by properly returning true upon initialization of a cat. This PR also cleans up some of the init code with a ternary
(Note: Making separate issues for Cats and Pandas since the causes are different)
---
**Target Minecraft Versions:**     Any MC version with Cats
**Related Issues:**     #2440
=> Cat Comparison Fix

src/main/java/ch/njol/skript/expressions/ExprPlayerViewDistance.java
- New expression for view distance of player
---
**Target Minecraft Versions:** All (see notes for 1.14.x)
**Requirements:** Requires PaperMC
**Related Issues:** #2010 
- This is currently not working in PaperMC 1.14+
- They removed it from 1.14 with the intention to re-add it back in the future.  (See [**paper**](https://github.com/PaperMC/Paper/issues/2098))
For now this expression will work on 1.9-1.13.2
=> ExprViewDistance - New

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/expressions/ExprPortal.java
Adds a new expression "portal's blocks" / "blocks of portal" to return the portal's blocks via Spigot's PortalCreateEvent.getBlocks() method
---
**Target Minecraft Versions:**     Any (1.9+)
**Related Issues:**     #576
=> Improved PortalCreateEvent

src/main/java/ch/njol/skript/expressions/ExprSkull.java
https://minecraft.gamepedia.com/Mob_head Player "skulls" are referred to as player heads, and the Skript aliases already support this, so the expression should as well
---
=> Add Head as Alias to Skull

src/main/java/ch/njol/skript/conditions/CondContains.java
This PR reworks CondContains to make it more stable:
- Cleaned up its code
- Removed much unnecessary codes
- Fixed some issues
- Added more features
- After the last changes, it wasn't supporting lists like `contains 1 and 2` or `contains 1 or 2`, this is fixed
Here are some codes (effect commands) i used to test:
https://gist.github.com/Blueyescat/eadf558783dd7aa57d7255a069e7d449
*all of them works as expected*
**Current syntaxes:**
```autohotkey
%inventories% (has|have) %itemtypes% [in [(the[ir]|his|her|its)] inventory]
%inventories% (doesn't|does not|do not|don't) have %itemtypes% [in [(the[ir]|his|her|its)] inventory]
%inventories/strings/objects% contain[s] %itemtypes/strings/objects%
%inventories/strings/objects% (doesn't|does not|do not|don't) contain %itemtypes/strings/objects% …
```
=> Rework the contains condition

src/main/java/ch/njol/skript/expressions/ExprSpawner.java, src/main/java/ch/njol/skript/expressions/ExprSpawnerType.java
Adds an expression that allows for the retrieval, setting, and resetting of spawner blocks' entitytype
Note: I ran into an issue where Skript couldn't properly detect entity types when using Bukkit's ``EntityType.class``, so I just stuck with Skript's ``EntityType.class`` for variable's sake but internally it converts between the two for setting/getting the entity type of the spawner block using the helper functions ``toBukkitEntityType()`` and ``toSkriptEntityType()``
---
**Target Minecraft Versions:**     Any*
**Related Issues:**     #1186, #2385
=> Spawner Type Expression

src/main/java/ch/njol/skript/effects/EffCancelDrops.java, src/main/java/ch/njol/skript/effects/EffKeepInventory.java, src/main/java/ch/njol/skript/expressions/ExprDrops.java
ExprDrops will no longer work in block break events, which is returning always null.
I wanted to improve ExprDrops much more, like support for experience drops of blocks, but i failed because of some confusing reasons lol.
```autohotkey
(cancel|clear|delete) [the] drops [of (items|[e]xp[erience][s])]
(cancel|clear|delete) [the] (item|[e]xp[erience]) drops
```
```autohotkey
keep [the] (inventory|items) [(and [e]xp[erience][s] [point[s]])]
keep [the] [e]xp[erience][s] [point[s]] [(and (inventory|items))]
```
---
**Target Minecraft Versions:** Any, 1.12+ for cancelling block item drops
=> Add Cancel Drops and Keep Inventory/Experience effects, improve ExprDrops

src/main/java/ch/njol/skript/effects/EffPlaySound.java
Fixes #2412 by adding a regex check each iteration of the sound array
---
**Related Issues:**     #2412
=> Resolve ResourceKeyInvalidException

src/main/java/ch/njol/skript/lang/Variable.java
Adds further checks to the Variables class to allow asterisks within expressions in lists since currently it only allows asterisks at the end of a list
Test Code:
```
on click:
set {test} to 1 #No Error ✓
set {*test} to 1 #Errors ✓
set {**test} to 1 #Errors ✓
set {test*} to 1 #Errors ✓
set {test:*} to 1 #Errors ✓
set {test::*} to 1 #No Error ✓
set {test:::*} to 1 #Errors ✓
set {test::*::*} to 1 #Errors ✓
set {test::**::*} to 1 #Errors ✓
set {test::%2%::*} to 1 #Errors ✓
set {test::%%::*} to 1 #No Error **?**
set {test:%%::*} to 1 #Errors ✓
set {test::%::*} to 1 #Errors ✓
set {test::&::*} to 1 #No Error ✓
set {test::%5::*} to 1 #Errors ✓
set {test::%2*5%::*} to 1 #No Error ✓
set {test::%2*5%%::*} to 1 #Errors ✓
set {test::::*} to 1 #Errors ✓
```
Oddly enough, ``set {test::&::*} to 1 #No …
=> Allow asterisks within expressions in lists

src/main/java/ch/njol/skript/conditions/CondIsBlocking.java
Makes it slightly more evident to users that the ``blocking`` conditional is referring to a player shielding, and not anything else.
---
**Related Issues:**     #1578
=> Clearer Syntax for CondIsBlocking

src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
Adds an expression to get the amount of time a player has played on the server for.
ex:
```vb
if player's time played is greater than 10 days:
set {legacy::%uuid of player%} to true
```
---
**Related Issues:**  none
=> new ExprTimePlayed

src/main/java/ch/njol/skript/Skript.java
This PR is to add the version of the addons to Skript's sever error messages.
Many times when helping people, they will send a stack trace error. Often times these errors are created by addons, but seeing something like this:
```
[14:13:50 ERROR]: #!#! Here is full list of them:
[14:13:50 ERROR]: #!#! skript-mirror (https://github.com/btk5h/skript-mirror) TuSKe (github.com/Tuke-Nuke/TuSKe) SK-NBeeT (https://github.com/ShaneBeee/Sk-NBeeT) 
```
...is not helpful, as we have no clue which versions of the addons the user is using. Quite often we ask "Which version of Tuske are you using", reply: "latest" or "newest" and more often than not, they are **not** using the "latest" or "newest" version of said addon.
Simply adding the version to the error, we can cut down on asking which version of …
=> SkriptError - add addon version

src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java, src/test/skript/tests/misc/2584-HealthUtils - update.sk
- Removed some really old code that was used before MC 1.6 (prior to MC 1.6, the damageable classes methods used ints, 1.6 introduced using doubles. The reflection methods were introduced by Njol years ago to help handle the difference. Since we don't support below 1.9.4 they are most definitely not needed)
- Updated the java doc notes
- Updated to use attributes to make this class more future proof in the event the deprecated Damageable#getMaxHealth and Damageable#setMaxHealth methods are removed in future Spigot releases
- I have tested this on both 1.9.4 and 1.14.4, everything works swimmingly.
---
This file was using CRLF, I wanted to switch it to LF but figured the PR would be hard to see what was …
=> HealthUtils - update

src/main/java/ch/njol/skript/expressions/ExprClientViewDistance.java
This expression adds the option to grab the view distance from the player's client. 
This can be used hand in hand with the player view distance expression, or you know, just for funnies to see how far a player's client view distance is set.
This may also be handy when doing certain effects for players, making sure they can actually see them. 
---
**Target Minecraft Versions:** 1.13.2+
**Requirements:** Spigot 1.13.2+
=> new ExprClientViewDistance expression

src/main/java/ch/njol/skript/entity/FishData.java
Allows scripts to be able to spawn random fish from the expression ``spawn fish``
Tested with:
``!spawn cod``
``!spawn puffer fish``
``!spawn salmon``
``!spawn tropical fish`` (random functionality still works for this)
``!spawn fish`` (will now randomly spawn cod, puffer fish, salmon, or a random tropical fish!)
---
**Target Minecraft Versions:**     1.13 and above (where fishes became entities)
**Related Issues:**     #2046
=> Random Fish Spawning

src/main/java/ch/njol/skript/expressions/ExprExplodedBlocks.java
Add an expression to retrieve the exploded blocks from an explosion event
---
**Target Minecraft Versions:**  any
**Related Issues:** #2509
=> ExprExplodedBlocks - new

src/main/java/ch/njol/skript/entity/BoatData.java
- Fix an issue where using a right-click event for a block, would fire when clicking on a spruce boat
---
**Target Minecraft Versions:**  1.13+
**Related Issues:** #2609
=> BoatData - fix

src/main/java/ch/njol/skript/entity/VillagerData.java, src/main/resources/lang/english.lang
- Fix an issue with the ordering of villager professions
The issue was comparisons for villager types were not working, ie:
```vb
command /test:
trigger:
if target entity is a cleric:
send "CLERIC"
else:
send "NO?!?!"
```
The villager types would not match.
In the BukkitAPI, the NONE profession is listed after NITWIT:
but when actually printing out the values it appears that NONE is registered first (ergo it's 0 in the list)
ie:
```
[13:44:00 INFO]: Val: NONE
[13:44:00 INFO]: Val: ARMORER
[13:44:00 INFO]: Val: BUTCHER
[13:44:00 INFO]: Val: CARTOGRAPHER
[13:44:00 INFO]: Val: CLERIC
[13:44:00 INFO]: Val: FARMER
[13:44:00 INFO]: Val: FISHERMAN
[13:44:00 INFO]: Val: FLETCHER
[13:44:00 INFO]: Val: LEATHERWORKER
[13:44:00 INFO]: Val: LIBRARIAN
[13:44:00 INFO]: Val: MASON
[13:44:00 INFO]: Val: …
```
=> VillagerData - fix

src/main/java/ch/njol/skript/effects/EffColorItems.java
This fixes an issue with the dye effect throwing errors in console.
---
**Related Issues:** #2623
=> EffColorItems - fix

src/main/java/ch/njol/skript/effects/EffCancelDrops.java
- Fix an issue with console throwing errors when doing actions like picking up water.
---
**Related Issues:** #2645
=> EffCancelDrops - fix

src/main/resources/lang/english.lang
- Match priest/cleric in english.lang file
This changes patterns for priests and clerics to be the same, which allows for using either name on all versions of MC.
This fixes an issue Bensku had with a regression test across all versions (see #2641)
This also creates better compatibility when users are upgrading their server from 1.13.2 and below -> 1.14+ 
I have this PR going to the 2.4 branch, but its not really necessary as a fix in 2.4, but would still be a nice/helpful fix. But if need be I can change it to the master branch. 
---
**Related Issues:** #2641
=> english lang - fixes

src/main/java/ch/njol/skript/events/EvtItem.java
Adds the EntityPickupItemEvent, allowing a Skripter to check if an entity picks up an item, not just a player.
---
**Target Minecraft Versions:** 1.12.2+ 
**Requirements:** 1.12.2
**Related Issues:** #1385
This event was actually added just before 1.12.1 came out. If everyone feels I should change the required version to 1.12.1 I could easily change it, but I think we can all agree no one is running a 1.12 or 1.12.1 server. 
On that note, the readme for Skript clearly states:
""
Skript supports only the **latest** patch versions of Minecraft 1.9, 1.10, 1.11, 1.12 and 1.13. For example, this means that 1.12.2 is supported, but 1.12.1 is not. 
""
=> new EntityPickupItemEvent

src/main/java/ch/njol/skript/conditions/CondIsTameable.java, src/main/java/ch/njol/skript/expressions/ExprEntityTamer.java, src/test/skript/tests/syntaxes/expressions/ExprEntityTamer.sk
This PR adds a new expression to get/set the owner/tamer of an entity (such as a horse or wolf) as well as a new condition to check if an entity is tameable.
---
=> Entity Tameable - NEW

src/main/java/ch/njol/skript/expressions/ExprNumberOfCharacters.java, src/test/skript/tests/syntaxes/expressions/ExprNumberOfCharacters.sk
Adds an expression to get the number of uppercase, lowercase, or digit characters in a string.
I used this expression a lot when I had skUtilities, and figured it'd be useful to have in vanilla Skript.
---
**Related Issues:**     None (I think)
=> Add Number of Characters Expression

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/classes/data/DefaultComparators.java, src/main/java/ch/njol/skript/conditions/CondCompare.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/lang/UnparsedLiteral.java, src/main/java/ch/njol/skript/lang/util/SimpleLiteral.java
This PR fixes all comparison issues detailed in #2637 and issues linked from it. There were multiple causes for them:
* Literal parsers for types not registered (spawn reason, teleport cause)
* Nonsensical comparator usage (entities, e.g. projectiles)
* Ambiguous literals (some of the damage causes)
The first two were rather easy to fix, even if finding them took a while. The third, however, introduces a major change to CondCompare; it now attempts to parse literals of wrong types again, this time with more type information than SkriptParser has.
All of these changes could cause serious regressions. Testing them automatically is not going to help, because Skript can't (yet?) create mock events for test scripts.
---
**Related …
=> Fix the comparison issues

src/main/java/ch/njol/skript/effects/EffBan.java
This PR adds an option time span to the ban effect to allow users to temp ban players.
---
**Related Issues:** #2667 
Special note:
I tried to do a test for this one, but for true testing I need to do a wait. The testing environment appears to ignore waits in testing.
=> EffBan - add an optional time span to temp ban a player

src/main/java/ch/njol/skript/effects/EffEquip.java
Add llamas to the entity equip effect.  You will be able to equip a Llama with a carpet (this is their saddle) as well as a chest.
Also updated the description to say entity not player
---
**Target Minecraft Versions:** 1.11+ (When llamas were introduced)
=> EffEquip - Add llama to entity equip effect

src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java, src/test/skript/tests/syntaxes/expressions/ExprNoDamageTicks.sk
This PR will allow users to get / modify the "no damage ticks" (aka invulnerability ticks) of living entities. Could be useful in scripts for inducing a cooldown on mob hits or for removing naturally occurring invulnerability ticks.
---
=> No Damage Ticks Expression

src/main/java/ch/njol/skript/effects/EffPotion.java
This PR adds in what is described in #2598. The syntax may be able to be improved and I'm open to any suggestions. I have not really made any changes in Skript's code before, so please let me know if I'm doing anything wrong :)
I built these changes and they worked perfectly when I tested them.
I was thinking we could also add in a test for the entire effect but I was not 100% sure on how to do it properly.
---
**Related Issues:**     #2598
=> Apply potion effects without adding onto current duration

src/main/java/ch/njol/skript/expressions/ExprCreeperMaxFuseTicks.java
This PR adds the ability to get/set a Creeper entity's max fuse ticks.
---
**Target Minecraft Versions:**     "Added after 1.12.2", so I used methodExists()
**Related Issues:**     #1385
=> Creeper Max Fuse Ticks Expression

README.md
In the changelog of the latest stable version of Skript, 2.4.1, it is said that it fully supports 1.15, so the ReadMe should be updated according to it!
---
No code changes
=> Update Minecraft's versions that Skript supports in the README

src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/main/java/ch/njol/skript/effects/EffDrop.java
The drop item effect throws a massive error when attempting to drop a material which cannot be an item. 
Bukkit 1.12 added a method Material#isItem, to keep compatibility with 1.9+ I added an ItemUtils method to be able to handle this new method.
---
**Related Issues:**  #2812
=> Fix drop item effect throwing error

src/main/java/ch/njol/skript/conditions/CondIsCharged.java, src/main/java/ch/njol/skript/effects/EffChargeCreeper.java, src/test/skript/tests/syntaxes/effects/EffChargeCreeper.sk
This PR adds an effect which allows the user to charge or uncharge a creeper. There is also a condition to check whether or not a creeper is charged.
---
=> Charge Creeper Effect and Condition

src/main/java/ch/njol/skript/aliases/ItemData.java, src/main/java/ch/njol/skript/aliases/ItemType.java
I fixed a few quirks with item comparisons that caused scripts to remove wrong items in some cases. 
* Missing item meta values (e.g. names) of items in inventories are no longer ignored
* Previously, removing a named item would also remove unnamed items
* Instead, removing an unnamed item will (as intended) remove those that do have names
* Items in inventories that fail meta checks are no longer promoted as successful matches
* Promotion used to be done for items without any meta
* Lack of meta in items is significant, so this was not safe
* Promotion is still done for aliases that do not have any tags
Please test this PR for regressions before approving. There might be nasty regressions that I didn't think of.
---
**Target Minecraft Versions:** any, but won't solve comparison issues …
=> Fix some item comparison issues

src/test/skript/environments/main/paper-1.15.2.json
This PR is to remove the vanilla Minecraft GUI console from the Skript test system, which pops up when you run a server on 1.15.2
I was running tests in the background, the GUI popped up and startled me 🤓 
---
**Target Minecraft Versions:** 1.15.2
=> SkriptTests - remove vanilla Minecraft GUI console

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
This PR fixes some misplaced patterns for some classes.
In some classes the patterns were put in the description section rather than the usage section.
This brings some continuity between the classes
---
=> BukkitClasses - fix some misplaced patterns for some classes

src/main/java/ch/njol/skript/util/VisualEffect.java, src/main/resources/lang/english.lang, src/test/skript/tests/syntaxes/effects/EffSpawn.sk
This PR adds missing cat types to the lang file.
Until this point you could only spawn a cat, but not by type, this fixes that. 
Please ignore the other commits here. I originally planned on doing a bigger PR that fixes a bunch of issues, but decided to split it up.
---
**Target Minecraft Versions:** 1.14+ (when cats were introduced)
=> Fix missing cat types in the lang file

src/main/java/ch/njol/skript/util/VisualEffect.java, src/main/resources/lang/english.lang
This PR fixes a typo in the VisualEffect class, as well as adds in some missing spawn reasons in the lang file.
---
**Related Issues:**  none
=> Fix lang file

.github/workflows/gradle.yml
There have been a few issues with actions failing. I did some research and saw a few other repos having this issue. Looking thru commits/PRs it appears the fix was to change the checkout v1 to v2
---
**Target Minecraft Versions:** n/a
=> Fix an issue with actions failing on some PRs

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This PR fixes an issue with the item damage event missing an event-item value
---
**Related Issues:** #2895
=> BukkitEventValues - add PlayerItemDamageEvent item value

src/main/java/ch/njol/skript/expressions/ExprHotbarButton.java, src/main/java/ch/njol/skript/expressions/ExprPlayerlistHeaderFooter.java
Fix an issue with the docs of 2 expressions joining (affected hotbar button)
(also fixed a small typo in the player list expression)
**BEFORE**:
**AFTER**:
---
**Target Minecraft Versions:**any
=> ExprHotbarButton - fix doc issue

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/SimpleEvents.java
This PR adds an event-value (event-entity) for the lightning strike event.
I also updated the docs for the lightning strike event to show this in action
---
**Related Issues:** #2863
=> Add missing lightning entity for lightning strike event

src/main/java/ch/njol/skript/util/Date.java
This PR aims to expand the date a little bit to add some ease of use.
- Add return for plus/minus methods for creating a new instance of the date with the added/subtracted time.
- As suggested by Pikachu, added a Date#now() method, returning a new date at the current time.
- Add some javadoc notes. IntelliJ has some really interesting popups which show java docs on classes/methods you hover over. By adding better java doc notes to some of these methods, end users can easily see what these methods do and are meant for.
I noticed the need for this in #2907 
https://github.com/SkriptLang/Skript/pull/2907/files#r403780753
---
=> Date - expand API for ease of use

src/main/java/ch/njol/skript/lang/ExpressionList.java
This PR removes the assertion that the length of an ExpressionList is greater than one.
In my PersistentData PR, I need to be able to use an ExpressionList with just one value. While it works fine in-game, the test does not work. This change shouldn't break anything.
---
**Target Minecraft Versions:**     N/A
**Requirements:**     N/A
**Related Issues:**     #2837
=> Change Assertion in ExpressionList

build.gradle
So it appears the nexus repo has gone down, which is causing builds to fail with PreciousStones.
For funsies, I took it out just to see what would happened, and the build started working. Goes to show this repo is not needed.
This PR is to fix said issue, so builds will start to build again.
Open for discussion :)
---
=> Fix issue with Nexus repo + PreciousStones

src/main/java/ch/njol/skript/SkriptCommand.java, src/main/resources/lang/english.lang
This PR adds server version, skript version and installed addons to the `/skript info` command.
Quite often when people request help, they give us very little info. We may say to them "Which version is your server and/or Skript?" ... they reply "latest", same with addons. 
By adding this additional info, a user can quickly see the details of their server, skript and which addons they currently have installed.
---
**Target Minecraft Versions:**  any
**Related Issues:**  #2970
=> InfoCommand - add server version, skript version and installed addons

src/main/java/ch/njol/skript/expressions/ExprFinalDamage.java
It was recently brought to my attention that `final damage` was not returning correctly. 
This fixes that issue.
---
**Related Issues:**  none that I can find
=> ExprFinalDamage - Fix returning getDamage instead of getFinalDamage

src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
So one issue is settings blocks will always default to Bukkit's default block data. 
The issue here is blocks such as fences, it will set a single fence post, and will not connect to blocks next to it. The reason this happens is because Skript sets the default block data.
This PR fixes it by not setting block data if no block data is determined (ie: using an aliases with no option block data properties)
If an alias which is not default is used, then the Block data of said alias will be applied to the set block.
---
**Target Minecraft Versions:**  1.13+
**Related Issues:**  #2292
=> Fix default block data applying to all placed blocks

build.gradle, src/main/java/ch/njol/skript/bukkitutil/UnresolvedOfflinePlayer.java, src/main/java/ch/njol/skript/entity/DroppedItemData.java, src/main/java/ch/njol/skript/expressions/ExprItem.java, src/main/java/ch/njol/skript/util/BlockStateBlock.java, src/main/java/ch/njol/skript/util/DelayedChangeBlock.java, src/main/java/ch/njol/skript/util/slot/DroppedItemSlot.java
This PR prepares Skript for 1.16
There were some changes to the Bukkit/Paper APIs in 1.16, and we had to implement a few new things. 
Also some changes to some Nullable/NonNull parameters.
I did my best to implement everything, but my main goal was just to get this to build against the 1.16.1 API.
I would appreciate some feedback on this. How to clean it up, how to make things better. I'm all ears!
---
**Target Minecraft Versions:** (target is to build on 1.16, but work on all versions)
=> Prepare for 1.16.x

src/main/java/ch/njol/skript/expressions/ExprName.java
This PR rewrites ExprName. While the solution to the related issues (probably) *isn't ideal*, I would say that in this case, it's better to have something than nothing. I found that overall performance increased, especially in the first few iterations (although I don't know how accurate an in-game benchmark is haha).
---
**Related Issues:**     #3103 #2069 (kind of)
=> Rewrite ExprName

docs/text.html, src/main/java/ch/njol/skript/effects/EffActionBar.java, src/main/java/ch/njol/skript/util/Utils.java, src/main/java/ch/njol/skript/util/chat/BungeeConverter.java, src/main/java/ch/njol/skript/util/chat/ChatMessages.java, src/main/java/ch/njol/skript/util/chat/MessageComponent.java, src/main/java/ch/njol/skript/util/chat/SkriptChatCode.java, src/main/resources/lang/english.lang
This is a remake of #3078, which I had to close because the conflicts had gotten too complicated for me to fix.
This PR adds hex color support to Skript through a new "color" tag. I have updated the documentation appropriately. Unlike #3078, the tag *should* work everywhere now. I had to make some changes to EffActionBar for colors to work properly there.
This is kind of outside of this PR, but Skript doesn't allow you to do:
`
send title "<RED>Hello %player%!"
`
"RED" must be in lowercase. I'm not sure if this is intentional or not though.
The cause is: https://github.com/SkriptLang/Skript/blob/558e9c64a5024781427c36aa12d808b2cce8ea22/src/main/java/ch/njol/skript/util/Utils.java#L526 in that the string isn't converted to lowercase ("RED" doesn't exist in the map, but "red" does).
--- …
=> Add Hex Color Support

src/main/java/ch/njol/skript/entity/VillagerData.java
This PR fixes an issue with "last spawned entity" not being set, due to an issue with villager data.
---
**Target Minecraft Versions:**  1.10-1.13.2
**Related Issues:** #3063
=> Fix villager data for legacy versions

src/main/java/ch/njol/skript/lang/VariableString.java
I tracked down this issue down to this section of `VariableString`, where a plain text component is returned.
I'm pretty sure this is safe to do, so it shouldn't cause any issues. I figured grabbing the hex, updating the color, and removing it from the text would be the most efficient way to do this (instead of calling `ChatMessages#parse`).
While `Utils#parseHexColor` may return a null `ChatColor`, I don't think this code will ever run if the hex color is invalid, as `text` won't contain `§x`.
---
**Target Minecraft Versions:** 1.16+
**Related Issues:** #3213
=> Fix incorrect parsing

src/main/java/ch/njol/skript/conditions/CondCompare.java, src/test/skript/tests/regressions/3111-cond compare is between.sk
This fixes #3111 by adding an additional check that **switches** `o2` and `o3` in **Relation** check.
There may be a better way to do this, but I think this is it?
I will probably make some changes to avoid doing that null check multiple times.
---
**Target Minecraft Versions:** None
**Related Issues:** #3111
=> CondCompare: Is Between Fixes

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
This pull request fixes the `experience` class info having no user.
I tested the changes, and everything works.
---
**Requirements:** N/A 
**Related Issues:** #3265
=> Fix no user in experience class info

src/main/java/ch/njol/skript/expressions/ExprBlockData.java
When I created this expression, I type the wrong link (I think I copied it from another expression, which I guess that one was wrong)
---
=> ExprBlockData - fix link for types (classes)

src/main/java/ch/njol/skript/hooks/economy/expressions/ExprBalance.java
This PR aims to add support for offline player balances. Oddly enough this class pretty much already supported it, just the pattern itself didn't.
---
=> ExprBalance - add support for offline player balances

src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
This PR aims to fix an issue with ExprInventoryInfo returning a single value for viewers.
I changed this from a PropertyExpression -> SimpleExpression.
While in there I cleaned up the code a bit, I also added an option for amount of slots.
I also fixed an issue where `rows of inventory of a hopper` would return 0 (due to getSize() / 9)
---
**Related Issues:** #3321
=> ExprInventoryInfo - fix viewers returning a single value

src/main/java/ch/njol/skript/conditions/CondIsBlockRedstonePowered.java
This Pull Request brings the addition of the "indirectly redstone powered" condition.
I directly added this to the existing condition. If you think it was a bad idea and that another condition should have been made, let me know!
---
**Related Issues:** #3294
=> Adding "indirectly redstone powered" condition

src/main/java/ch/njol/skript/effects/EffVisualEffect.java, src/main/java/ch/njol/skript/util/VisualEffect.java, src/main/resources/lang/english.lang
This PR aims to fix issues with coloured particles. 
Im not sure why but a lot of the code in the VisualEffect was written in a really odd way, possibly for a really old version of Bukkit API. It appears the offset was being set using the colors' RGB codes?!?! So confusing.
I've spent hours re-writing and testing this. It seems to fix the issues pertaining to colors, as well as some other issues with count, speed and offset.
In VisualEffect I added a subclass ParticleOption. It includes size, which can be used for Redstone dust particles. I tried making size stuff work but I kept failing, so I left the size stuff out for now. Im leaving this class here as it may be useful in the future, and I will attempt to do size stuff again.
---
**Requirements:** …
=> Fix visual effect issues

src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
This PR aims to fix an issue with the Inventory (holder|owner) expression clashing with the entity (owner|tamer) expression.
---
**Related Issues:** #3344
=> ExprInventoryInfo - remove "owner" to fix a clash with "entity owner"

src/main/java/ch/njol/skript/expressions/ExprNamed.java, src/test/skript/tests/regressions/3305-named inventory-item.sk
This PR aims to fix an issue with named items throwing errors that they're not ItemTypes. 
This was caused by a previous issue I fixed, when in turn, broke something else.
---
**Related Issues:** #3347
=> ExprNamed - fix issue with named items failing

src/main/resources/plugin.yml
This PR aims to fix an issue with the soft depends in the plugin.yml.
When the plugin loads I saw this warning:
```
[12:27:44 WARN]: [Skript] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 
which is not a depend, softdepend or loadbefore of this plugin.
```
Well, clearly Vault is a soft depend, then I realized it should be `softdepend` not `soft-depend`
---
=> plugin.yml - fix soft-depend -> softdepend

src/main/java/ch/njol/skript/aliases/AliasesProvider.java, src/main/java/ch/njol/skript/aliases/ItemData.java, src/main/java/ch/njol/skript/aliases/MaterialRegistry.java
Adds a SpawnEggMeta comparison check on 1.12
EDIT: small fixed needed
---
**Target Minecraft Versions:** 1.12
**Related Issues:** #3167
=> Fix spawn eggs for 1.12

src/main/java/ch/njol/skript/events/SimpleEvents.java
This simple PR adds an event called when a player swings his arm.
It does not provide a comparison of the type of animation, as there is only one type (`ARM_SWING`).
---
**Related Issues:** #3114
=> Add arm swing event

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/EvtItem.java
This PR aims to resolve an issue with the ItemMergeEvent, allow the user to grab the target entity (the entity in which the item is merging into)
I set it up as a future event-entity and it works quite well ... yay!
---
=> BukkitEventValues - add event-value for target in ItemMergeEvent

src/main/java/ch/njol/skript/expressions/ExprNumbers.java
Completely revamped decimals between's iterator to fix an issue, also made some changes to fix rounding errors and always choose the first number's decimal precision (regardless of which is larger).
---
**Related Issues:** #3494
=> ExprNumbers bugfixes and decimal iterator revamp

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/lang/ExpressionInfo.java, src/main/java/ch/njol/skript/lang/SyntaxElementInfo.java, src/main/java/ch/njol/skript/lang/function/Parameter.java, src/main/java/ch/njol/skript/localization/Language.java, src/main/java/ch/njol/skript/registrations/EventValues.java
This PR introduces some changes that will allow documentation extraction tools like ResourceSync(skUnity), [SkriptHubDocsTool](https://github.com/SkriptHub/SkriptHubDocsTool) (Skript Hub) and [DocExtractionTool](https://github.com/SkriptInsight/DocExtractionTool)(SkriptInsight) to have a more consistent API for extracting information. They, and new others will benefit from these changes.
Some of the changes include the following:
- Store and expose Skript Expression types (The expression order is different depending on the expression's type)
- Expose Syntax Element information with getters
- Expose Event Value information with getters
- Expose Language information with getters
- Expose Function Parameter information with getters
When tools need to fetch information from Skript, they have …
=> Improve public syntax information API 

src/main/java/ch/njol/skript/expressions/ExprBlockData.java
This PR aims to add `set` to the block data expression. I honestly have no clue why I didn't add this in the first place. While yes the player can just set the block to block data, this expression is a little more defined.
---
=> ExprBlockData - add support to set blockdata of blocks

src/main/java/ch/njol/skript/expressions/ExprSubstring.java
This PR aims to fix an issue with ExprSubstring throwing an error
---
**Related Issues:** #3585
=> ExprSubstring - fix an error with `start` being null

src/main/java/ch/njol/skript/expressions/ExprOffTool.java
This PR aims to fix an issue with getting the offhand tool in a bucket event. It is returning the main hand, when it should be returning the offhand.
---
**Related Issues:** #3584
=> ExprOffTool - fix an issue with bucket event and offhand actually returning main hand

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This fixes the CCE thrown by using event-location in EvtSpawn.
It seemed to be a result of the event change in #3427.
I had no issues during testing. I also made sure ExprSpawnReason was still working right, since the event changed, and I had no issues with it. It just returns null if it is a non-living entity
---
**Related Issues:** #3622
=> Fix EvtEntity event-location

src/main/java/ch/njol/skript/effects/EffTeleport.java
This saves and then re-sets local variables after the teleportation. I think I did everything right (I haven't actually worked with async effects before), but if there is anything else I should change reviews are very appreciated. This seemed to fix the issue when I tested it.
---
**Target Minecraft Versions:** All
**Related Issues:** #3605
=> Re-set local variables after async teleporation

src/main/java/ch/njol/skript/util/AABB.java
This PR aims to fix an issue with the `blocks within` expression, where the bounding box is smaller than expected.
This was due to the AABB class shrinking when it shouldn't be
---
**Related Issues:** #3615
=> BlocksWithin - fix issue with bound being smaller than expected

src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
This PR aims to use a fallback world when a world is missing from the location function.
This does not fix the issue with getting event-world, it just gets the main world if the world is missing for whatever reason.
- Also added a few more examples since people find this hard to understand
---
**Related Issues:** #3597, #3455, #1465
=> DefaultFunctions - use a fallback world when a world is missing in location function

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/SimpleEvents.java
This PR adds the EntityPortalEvent, along with support for getting the entity in a portal creation event (on supported versions).
I could add the [EntityCreatePortalEvent ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityCreatePortalEvent.html) for event-entity support on older versions, but I'm not sure if that's really necessary.
---
**Target Minecraft Versions:** All
**Requirements:** 1.14+ (for event-entity in portal creation event)
**Related Issues:** #3546
=> Enhance Portal Events

src/main/java/ch/njol/skript/expressions/ExprItemWithLore.java, src/test/skript/tests/syntaxes/expressions/ExprItemWithLore.sk
Apply new line (`%nr%`) in item lore. It seems that #2505 forgot this.
e.g.
`1 of stone with lore "first line%nl%second line"`
[The test case](https://github.com/SkriptLang/Skript/pull/3636/files#diff-840322c377d70914e2d9a5072c844f83cbf7155c5ba9b3caaa60ee37d3b4cf5a) describes the behavior well.
---
**Related Issues:** #3544.
=> Apply new line (`%nr%`) in item lore correctly

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This PR aims to add event-sender to server/script load/unload events allow for the use of the message effect without requiring to use `to console`
---
=> BukkitEventValues - add support for command sender (console) in server/script load/unload events

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This PR aims to add support for retrieving recipe strings in craft events.
This is available in 1.12.2+ (or 1.12 - I'm not sure which revision, whenever NamespacedKeys were added)
---
**Target Minecraft Versions:** 1.12+
=> BukkitEventValues - add support for recipe keys in craft events

src/main/java/ch/njol/skript/localization/Noun.java
Fixes reversed arguments in Noun's static toString method.
Found automatically by SonarLint. Not sure if it breaks anything, test respectively before merging.
---
=> Fix reversed arguments in Noun toString method

src/main/java/ch/njol/skript/lang/SkriptParser.java
Fix the parsing of expressions with strings on both ends.
Test script:
```
on load:
set {_test::*} to "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday" split at ","
set {_d} to "hi" if 1 = 1 else "d"
```
If I should add a regression test for this, tell me. I didn't think it was necessary, as the only way I see this exact thing breaking again is by someone reverting the commit.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/719, https://github.com/SkriptLang/Skript/issues/3490
=> Fix parsing with strings on both ends of expression

src/main/resources/scripts/item command.sk
IDs were removed on 1.13+, replace it with type instead. Fixes these errors:
```
[22:01:32 ERROR]: [Skript] Items do not have numeric ids on Minecraft 1.13 or newer. (item command.sk, line 47: if player has permission "skript.give.%ID of loop-item%":')
[22:01:33 ERROR]: [Skript] Items do not have numeric ids on Minecraft 1.13 or newer. (item command.sk, line 60: if player has permission "skript.give.%ID of loop-item%":')
[22:01:33 ERROR]: [Skript] 'else' has to be placed just after an 'if' or 'else if' section (item command.sk, line 63: else:')
```
Note that this not perfect, i.e cobblestone would require skript.give.cobblestone block permission instead of just cobblestone.
So I added the required permission too to the no permission message. If there is a better alternative to type of …
=> Fix example script errors

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/SkriptEventHandler.java, src/main/java/ch/njol/skript/command/Commands.java
The ServerCommandEvent was made Cancellable somewhere between 1.8 and 1.8.8 but not respected on Skript
Since EffCancelEvent checks for Cancellable as interface, it worked, but some other places on Skript checked manually that if ServerCommandEvent is cancelled by determining if the command is empty or not.
Related Spigot commit:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/c31fcfe3a19c4ee597df75e750af1542ac020b92
---
=> Handle cancellation of ServerCommandEvent properly

src/main/java/ch/njol/skript/conditions/CondCompare.java
Adds `lower than` as an alternative to `less than` or `smaller than` in CondCompare.
I was trying to use lower than and confused when it wasn't working (because greater than works.) when I was first started on Skript, so this why I'm making this PR; it just come to my mind and decided to make a PR for it.
---
=> Add lower than to CondCompare

src/main/java/ch/njol/skript/ScriptLoader.java
Skript displays the wrong amount of commands (and functions, if that was displayed) when reloading all scripts (or when reloading a specific script with log verbosity 'high'). Example:
```
command [[[[[[:
trigger:
stop
command [[[[[[:
trigger:
stop
command [[[[[[:
trigger:
stop
command [[[[[[:
trigger:
stop
command [[[[[[:
trigger:
stop
```
---
**Requirements:** nony
=> Show right amount of loaded commands after reload

src/main/java/ch/njol/skript/expressions/ExprRawName.java
This PR aims to fix an NPE error when using this expression in a string, ie:
```vb
send "%minecraft name of player's tool%"
```
should return
```
[02:49:08 WARN]: [Skript] minecraft name of the tool of the player is already a text, so you should not put it in one (e.g. minecraft name of the tool of the player instead of "%minecraft name of the tool of the player%") (test.sk, line 6: send "%minecraft name of player's tool%"')
```
but instead its throwing an error.
---
=> ExprRawName - fix an error from the toString method

src/main/java/ch/njol/skript/effects/EffTeleport.java
Teleporting a player in a move event causes a StackOverFlowError since teleportation trigger move event too, and this repeats. The correct way is to use PlayerMoveEvent#setTo instead.
While Skript does not provide a PlayerMoveEvent by default, some add-ons do. This fixes the teleport effect's behaviour on move events.
---
**Related Issues:** can't remember but I saw one long time ago
=> Fix stackoverflow error with teleport effect

src/main/java/ch/njol/skript/PatcherTool.java
This PR aims to fix an issue when attempting to build Skript on Gradle 6
Edit: According to my gradle thing, I wasn't actually using gradle 6. But using the gradle buttons in IntelliJ, I was forced to change this class for it to build. Regardless, this will help in the future when we update to Gradle 6. 
---
=> PatcherTool - fix issue when building on Gradle 6

src/main/java/ch/njol/skript/util/AABB.java
This PR aims to fix an issue with the blocks in region expression, returning blocks 1 outside of the region.
In a previous change to AABB I broke it, and when I fixed it, I didn't fix the constructor that is used by WG.
This fixes that issue... 3rd times a charm.
---
**Related Issues:** #3707
=> AABB - fix an issue with blocks in WG regions also looping blocks 1 outside the region

src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
When setting a block to a bisected block (such as a door or bed), it will alternate the bisection.
ie: set a block to a door, it sets correctly. Repeat that task, and it will set at the block below. This is caused by Skript changing the ItemType's ItemData to the opposing bisection, causing blocks to alternate. 
By cloning the original data, we don't have to change it.
---
**Related Issues:** #2473
=> NewBlockCompat - fix issue with bisected blocks alternatively placing

src/main/java/ch/njol/skript/events/SimpleEvents.java
.. as an alternative to quit, disconnect and logout.
Will handle leave, leaving and their variants with "on" prefix. (ScriptLoader adds that, no need to specify here)
Not sure if tests are required for a change like this; not familiar with the testing system but can add one that ensures on quit, on disconnect, on logout and on leave parses successfully (if that is possible).
---
**Related Issues:** #3789
=> Add on leave to quit event (#3789)

src/main/java/ch/njol/skript/Skript.java
Fixes this error:
```
[22:02:47 WARN]: java.lang.NoSuchFieldException: modifiers
[22:02:47 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2569)
[22:02:47 WARN]:        at ch.njol.skript.Skript$4.run(Skript.java:1056)
[22:02:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
```
The Field#modifiers field was removed on Java 12.
The eror happens on Java 12+ only and the stacktrace is only printed when Skript#testing returns true (i.e -ea/-enableassertions), but it should be fixed anyway.
By "fix", it just ignores the error. The behaviour is not same as on Java < 12. Can't find a better alternative rn, but probably there is.
Not tested on Java 11 but it would give a illegal access warning with or without this fix anyway. Perhaps unsetting static final …
=> Fix Java 12 compatibility

src/main/java/ch/njol/skript/expressions/ExprDifference.java, src/test/skript/tests/regressions/661-skript parse error.sk
Fix issues with `ExprDifference`.
Test script used: https://pastebin.com/BhZKtvMr
---
**Related Issues:** #661, #575, #994, #1001, #2302
=> Fix ExprDifference

build.gradle
Adds an automatic module name, that is, used as module name when Skript is on the modulepath on Java 9+.
If the jar is not modular (does not contain module-info.class) and does not have a `Automatic-Module-Name` entry on META-INF/MANIFEST.MF, then the module name is determined by file name.
Publishing non modular artifacts (not containing module-info.class) that also doesn't contain `Automatic-Module-Name` to any repository and using them as libraries on projects is discouraged, and will most likely cause a warning to be thrown.
The filename based module name is normally `Skript` on releases published in GitHub Releases, but people can alter them and name it whatever they want.
Adding an `Automatic-Module-Name` _will_ break the current _modular_ projects that requiring Skript via its …
=> Add automatic module name

src/main/java/ch/njol/skript/expressions/ExprDefaultValue.java, src/main/java/ch/njol/skript/expressions/ExprFilter.java, src/main/java/ch/njol/skript/expressions/ExprMetadata.java, src/main/java/ch/njol/skript/expressions/ExprRelationalVariable.java, src/main/java/ch/njol/skript/expressions/ExprTernary.java
The expressions in the title were converting incorrectly, because they were only storing the supertype of the given classes to convert to, instead of the classes themselves. If the classes were, for example, ItemStack and ItemType, the stored supertype would be Object, which would match any returned object, e.g. InventorySlot, even if that class doesn't match the given types.
---
**Related Issues:** #3905
=> Fix default value, filter input, metadata, relational variable, ternary incorrectly converting

.gitignore
Adds the `test_runners` directory (from Skript's testing system) to .gitignore.
---
=> Add test_runners to .gitignore

skript-worldguard6/src/main/java/ch/njol/skript/module/worldguard6/WorldGuard6Hook.java, src/main/java/ch/njol/skript/hooks/regions/GriefPreventionHook.java, src/main/java/ch/njol/skript/util/AABB.java
Changed AABB and classes using it, to not make certain regions extended by 1 block. From some of the constructors in AABB you get the impression upperBound is exclusive (because some constructors add 1 to each vector component), but the implementation indicates is actually inclusive, so these aren't needed. I've also changed the calls to [`World#getMaxHeight()`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#getMaxHeight()), because that always returns the 1 above the highest possibly y coord where a block can be found (e.g. 256 instead of 255).
---
=> Fix blocks in chunk returning too much

src/main/java/ch/njol/skript/Skript.java
The order of the `Skript#expressions` field was partially reversed:
https://pastebin.com/auvMwfnc: `Registered` is the order it was registered, `Detected` is the order of the list after registration. Note that the order of registration shouldn't exactly match the order of the list, as expression with the same `ExpressionType` should be grouped together. Also note that `ExprDamageCause` is registered earlier due to [BukkitClasses#L1302](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/BukkitClasses.java#L1302).
This is the new result: https://pastebin.com/b41zBNrV
---
=> Fix expression parse order

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/util/BlockUtils.java
This PR aims to reformat a block's toString() method, to include more info.
See #3315 for the discussion.
I know it was up in the air whether or not a world should be included, and its potential to be too verbose, I included it, as users may have block stored in variables, and this just prints a more accurate accounting of the block.
Ex code:
```vb
on load:
set {_b} to block at location(-910, 12, -234, world "world")
send "Block: %{_b}%" to console
```
Output:
```
Block: 'raw andesite' at -909.5, 12.5, -233.5 in world 'world'
```
---
**Related Issues:** #3315
=> BukkitClasses - reformat Block's toString to include more helpful info

src/main/java/ch/njol/skript/effects/EffBroadcast.java, src/main/java/ch/njol/skript/effects/EffMessage.java, src/main/java/ch/njol/skript/lang/VariableString.java
Makes `EffMessage` and `EffBroadcast` accept objects to broadcast, instead of just strings. 
Also makes it so the effects don't call any of the expressions getters multiple times (which is what the ugly code at the start of the second loop in `EffMessage#execute` is for):
```
function doStuff() :: text:
broadcast "func called"
return "test"
command /test:
trigger:
add sender to {_l::*}
add sender to {_l::*}
send "Result: %doStuff()%" to {_l::*}
```
will now only call `doStuff` once, used to be twice.
---
**Related Issues:** #3164
=> Make message and broadcast effects accept objects

src/main/java/ch/njol/skript/lang/Variable.java
(the change is at L300)
With a list variable like: `{_a::b::c} = 1`, without a value at `{_a::b}`, the expression `{_a::*}` would return an array of size 1 instead of 0.
Test code:
```
command /test:
trigger:
set {_a::b::d} to 1
set {_a::c::d} to 1
message "size: %size of {_a::*}%"
message "values: %{_a::*}%"
```
---
**Related Issues:** #2600
=> Fix list variables returning null

src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/lang/function/ScriptFunction.java
Sets the line number fields of the triggers of functions and commands.
---
**Related Issues:** #2336 (partially)
=> Give line numbers to command and function triggers

src/main/java/ch/njol/skript/effects/EffColorItems.java
It was missing the parameter
---
**Target Minecraft Versions:** Wherever this method exists
**Related Issues:** #3947
=> Fix method check in EffColorItems

src/main/java/ch/njol/skript/expressions/ExprReversedList.java, src/main/java/ch/njol/skript/expressions/ExprShuffledList.java, src/main/java/ch/njol/skript/expressions/ExprSortedList.java
Fixes the return type of some list expressions: `ExprSortedList`, `ExprShuffledList`, `ExprReversedList`.
All 3 loops in this code don't parse without this PR (with error `loop-value is not a text`):
```
command /test:
trigger:
set {_l::*} to 5 times
loop reversed indices of {_l::*}:
set {_i} to (loop-value) parsed as integer
message "%loop-value% ; %{_i}%"
loop shuffled indices of {_l::*}:
set {_i} to (loop-value) parsed as integer
message "%loop-value% ; %{_i}%"
loop sorted indices of {_l::*}:
set {_i} to (loop-value) parsed as integer
message "%loop-value% ; %{_i}%"
```
---
**Related Issues:** #3492
=> Fix return type of some list expressions

src/main/resources/config.sk
This PR aims to change the config option "log player command" default to false
---
**Related Issues:** #3855
=> config - change "log player command" default to false

src/main/java/ch/njol/skript/events/EvtMove.java
This PR introduces the Player move event, along with an entity move event.
In the past it has been discussed to not use these events as they are performance heavy.
Here are a couple reasons I decided to add this:
1) Skript already uses the move event for the "move on" event. So regardless, the performance is going to be hindered by that event.
2) Paper (and I think Spigot too) only calls heavy events like this, if a plugin actually registers an event. 
Skript only registers a listener if a user is using said event. That said, performance will only potentially take a hit to users who use this event. I added cautionary notes in the description of the event to make sure users are clear. This is up to them if they want to use the event or not.
I don't think its in our position to deny users …
=> EvtMove - new player/entity move event

src/main/java/ch/njol/skript/conditions/CondIsPluginEnabled.java
This PR adds a condition to check if a plugin is enabled/disabled.
As of right now there won't be a whole lot of use for this, but its part of a PR I was working on before, where a section of code would only be parsed if a condition passed, see old PR https://github.com/SkriptLang/Skript/pull/3289
While this may not be totally useable yet... I'm sure some people will find some use for this.
---
=> CondIsPluginEnabled - new condition checking if plugins are enabled/disabled

src/main/java/ch/njol/skript/effects/EffDoIf.java
EffDoIf didn't set the parsed effects parent.
---
**Related Issues:** #3983
=> Fix EffDoIf with exit effect

src/main/java/ch/njol/skript/SkriptEventHandler.java
Fixes events not being called when a subclass of the registered event was called instead of the exact event class.
---
**Related Issues:** #3852
=> Fix event listening with subclasses

src/main/java/ch/njol/skript/aliases/Aliases.java, src/main/java/ch/njol/skript/aliases/AliasesProvider.java
This PR aims to create temporary aliases for missing materials. This will help future proof Skript during future Minecraft releases. 
A small example was the release of Minecraft 1.16. When Spigot was released, we had to try to rush a release on Skript to have aliases available to users. The main problem here was these aliases were added to Skript 2.5-alpha versions. 
Users who wish to stay on a stable release (ie: 2.4.1 at the time) would not have access to these new aliases. 
With this change, and the introduction to BlockData recently, Skript users will not have to wait for a Skript update to use the new aliases. 
This gives us more time to write/test new aliases for Skript, without having to worry about pushing out an update right away. 
- I included `¦s` as a temporary plural variant …
=> Aliases - load temp aliases, when aliases are missing

src/main/java/ch/njol/skript/expressions/ExprWorld.java
This PR aims to fix an issue with the world expression, and not able to set a world of a location
I also cleaned up the class a bit, to match the conventions of expression classes
---
**Related Issues:** #2709
=> ExprWorld - fix not being able to set world of location

src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/java/ch/njol/skript/effects/EffChange.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/log/ParseLogHandler.java
Due to a change in #4020, `ParseLogHandler#printLog` now also prints errors. This required some changes in `SkriptParser`, otherwise errors would incorrectly be shown.
I've also removed a lot of commented out code.
---
**Related Issues:** #4020
=> Fix new incorrect ParseLogHandler usage in SkriptParser

src/main/java/ch/njol/skript/effects/EffReplace.java, src/main/java/ch/njol/util/StringUtils.java
Update `EffReplace` and `StringUtils` so it only escapes the replacement string if needed, which is only if the replacement is done with regex, which is only done if case sensitivity is disabled.
---
**Related Issues:** #1226
=> Fix EffReplace escaping characters when not needed

src/main/java/ch/njol/skript/effects/EffContinue.java
Makes EffContinue iterative, instead of recursive.
Test code:
```
command /test:
trigger:
loop 10000 times:
continue
```
---
**Related Issues:** #4096
=> Make EffContinue iterative instead of recursive

src/main/java/ch/njol/skript/sections/SecLoop.java
Makes `SecLoop` check for `UnparsedLiteral`s. This makes sure that Skript doesn't pass random nonsense to the loop.
Test code:
```
command /test:
trigger:
loop awdhawiudhiwad:
stop
```
---
**Related Issues:** #4020
=> Make SecLoop check for UnparsedLiterals

src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
This PR aims to prevent the giant stack traces when a block state is missing after an MC update.
In this example, MC 1.17 changed how cauldrons work, which when running Skript (2.5.3) on MC 1.17, we get this giant stack trace (and nobody wants this)
Example of how it looks after this change:
---
**Target Minecraft Versions:** future MC versions
=> NewBlockCompat - prevent stacktrace when blockstates are missing

src/main/java/ch/njol/skript/events/bukkit/SkriptParseEvent.java, src/main/java/ch/njol/skript/sections/SecConditional.java, src/test/skript/tests/syntaxes/sections/SecConditional.sk
This PR aims to add a `parse if` condition.
The goal of this is stop code from being parsed in a section if the condition is not true.
This can be useful when using different addons with a script, and only wanting to load code if the addon is actually loaded, otherwise this code would throw a bunch of errors on you.
Example code:
```vb
on load:
parse if plugin "SkBee" is enabled:
this fake code SHOULD error
else parse if plugin "SomeFakePlugin" is enabled:
this fake code should NOT error
```
Output:
```
> sk reload test
[14:12:48 INFO]: [Skript] Reloading test.sk...
[14:12:48 ERROR]: Can't understand this condition/effect: this fake code SHOULD error (test.sk, line 6: this fake code SHOULD error')
[14:12:48 INFO]: [Skript] Encountered 1 error while reloading test.sk!
```
Because SkBee is …
=> SecConditional - add `parse if` option

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/skript/tests/regressions/4143-nested-variables-erroring-in-2.6-beta1.sk
Update `SkriptParser#parseVariable` to allow doubly nested variables. Also adds a test for them.
This is how this method saw the input (`.` is text, `^` is expression) before this change:
```
{aaa%{bbb%{ccc}%}%}
....^^^^^^.....^^^.
```
---
**Related Issues:** #4143
=> Fix doubly nested variable parsing

code-conventions.md
Updates code-conventions.md
---
=> Update code conventions to require Java 16 for compiling

src/main/java/ch/njol/skript/sections/SecConditional.java, src/test/skript/tests/syntaxes/sections/SecConditional.sk
Fixes a bug with code such as 
```
command /test:
trigger:
if 1 = 1:
broadcast "true"
exit 1 section # or an inline condition that returns false, such as `1 = 2`
else:
broadcast "false"
```
broadcasting both true and false.
---
=> Fix conditionals with inline conditions or exit section effects

src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Adds magma to the itemtype - damage cause comparator
---
**Related Issues:** #4203
=> Add magma to itemtype damage cause comparator

src/main/java/ch/njol/skript/sections/SecConditional.java
Fixes fallout from #4175: the line `setNext(skippedNext)` was leftover from a previous version of that change, I forgot to remove it before pushing.
---
**Related Issues:** #4212, https://github.com/SkriptLang/Skript/pull/4162#issuecomment-884731972, #4175
=> Fix combined conditional running on non-first runs

skript-worldguard6/build.gradle
Fixes the WorldGuard 6 module by adding this code from the main module's build.gradle:
https://github.com/SkriptLang/Skript/blob/6e7eca0d609fdbc8bbb4b1d3fad484f43a45f612/build.gradle#L14-L16
---
**Related Issues:** #4211
=> Fix WorldGuard 6 module not building to right Java version

src/main/java/ch/njol/skript/aliases/AliasesProvider.java
This PR aims to fix the linked issue by stripping the ending dash slightly earlier (if the string to insert is not null, it will try to strip it basically).
---
**Target Minecraft Versions:** None
**Related Issues:** #4160
=> Fix incorrect ending dash with ExprRawName

src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Skript tried to compare the entity to the rabbit item, so I added rabbit to the EntityData - ItemType comparator
---
**Related Issues:** #4040
=> Fix entity rabbit comparison

src/main/java/ch/njol/skript/expressions/LitConsole.java
Fixes the return type of LitConsole, so Utils#getSuperType functions properly
---
**Related Issues:** #3863
=> Fix CCE due to console literal

src/main/java/ch/njol/skript/expressions/ExprColorOf.java
Suppresses the exception, unless verbosity is set to 'very high', in which case it re-throws it.
---
**Related Issues:** #2931
=> Suppress bed colour setting exception on newer server versions

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/expressions/ExprArrowKnockbackStrength.java, src/main/java/ch/njol/skript/expressions/ExprName.java, src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
Changes the string form of offline players, to use their UUID instead of their name when the name isn't available (hasn't joined server before, offline mode etc).
Also made 2 expressions support offline players.
Also fixed a pattern:
---
**Related Issues:** #2458
=> Offline player stuff

src/main/java/ch/njol/skript/command/Commands.java
Fixes command permission and cooldown message quote parsing
---
**Related Issues:** #1679
=> Fix command permission and cooldown message quote parsing

src/main/java/ch/njol/skript/util/chat/ChatMessages.java
- Fix lenient link parsing not working after color codes
- Fix lenient link parsing not working with http:// and https://
- Made https the default instead of http when parsing a lenient link
---
**Related Issues:** #2283
=> Fix lenient link parsing

src/main/java/ch/njol/skript/effects/EffMessage.java, src/main/java/ch/njol/skript/lang/VariableString.java, src/main/java/ch/njol/skript/util/chat/ChatMessages.java, src/main/java/ch/njol/skript/util/chat/MessageComponent.java
Fixed chat color issues by creating ChatMessage.fromParsedString, which only turns color codes with '§' into MessageComponents.
Also copies over color codes from previous components properly.
```
command /test:
trigger:
set {_x} to "&bCB"
message "&aABC %{_x}% AAA"
message formatted "&aABC %{_x}% AAA"
message colored "&aABC %{_x}% AAA"
message "&aABC %{_x}% &eAAA"
message "<##00ff00>A"
message colored "<##00ff00>A"
set {_value} to "<##00ff00>A"
message {_value}
message formatted {_value}
message colored {_value}
message uncolored {_value}
```
---
**Related Issues:** #2319, #4276
=> Fix chat color stuff with expressions

src/main/java/ch/njol/skript/expressions/ExprXOf.java, src/test/skript/tests/syntaxes/expressions/ExprXOf.sk
In #4261, I removed the getConvertedExpression method from ExprXOf, but this turned out to be a bad change, as seen in #4296. This PR adds back the method, buts limits the classes argument to only the types that ExprXOf can accept. 
I also added a test.
---
**Related Issues:** #4296, #4261
=> Fix ExprXOf converting

src/main/java/ch/njol/skript/effects/EffDrop.java
Fixes dropping items in a cancelled death event (cancellation is only available on Paper). The code removed was supposed to make item dropping in a death event add it to the event's drops, but this can (and IMO should) be done using the [drops](https://skriptlang.github.io/Skript/expressions.html#ExprDrops) or [experience](https://skriptlang.github.io/Skript/expressions.html#ExprExperience) expression. 
I could've added a condition to make sure the event isn't cancelled, but that would not prevent the bug from happening when the event is cancelled *after* the drop effect is called.
I also cleaned up the file and merged the two patterns, using a parse mark.
---
**Related Issues:** #4288
=> Fix dropping in cancelled death event

src/main/java/ch/njol/skript/events/EvtExperienceSpawn.java, src/main/java/ch/njol/skript/events/bukkit/ExperienceSpawnEvent.java
This PR aims to fix `<none>` values being returned for the experience spawn event, along with the event firing in cases where there would never be EXP spawning (for example, it fired for ALL cases/states of the fish event). I cleaned up `EvtExperienceSpawn` and `ExperienceSpawnEvent`
---
- #2915 (fixes)
- #3661 (Not sure if this technically fixes, but these events are also called at the same time so this could just be an unavoidable inconsistency. Applying an event priority to the fish event may be the workaround for the user)
=> Improve Experience Event

src/main/java/ch/njol/skript/variables/FlatFileStorage.java
Fixes FlatFileStorage not writing to the right temporary file, always using `variables.csv.temp` instead of `<file>.temp`
---
**Related Issues:** #4398
=> Fix CSV storage not using the right temporary file

src/main/java/ch/njol/skript/sections/SecLoop.java
SecLoop allowed looping single values which caused issues with non-list variables: 
```
loop {_a}:
```
The above code caused a SkriptAPIException.
---
=> Fix looping single values

.github/workflows/gradle.yml, src/main/java/ch/njol/skript/util/BlockStateBlock.java, src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Updates Skript's classes that implement Block.
Also updates the workflow, as https://github.com/textbook/git-checkout-submodule-action has been archived, so now it uses actions/checkout with the submodules: recursive option
---
=> Fix Gradle building

src/main/java/ch/njol/skript/hooks/regions/classes/Region.java
This PR aims to fix a long annoying behavior in skript when using an unknown region name it would give another error message.
Before this PR:
After this PR:
---
**Related Issues:**  #2737 (non-fixing but related because the error message wasn't correct)
=> 🚀 Add region `not found` error

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This PR aims to add missing event-values for the EntityPickupItemEvent, as well as adds event-entity for PlayerPickupItemEvent as event-entity currently returns the dropped item entity that was picked up (which event-item also does)
---
=> BukkitEventValues - fix missing event-values for pickup events

src/main/java/ch/njol/skript/patterns/LiteralPatternElement.java
Issue was caused by pattern compiling PR. A string with the character `İ` converted to lower case using String#toLowerCase will have that part replaced by two characters instead of one, which the implementing code had expected. This didn't occur before, because the old implementation used Character#toLowerCase to compare characters, which is also the change this PR implements.
---
**Related Issues:** #4465
=> Fix parsing with İ

src/main/java/ch/njol/skript/expressions/ExprAttackCooldown.java
This PR adds a new expression to get the attack cooldown of players, currently this can not be set due to spigot's implementations.
---
**Target Minecraft Versions:** 1.15+
**Requirements:** MC 1.15+
**Related Issues:**  #4105
=> 🚀 Add ExprAttackCooldown of players

src/main/resources/lang/default.lang
Fix a mistake with the lang file I made on GitHub
---
=> default.lang - fix indentation of biomes

src/main/java/ch/njol/skript/lang/EffectSection.java, src/main/java/ch/njol/skript/lang/Section.java
Pretty much the same issue as https://github.com/SkriptLang/Skript/pull/4353, this time fixed properly. 
The previous PR assumed the only place the SectionContext data could be modified was during the init section of a Section, but it could also be done while parsing (effect)sections, before init is even called.
In the case of the issue linked by parsing of an expression, which lead to the parsing of an effect (because of SkQuery's lambda literals), which led to EffectSection parsing, which modified the SectionContext data.
This time, the issue has been fixed at the source: the modification of the SectionContext data itself.
---
**Related Issues:** #4473
=> Fix Section parsing NPE v2

src/main/java/ch/njol/skript/lang/SkriptParser.java
Fixes function call parsing with a string argument containing a closing bracket without first an open bracket. Introduced in #3862, the fix there did not account for strings. The current solution does by using `SkriptParser#next`
---
**Related Issues:** #4487, #3862 (latter non-fixing)
=> Fix function parsing with brackets in strings

README.md
jCenter has been since shutdown. No need to have it in the example.
=> Remove jCenter() example

src/main/java/ch/njol/skript/expressions/ExprLanguage.java
Fixes legacy method being invoked with no parameters in ExprLanguage.
---
**Target Minecraft Versions:** 1.9-1.11
=> Fix legacy method invocation in ExprLanguage

src/main/java/ch/njol/skript/patterns/PatternCompiler.java
This change makes it so any exception caught while compiling a pattern is rethrown with more information about the pattern.
For example, I malformed the pattern of EffMessage.
Before PR:
https://pastebin.com/dzp0Q1Mh
```
ch.njol.skript.SkriptAPIException: No class info found for objectst
```
After PR:
https://pastebin.com/aZZHG6Kc
```
java.lang.RuntimeException: pattern compiling exception, element class: ch.njol.skript.effects.EffMessage
Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: (message|send [message[s]]) %objectst% [to %commandsenders%] [from %-player%]]
Caused by: ch.njol.skript.SkriptAPIException: No class info found for objectst
```
--- …
=> Improve exception throwing of PatternCompiler

src/main/java/ch/njol/skript/util/Utils.java
With the latest update, Hex colors couldnt be used within containers like variables, or functions. 
Idk why tho. But this fixes it 🎉 
---
**Target Minecraft Versions:** 1.16+
**Requirements:** Skript
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4527
=> Hex Color Fix

src/main/java/ch/njol/skript/lang/Effect.java, src/main/java/ch/njol/skript/lang/Statement.java
Fix two incorrect log handler usages in Statement#parse and Effect#parse, due to EffectSection parsing.
---
=> Fix EffectSection parsing unrelated errors

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/variables/Variables.java
Before PR:
This line in the config is unrelated, and it doesn't need to be displayed with the warning.
After PR:
---
=> Fix 'no scripts found' warning displaying with a config line

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/suggestion.yml
This PR makes a few changes to the issue templates.
- Forces the Skript Info field to render in mardown (sometimes people mess up the backticks and the whole template is messed up)
- Turns Errors/Screenshots section into a normal text area. Rewords recommendation of using a paste website.
- Minor wording changes
If anyone has any other changes they would like to see implemented, feel free to suggest them.
---
=> Update issue templates

.github/workflows/gradle.yml, .github/workflows/repo.yml, build.gradle, src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/tests/platform/Environment.java, src/test/skript/environments/extra/paper-1.10.2.json, src/test/skript/environments/extra/paper-1.11.2.json, src/test/skript/environments/extra/paper-1.13.2.json, src/test/skript/environments/extra/paper-1.16.5.json, src/test/skript/environments/extra/paper-1.17.1.json, src/test/skript/environments/main/paper-1.12.2.json, src/test/skript/environments/main/paper-1.18.1.json, src/test/skript/environments/main/paper-1.9.4.json
With this update the Paper downloads will automatically use the latest build of their respective version, instead of relying on updates for them. Also updates the testing system to use 1.18.1 as the latest version.
Also updates the Java version used by the workflows to Java 17, and delays the tests by 5 seconds to make sure the server is fully started.
---
**Related Issues:** #4119, #4441, #3767 (all non-fixing)
=> Update test download system

src/main/java/ch/njol/skript/util/BlockLineIterator.java
Fix retrieving blocks between 2 blocks with at least one of the locations being **-Y** throwing IAE exception
---
**Target Minecraft Versions:** 1.17.1+
**Related Issues:**  #4645 #4383 (non-fixing)
=> ⚒️ Fix blocks between with minus Y

src/main/java/ch/njol/skript/expressions/ExprBiome.java
Adds time states and default expressions for biomes from a location (so basically anything).
Also did some micro code improvements, like removing the casting each for loop.
This script below will now work with this pull request
```vb
on teleport:
broadcast "%biome%"
if the biome at the future location will be basalt deltas, the end or nether:
cancel event
```
=> Add time states to biomes

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Restricts entity event values from being used in the death event and forces users to use `attacker/victim` to avoid confusion as to why they're not getting a message or why their code isn't erroring.
A user in the SkUnity discord was questioning why they weren't getting any errors and what was wrong with their script. Turns out it wasn't erroring because there was multiple entities involved in the event and either `player` or `event-entity` wasn't working.
Example script that will now error with this pull request:
```vb
on death of player:
attacker is a player
message "Needs to specify the sender"
message "Who is this messaging?" to event-entity
```
Fix of example script:
```vb
on death of player:
attacker is a player
message "&dYou just killed %victim%" to attacker
```
=> Exclude entity event values from death events

src/main/java/ch/njol/skript/effects/EffBroadcast.java, src/main/java/ch/njol/skript/effects/EffMessage.java, src/main/java/ch/njol/skript/lang/ExpressionList.java
Fixed EffMessage and EffBroadcast to handle 'or' expression lists correctly.
Also changed how a few of ExpressionList's methods work (getSingle, getArray and iterator), how the behaviour changed is explained in example below. The rest of the diff is formatting.
```
command /test:
trigger:
broadcast "a", "b" or "c"
send "A", "B" or "C"
set {_x} to "X"
set {_y} to {_x} or {_none}
broadcast "y: %{_y}
```
Before PR:
After PR:
ExpressionList would always try to pick a non-null value instead of picking a random value from the list.
I personally think the new behaviour from this PR makes more sense, but I'd like feedback on it (which is why I added 'up for debate' label)
---
**Related Issues:** #4543
=> Fix message and broadcast with or list, redesign or ExpressionList getting

src/main/java/ch/njol/skript/expressions/ExprIndices.java
Re-adds the 'all' syntax to ExprIndices, accidentally removed in #3922. Also removes the optional 'the' from the second pattern, as IMO `the {_x::*}'s indices` doesn't make much sense to me (PropertyExpression also doesn't have the 'the' on the `'s` pattern).
---
**Related Issues:** #4547, #3922 (latter non-fixing)
=> Re-add ExprIndices pattern 'all' part

src/main/java/ch/njol/skript/expressions/ExprSaturation.java
Fixes an NPE when using e.g. `reset saturation of player`.
Changes the syntax of the saturation expression to that of a normal property expression, reducing syntax conflict between saturation, the potion effect and saturation, the expression involving a player.
Changelog: see https://github.com/SkriptLang/Skript/pull/4554#pullrequestreview-869349032
---
**Related Issues:** #4552, #692
=> Fix ExprSaturation issues

src/main/java/ch/njol/skript/effects/EffChange.java
For example when using the code `add 1 to player`
Before PR:
After PR:
Caused by #4104
---
**Related Issues:** #4552, #4104 (both non-fixing)
=> Re-add error from EffChange

src/main/java/ch/njol/skript/expressions/ExprPlayerProtocolVersion.java, src/main/java/ch/njol/skript/expressions/ExprProtocolVersion.java
Added an expression for getting players' protocol version, exclusive to Paper. Supported all the way back to 1.12.
Also changed ExprProtocolVersion syntax. This can be a breaking change and open to discussion.
---
**Requirements:** Paper
**Related Issues:** #1655
=> Add ExprPlayerProtocolVersion

src/main/java/ch/njol/skript/Skript.java
Makes Skript only accept registrations if the plugin is loaded & enabled.
I've seen multiple addon devs accidentally include Skript within their addon jar, this'll make it easier for them to detect the problem.
---
=> Make Skript only accept registrations if it is enabled

.gitignore, src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/expressions/ExprHanging.java
This PR adds a new expression to get the hanging entity/remover from hanging break and place events
---
**Related Issues:** #4359 #892
=> 🚀 Add Hanging Entity/Remover expression

src/main/java/ch/njol/skript/hooks/regions/classes/Region.java
Adds a `String` -> `Region` converter.
---
**Requirements:** any supported region plugin
**Related Issues:** #4684
=> Add string to region converter

src/main/java/ch/njol/skript/util/BlockUtils.java
Fix the computation for the pitch of block locations
---
**Related Issues:** #4708, #4280 (latter non-fixing)
=> Fix the pitch of locations of blocks

src/main/java/ch/njol/skript/entity/EntityData.java, src/main/java/ch/njol/skript/entity/FallingBlockData.java, src/main/java/ch/njol/skript/entity/PlayerData.java, src/main/java/ch/njol/skript/entity/ThrownPotionData.java, src/main/java/ch/njol/skript/entity/XpOrbData.java
Fixes falling block spawning with sections by making EntityData implementations override `spawn(Location, Consumer)` instead of `spawn(Location)`. 
---
**Related Issues:** #4716
=> Fix falling block spawning with sections

src/main/java/ch/njol/skript/aliases/ItemData.java, src/test/skript/tests/regressions/3419-item comparisons.sk
This PR fixes the comparison issue described in the related issue.
This was caused by #4162, as the methods used for comparisons in utility methods were changed.  However, the new method comparison process no longer included a crucial check, causing this issue. I have added the check along with a test.
Before PR (taken from the linked issue):
After PR:
---
**Target Minecraft Versions:** 1.12 and below
- #4643
=> Fix broken comparisons on 1.12 and below

src/main/java/ch/njol/skript/effects/EffReplace.java, src/main/java/ch/njol/skript/lang/Variable.java, src/test/skript/tests/regressions/4672-looping-expression-list-single-variables.sk
Fixes `Variable#iterator` for single variables. The method implementation assumed the variable would be a list variable, and therefore mostly copied code from `Variable#variablesIterator`. This fix adds an exception to return a single item iterator when the variable is not a list variable, containing the item. 
This fix also exposed a bug in EffReplace caught by one of our tests: EffReplace called with inventories and items will not use the right item comparisons to detect which items to replace. In particular, it only matched items with the same item amount. I've fixed this by using ItemType#isSimilar, but the test also said the item amount had to remain the same after replacing, so the new EffReplace implementation also takes care of that.
--- …
=> Fix variable iterator and EffReplace with items

src/main/java/ch/njol/skript/expressions/ExprAmount.java, src/main/java/ch/njol/skript/expressions/ExprArrowPierceLevel.java, src/main/java/ch/njol/skript/expressions/ExprFallDistance.java, src/main/java/ch/njol/skript/expressions/ExprProjectileBounceState.java, src/main/java/ch/njol/skript/expressions/ExprProjectileCriticalState.java
A little PR hopefully accepted one to fix some missing and extra `[the]` in some syntaxes.
Thanks to @Moderocky for pointing out `ExprAmount`
---
=> 🚀 Fix some extra and missing `[the]`s

src/main/java/ch/njol/skript/expressions/ExprYawPitch.java
Changes the add and set behaviors of ExprYawPitch to return a vector of the same length as the original, rather than a vector of length 1. I hope I did this correctly, first time contributing to anything.
---
**Target Minecraft Versions:**  Any
**Requirements:**  None
**Related Issues:**  #4610
=> Fix vector length reset when adding/setting pitch & yaw

src/main/java/ch/njol/skript/util/Utils.java
Makes `Utils#parseHexColor`'s pattern not range from 0-z but from 0-f, and make the pattern a static pre-compiled field
---
**Related Issues:** #3908 (non-fixing)
=> Utils#parseHexColor detail

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/lang/TriggerItem.java, src/main/java/ch/njol/skript/util/SkriptColor.java
- Replaces chat color codes in debugging statements instead of stripping them
- Handle unhandled debugging statements for chat color codes
**Before**
**After**
---
**Related Issues:**  None
=> ⚒️ Replace color char in debug statements

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/SkriptConfig.java
Adds an error message instead of an exception when changing the hook enabled config options and reloading config (after server has started).
Error: https://pastebin.com/frfCmne9
---
=> Add error when disabling hooks via config after server start

src/main/resources/lang/english.lang
=> Fix typo in empty folder warning

src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
The line `if damage cause is projectile` was parsed as `if event-damage cause is the event-projectile`. This isn't a problem, as Skript has comparator built in to handle this (a DamageCause - EntityData comparator). However, this comparator had an issue, it switched its arguments around.
---
**Related Issues:** #4709
=> Fix damage cause projectile comparison

src/main/java/ch/njol/skript/log/RedirectingLogHandler.java, src/main/java/ch/njol/skript/log/RetainingLogHandler.java, src/main/java/ch/njol/skript/log/SkriptLogger.java, src/main/resources/lang/english.lang, src/main/resources/lang/german.lang, src/main/resources/lang/korean.lang
Fixes console colors, adds `SkriptLogger#sendFormatted(CommandSender, String)` and replaces some logger uses with it
Spigot:
Paper:
---
**Related Issues:** #4723
=> Fix console colors

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This PR makes this code work
```v
on pickup:
send "1" # used to default to dropped item not player
on drop:
send "2"
```
- Changed pickup event's getPlayer() method return type to Player instead of Entity to fix this
- Added event-player to drop event
---
**Related Issues:**  #1322
=> ⚒️ Fix event-player in drop/pickup events

src/main/java/ch/njol/skript/expressions/ExprChestInventory.java
Title says all. While these inventories are allowed in older server versions (including 1.13), since the client doesn't display them properly, I think it's a good idea to disallow them on those versions too. The check made on newer server versions is: `9 <= size && size <= 54 && size % 9 == 0`, used to be just `size % 9 == 0`. Also fixes indentation of the file (used spaces instead of tabs).
---
**Related Issues:** #4736
=> Fix ExprChestInventory exceptions from too large chest inventories

src/main/java/ch/njol/skript/aliases/AliasesProvider.java
Currently, Skript does not perform any sort of duplication check when adding item data. This leads to duplicate item data ending up throughout many of the default item types stored. The goal of this PR is to add a check to avoid adding duplicate item data to default item type.
Before this PR, the default item type for `any spawn egg` included a massive 457,000+ item data. After this PR, it includes only around 60 (1 per spawn egg). You can even test this by comparing the toString output of each (`send "spawn egg" parsed as item type`) - do note that the toString for before this PR will likely lag and/or freeze the server.
---
- #4514
- Technically fixes the issue. Although toString for the mentioned item types will …
=> Fix aliases duplicating item data for default item types

src/main/java/ch/njol/skript/events/SimpleEvents.java, src/main/java/ch/njol/skript/expressions/ExprClicked.java
- Fix order of ExprClicked patterns due to `clicked button` was probably being parsed as `itemtype` (button) therefore matches `clicked block` pattern and fails
- Fix docs example
- Add new option to clicked enchantment button syntax `(button|option)`
---
- #4686
=> ⚒️ Fix clicked enchantment button

src/main/java/ch/njol/skript/sections/EffSecSpawn.java, src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Adds an error when attempting to use a spawn section on 1.9.4, as they aren't supported on that version (the method for spawning an entity with a consumer didn't exist yet, nor did the consumer interface).
Example of exception on 1.9.4 without fix: https://pastebin.com/c0U6LpsP
---
=> Add error when spawn section used on 1.9.4

src/main/java/ch/njol/skript/effects/EffDrop.java
I have changed the air check to use Material#isAir instead of checking against Material.Air.
---
**Target Minecraft Versions:**  any
**Requirements:** No additional requirements
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4757
=> Changed from check against Material.AIR to Material#isAir in drop effect.

src/main/java/ch/njol/skript/effects/EffDrop.java
My previous fix used the Material#isAir method which isn't avalible in versions prior to 1.15, so here is another fix :)
I have tested it on 1.18, 1.14 and 1.11
---
**Requirements:** No additional requirements
**Related Issues:** No related issues
=> Change Material#isAir since the method is only avalible in versions 1.15 and later

build.gradle, src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java, src/main/java/ch/njol/skript/aliases/Aliases.java, src/main/java/ch/njol/skript/aliases/AliasesParser.java, src/main/java/ch/njol/skript/classes/data/SkriptClasses.java, src/main/java/ch/njol/skript/command/CommandHelp.java, src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/java/ch/njol/skript/doc/HTMLGenerator.java, src/main/java/ch/njol/skript/effects/EffLog.java, src/main/java/ch/njol/skript/expressions/ExprCommandInfo.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/lang/UnparsedLiteral.java, src/main/java/ch/njol/skript/lang/function/Parameter.java, src/main/java/ch/njol/skript/localization/Language.java, src/main/java/ch/njol/skript/patterns/LiteralPatternElement.java, src/main/java/ch/njol/skript/patterns/SkriptPattern.java, src/main/java/ch/njol/skript/registrations/Classes.java, src/main/java/ch/njol/skript/util/EnchantmentType.java, src/main/java/ch/njol/skript/util/PotionDataUtils.java, src/main/java/ch/njol/skript/util/PotionEffectUtils.java, src/main/java/ch/njol/skript/util/SkriptColor.java, src/main/java/ch/njol/skript/util/StructureType.java, src/main/java/ch/njol/skript/util/Timespan.java, src/main/java/ch/njol/skript/util/Utils.java, src/main/java/ch/njol/skript/util/chat/ChatMessages.java, src/main/java/ch/njol/skript/util/chat/MessageComponent.java, src/main/java/ch/njol/util/Kleenean.java
In many parts of Skript, when converting to lower/upper case, a Locale is not specified. This means that the default Locale is used (usually dependent on the user's system).
The following, taken from the `String#toLowerCase()` javadoc, is an example of why this is an issue:
*Note: This method is locale sensitive, and may produce unexpected results if used for strings that are intended to be interpreted locale independently. Examples are programming language identifiers, protocol keys, and HTML tags. For instance, "TITLE".toLowerCase() in a Turkish locale returns "t\u0131tle", where '\u0131' is the LATIN SMALL LETTER DOTLESS I character.*
The result within Skript is that unexpected characters sometimes pop up during the parsing process for users on different locales, causing parsing to …
=> Fix Locale-related String conversion issues

src/main/resources/lang/default.lang
Adds 1.19 spawn reasons to default.lang:
- spell
- metamorphosis
---
**Target Minecraft Versions:** 1.19
=> Add 1.19 spawn reasons to default.lang

src/main/java/ch/njol/skript/tests/platform/Environment.java
Disables Spigot watchdog in our tests, as they've been crashing the test servers lately.
I don't know exactly why watchdog determined that our servers haven't been responding, because the default timeout time, the time that a server should hang until watchdog crashes it, is set to 60 seconds and watchdog crashes the server less than 60 seconds after it *begins* starting.
There is another part to the condition, relating to stopping servers, which probably causes the issue, but I'm not entirely sure.
https://github.com/PaperMC/Paper/blob/master/patches/server/0385-Improved-Watchdog-Support.patch
https://github.com/PaperMC/Paper/blob/master/patches/server/0238-Add-Early-Warning-Feature-to-WatchDog.patch
--- …
=> Disable watchdog in tests

src/main/java/ch/njol/skript/Skript.java
The previous fix (#4900) didn't work (see https://github.com/SkriptLang/Skript/pull/4845/commits/75e9ca17db24e9c9339547dd8096a1d514a7d92c for example, the previous PR was included in this test but it crashed nevertheless) because I though Paper would be a bit smarter: the `disable.watchdog` property they use to determine whether watchdog should be disabled or not, doesn't actually apply to the scenario that causes our servers to crash:
This scenario is explained below:
- the server is stopping (Server#shutdown is called, which Skript does after running its tests)
- the server hasn't stopped yet, i.e. is still in a tick: [MinecraftServer#x on 1.17.1](https://pastebin.com/pSMHbrB5)
- the last server tick was over a second ago, which is easily reachable because all of our tests are run in …
=> Fix test servers crashing part 2

src/main/java/ch/njol/skript/effects/EffStopSound.java
Fixes sound category for 1.10.2 and lower versions.
The stop sound effect forgot to remove the sound category expression from the second pattern which handles no sound category.
Self tested on Java 8 to be working fine.
**_Note that this is going into dev/2.6 branch_**
---
**Target Minecraft Versions:** 1.10.2 and lower
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4933
=> Fixes sound category on 1.10.2

src/main/java/ch/njol/skript/bukkitutil/EnchantmentUtils.java
Fixed sweeping edge not being registered on 1.11.2 and Skript erroring because it has no allocation to the enchantment.
Sweeping edge actually came out in 1.11.X but it's only registered in 1.12.
Self tested on Java 8 to be working fine.
**_Note that this is going into dev/2.6 branch_**
---
**Target Minecraft Versions:** 1.11.2
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4933
=> Fix 1.11.2 sweeping edge

.github/workflows/java-17-builds.yml, .github/workflows/java-8-builds.yml
Fixes nightly uploads
Also makes the test workflows only trigger for pull_requests or pushes to either the main or a dev branch, otherwise PRs from a branch not on a fork would run the workflows too many times. Syntax reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters and paragraph below
=> Fix nightly uploads

src/test/skript/tests/syntaxes/effects/EffHealth.sk
So the EffHealth randomly fails for no reason, potentially change zombie to cow may fix this as the zombie may be taking damage from sun burning?
=> Attempts to fix the random zombie health test failing

src/main/java/ch/njol/skript/SkriptCommand.java
Adds Skript flavour to the Skript info command. This way developers can identify what flavour the user is using.
This came up when we didn't know that the user was using a nightly build and reporting errors.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4974
=> Add flavour to Skript info command

.github/workflows/java-17-builds.yml, .github/workflows/java-8-builds.yml
Fixes the tests not running on the master branch, when a commit is made. This is caused by https://github.com/SkriptLang/Skript/pull/4946, which mistakenly used the branch name `main` instead of `master`, but we don't have such a branch.
---
**Related Issues:** #4946 (non-fixing)
=> Fix Actions not running on master branch

.github/dependabot.yml
Removes the language / ecosystem labels from Dependabot PRs, but keeps the generic `dependencies` label, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels
Also changes the file indentation to match that of the Dependabot docs, IMO it's better because the `-` from lists is no longer on the same level as its parent
*When merging, delete the `java` label (and `github_actions` label if it exists)*
---
=> Remove Dependabot language label

src/main/resources/config.sk, src/main/resources/lang/french.lang
This Pull Request adds the default language file `french.lang`.
Considering the difficulty I had translating some key words into French to keep an equivalent meaning, I would especially like to receive some reviews from the French community and know what you think about it! Also, I thought it was appropriate to use the formal pronoun *vous* to address users. Let me know what you think too! :)
If you have any questions about a translation or suggestions for improvement, please don't hesitate!
---
**Target Minecraft Versions:**  any
**Related Issues:**  none
=> Add french translation

src/main/java/ch/njol/skript/effects/EffEquip.java
ironically enough the 'equip' effect actually has support for multiple entities, it's just the pattern that doesn't support it, this PR fixes that issue
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5083
=> allow multiple livingentities in EffEquip's pattern

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/SimpleEvents.java
I am planning to add Paper's PlayerTradeEvent so that you don't need any addons or anything else.
---
**Requirements:** Paper 1.16+
=> Add Paper's PlayerTradeEvent in SimpleEvents

src/main/java/ch/njol/skript/effects/EffMakeEggHatch.java
This PR simply moves the `EffMakeHatch` out of the expression folder and into effect folder
I noticed it wasn't placed in the correct area
---
**Target Minecraft Versions:**  N/A
**Requirements:**  N/A
**Related Issues:**  N/A
=> Move EffMakeHatch to effect folder

src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
This PR makes the split expression use the config's case sensitivity option
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4886
=> ExprJoinSplit config case sensitivity

src/main/java/ch/njol/skript/entity/FallingBlockData.java
Skript will no longer throw a NPE when spawning a falling block without specifying the block type and will default to Stone
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5042
=> Fix falling block NPE

src/main/java/ch/njol/skript/patterns/OptionalPatternElement.java, src/main/java/ch/njol/skript/patterns/ParseTagPatternElement.java
Allows for syntax like `:[abc|def]` meaning `[(abc:abc|def:def)]`
---
=> Allow parse tags to be expanded onto optional pattern elements

README.md, src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/config/Config.java, src/main/java/ch/njol/skript/config/SectionNode.java, src/main/java/ch/njol/skript/localization/Language.java
This PR enables lang file updates when Skript detects a version change.
There are a few questions where I'm looking for input though:
- Should we allow addons to opt into this feature? Should it only be for Skript? My thought is that addon opt in would only be possible for addons that handle language files the same as Skript (I'm not sure any do tbh)
- Right now, it *always* updates and creates a backup of a lang file if a version change is detected. This is because Skript has no built-in capability of detecting differences in *values* of Config objects, only the actual keys themselves. Should we add a way for Skript to check if the values themselves have changed? It might result in *slightly* longer startup time when the version changes, but it might be better than just assuming it's …
=> Add lang file updates on version change

src/main/java/ch/njol/skript/effects/EffBroadcast.java, src/main/java/ch/njol/skript/effects/EffMessage.java
Title
It looks like players support advanced formatting. I tested on 1.9.4.
This fix is achieved by using the exact same logic as EffMessage.
---
**Target Minecraft Versions:** 1.12 and below
- https://github.com/SkriptLang/Skript/issues/5019
=> Fix message sending on legacy versions

src/main/java/ch/njol/skript/lang/VariableString.java
Fixes VariableString#isQuoted correctly, to return false for the input string `"` (with `withQuotes=true`).
---
**Related Issues:** #5149
=> Fix isQuotedCorrectly, to account for 1-char string `"`

src/main/java/ch/njol/skript/SkriptEventHandler.java, src/main/java/ch/njol/skript/events/EvtClick.java
This PR expands SkriptEventHandler's unregister method to attempt to unregister Skript's listener from the event's HandlerList if possible (meaning there are no other triggers depending on it).
Very brief and minor testing seems to indicate that it works. Logic was taken from other methods where these sorts of checks are done.
---
**Related Issues:** It's been discussed, but I don't think there's an issue
=> Implement unregistering event listeners when possible

build.gradle, src/main/java/ch/njol/skript/util/BlockStateBlock.java, src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Updates dev/2.6 to support 1.19.2
dev/2.6 currently doesn't work in 1.19.2 as it's missing pull request (#5009) that fixed missing implementations.
Implement missing methods for Block implementations on dev/2.6 branch.
---
**Target Minecraft Versions:** 1.9.4-1.19.2
**Skript target version:** 2.6.4
=> dev/2.6 Implement missing methods for Block implementations

src/main/java/ch/njol/skript/expressions/ExprFreezeTicks.java, src/test/skript/tests/syntaxes/expressions/ExprFreezeTicks.sk
Removes the artificial cap on freeze ticks imposed in #4781 .
I initially added it as I mistakenly thought the freeze ticks should not exceed the limits vanilla survival sets on it (between 0 and getMaxFreezeTicks). However, this makes it really difficult to freeze and entity for any significant period of time, so allowing it to exceed the getMaxFreezeTicks value makes a lot of sense. Any values above the max do not change the experience of an entity, it just extends the time the entity is in the maximum frozen state.
---
**Target Minecraft Versions:** 1.18+
**Requirements:** 1.18+ 
**Related Issues:** #4781
=> Remove cap on freeze time in 1.18 freeze syntax

README.md
Make the `scope` tag `provided` because many new developers include the whole Skript jar in their plugin's jar and won't know why their plugin isn't working
=> Change Maven dependency

src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
This PR aims to fix an issue with Skript not being able to compare block datas with each other
---
**Related Issues:** #5251
=> DefaultComparators - add comparator for BlockData - BlockData

src/main/java/ch/njol/skript/Skript.java
ZipEntry#getName does not correlate with Files.seperator.
After:
plugins/Skript/lang/
plugins/Skript/scripts/
=> Fix examples and lang files not generating

src/main/java/ch/njol/skript/expressions/ExprName.java
***This PR is a replacement PR for https://github.com/SkriptLang/Skript/pull/5259.***
*Forwarded from above stated PR*
This PR adds World support to ExprName.java.
Before PR:
After PR:
Requested changes stated from old PR has been carried over to this PR.
---
=> Support Worlds into ExprName.java

src/main/java/ch/njol/skript/conditions/CondIsValid.java
Add isValid for entities. When programming in Java, you typically use isValid over isDead because this method checks if the server considers it valid or not which includes it being despawned.
This addition is mainly for the unit testing system to ensure entities are fully gone.
---
**Related Issues:** non closing isValid https://github.com/SkriptLang/Skript/issues/4185
=> Add isValid for entities

README.md
The indentation seemed off, it was a tab, the other parts are spaces. Now they are all spaces.
=> Fix inconsistency in README.md

src/main/java/ch/njol/skript/Skript.java
Fixes scripts example folder generation. It's generating as `plugins/Skript/scripts/scripts/--example/` rather than `plugins/Skript/scripts/-example/` Also makes sure that all scripts carried over from the jar are disabled or in a disabled folder for jar security. Someone may add a malicious example script and distribute that said jar as anyone can do that without compiling code.
=> Fix scripts example folder generation

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This PR aims to fix an issue with event-values for BlockSpreadEvent (`on spread`)
both past/current event-block both returned the same block.
With this fix, the past event-block will be the old block, and event-block will be the new block.
---
=> BukkitEventValues - current/past event-block both return the same for BlockSpreadEvent

src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
Skript no longer supports 1.12- and `OTHER_AIR_EXISTS` is actually since 1.13 not since 1.14
---
=> 🛠 Removes 1.13 code from ItemUtils.isAir

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/expressions/ExprSourceBlock.java
Added a way to get the source block in BlockSpreadEvent
---
**Requirements:** No requirements
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5346
=> add event value for BlockSpreadEvent.getSource();

src/main/java/ch/njol/util/Pair.java
(originated from https://github.com/SkriptLang/Skript/pull/5403#discussion_r1088771469)
The previous implementation will return 0 if the `hashCode` of the objects equal due to the XOR operation. Therefore, a pair with equal objects will always have the same `hashCode`, which can be efficient if a data structure like a `HashMap` or `HashSet` contains pairs of possibly equal objects.
See also the contract of `hashCode`: https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--
---
=> Improve hashCode of Pair

src/main/java/ch/njol/skript/lang/SkriptParser.java
Fix parsing of an empty string. #5103 reordered the if statements in SkriptParser#next, causing a call with a startIndex out of range of the string to be incremented with context COMMAND.
---
**Related Issues:** #5103
=> Fix empty string parsing

.github/workflows/docs.yml
When a javadocs dir is already present, the workflow merged in #5383 fails as `mv` doesn't want to overwrite the existing directory. This fixes the issue by making sure the `DOCS_DIR` is empty before generating or moving anything.
---
=> Fix issue with nightly docs job not working when javadocs dir is already present

src/main/java/ch/njol/skript/lang/ExpressionList.java, src/test/skript/tests/misc/expression list checking.sk
This PR aims to fix an issue with negating the result of a condition used with an expression list. See image below and test for an explanation:
Both should print, but this is not currently the case. This is because the negation was applied at the end, when it should likely be applied to each expression's result.
---
**Related Issues:** None?
=> Fix expression list checking

src/main/java/ch/njol/skript/util/BlockUtils.java, src/test/skript/tests/misc/blockdata parser.sk
This change allows using aliases instead of minecraft names when parsing blockdata
---
=> Allow using alises when parsing BlockData

security.md
Updates the security document to recommend that security issues are privately reported via the security advisory page on github.
---
=> Update security guidelines to point to new reporting page

src/main/java/ch/njol/skript/expressions/ExprPermissions.java
Fixes a useless concatenation and double space in the toString of ExprPermissions.
---
=> Fix double space in toString of ExprPermissions

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/expressions/ExprScript.java, src/main/java/ch/njol/skript/lang/VariableString.java, src/main/java/ch/njol/skript/lang/parser/ParserInstance.java, src/main/java/org/skriptlang/skript/lang/script/Script.java, src/test/skript/tests/misc/effect commands.sk
This PR adds some safety checks and corrects some usages of Script that may result in an error occurring during the usage of effect commands (or other runtime parsing mechanisms).
I've also added in a rough test. This means that effect commands are **always** enabled for console during **tests**.
---
=> Script handling improvements

src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
This PR fixes an [exception](https://pastebin.com/jqqqggPk) being thrown when trying to get the return type of plural event values, due to the array class being returned instead of the component's class
code:
```vb
on sign change:
loop event-strings:
broadcast loop-value
```
---
=> Fix plural event values exception

src/main/java/ch/njol/skript/expressions/ExprAttacker.java
This PR fixes ExprAttacker not working in damage events. See the issue below:
This error occurred because the isCurrentEvent check was broken, but I recently fixed it.
EvtDamage is based on the EntityDamageEvent, but ExprAttacker requires EntityDamageByEntityEvent, thus the error. This simple fix restores previous behavior. No additional checks are needed since the `get` method already has instanceof checks.
---
**Related Issues:** N/A (reported on Discord)
=> Fix ExprAttacker not working in damage events

src/main/java/ch/njol/skript/expressions/ExprChunk.java, src/main/java/ch/njol/skript/expressions/ExprColoured.java, src/main/java/ch/njol/skript/expressions/ExprGameMode.java, src/main/java/ch/njol/skript/expressions/ExprLightLevel.java, src/main/java/ch/njol/skript/expressions/ExprShooter.java, src/main/java/ch/njol/skript/expressions/ExprTarget.java, src/main/java/ch/njol/skript/expressions/ExprVehicle.java, src/main/java/ch/njol/skript/expressions/ExprWorld.java, src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java, src/main/java/ch/njol/skript/expressions/base/SimplePropertyExpression.java, src/main/java/ch/njol/skript/util/Getter.java
Currently, addons making use of PropertyExpression will error with a NoSuchMethodError, like this one:
This is because these classes were made to require usage of the new Converter class. Of course, we can easily rectify this issue by having the method make use of the old Converter class. This also makes SimplePropertyExpression and Getter implement/extend (respectively) the old Converter class. This should have a minimal impact internally while allowing these addons to function. Some syntax classes have been updated so that they are using lambdas (allowing this to easily work regardless of which Converter class is required).
Since old Converter extends new Converter, Getter and SimplePropertyExpression are still both new Converters as well (they are just also old ones again too).
--- …
=> Fix Converter compatibility for Property Expressions

build.gradle
Disables the JUnit test from running when building. The build task does not start up a test runner server instance, so it'll throw errors as the JUnit tests are expecting a server to be running. This will disable that for the build task, which should be just like gradlew assemble. Use the provided test tasks for testing specific traits of Skript.
=> Disable JUnit in build

src/main/java/ch/njol/skript/structures/StructVariables.java, src/test/skript/tests/misc/default variables.sk
Fixes a bug where Skript attempts to add type hints to the default variables data of a variable that was not defined in the default variables, causing Skript to critical internal error. This is only present on scripts that utilize the default variables section.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5510
=> Fix unrelated default variables

build.gradle, src/main/java/ch/njol/skript/test/runner/EffDebug.java
Adds a debug effect for printing all the details about an expression or checking what effect/condition class Skript parsed an input as. Note the `-` in the `debug-effect` and condition is to avoid conflicting. Skript cannot understand the effect without it.
=> Add debug effect

build.gradle, settings.gradle
Adds the Gradle suggested toolchain downloader for whatever latest Java version we support. https://docs.gradle.org/current/userguide/toolchains.html
This allows any new contributor to start building Skript without having to need Java 17 installed. Gradle will do this automatically by applying Java 17 for them. This means when the IDE goes to compile Skript/Spigot for usage, it ensures it's set to Java 17 as that is what Paper 1.17+ requires.
Tested on a Java 8 machine with Eclipse.
Labeling as a bug as a few users have had issues and asked for support before in the development Discord channels of SkUnity.
Notes:
- Skript still compiles down to Java 8 target.
- This does not impact the Skript runner tests. They still run on Java 8 and Java 17 respectively.
=> Gradle auto apply correct JDK version

src/main/resources/lang/default.lang
Adds missing .lang values for 1.19.4
```
[21:07:46 INFO]: [Skript] Line 41: (combat.sk)
[21:07:46 INFO]:     Missing entry 'entities.sniffer.name' in the default/english language file
[21:07:46 INFO]:     Line: spectral arrowªs = minecraft:spectral_arrow[relatedEntity=spectral arrow]
[21:07:46 INFO]:
[21:07:46 INFO]: [Skript] Line 41: (combat.sk)
[21:07:46 INFO]:     Missing entry 'entities.text display.name' in the default/english language file
[21:07:46 INFO]:     Line: spectral arrowªs = minecraft:spectral_arrow[relatedEntity=spectral arrow]
[21:07:46 INFO]:
[21:07:46 INFO]: [Skript] Line 41: (combat.sk)
[21:07:46 INFO]:     Missing entry 'entities.item display.name' in the default/english language file
[21:07:46 INFO]:     Line: spectral arrowªs = …
```
=> Add missing .lang values for 1.19.4

src/main/java/ch/njol/skript/events/EvtPlayerChunkEnter.java
This PR makes the keyword 'player' in the pattern of EvtPlayerChunkEnter as optional, which I should have done it in my previous PR on implementing this event.
---
=> EvtPlayerChunkEnter - Make 'player' Keyword Optional

src/main/java/ch/njol/skript/conditions/CondIsWithin.java
I mistakenly used == to compare chunks and worlds in CondIsWithin, leading to failing tests in 1.19.4. 
This PR corrects that mistake and uses .equals() instead.
---
**Related Issues:** #5371
=> Fix Comparison Mistake in CondIsWithin

src/main/java/ch/njol/skript/Skript.java
You currently cannot use any classinfo registered in the BukkitClasses inside any .lang file. This fix changes the loading order of BukkitClasses to also be registered with SkriptClasses. No issues from my testing, but could use testing from users with many scripts.
- Moves the platform version check higher. (I dont know why this isn't the first thing to check)
- Moves BukkitClasses higher to load with SkriptClasses.
=> Change loading order for BukkitClasses

build.gradle
Adds in the Adventure API serializer for the Bungeecord Chat API.
This allows us to use the Component classes that Paper has been deprecated in Spigot in favor of the Adventure API methods using Adventure API components. The BungeeComponentSerializer converts BaseComponents to Adventure API Components.
---
**Related Pull Requests:** https://github.com/SkriptLang/Skript/pull/5601 and https://github.com/SkriptLang/Skript/pull/5622
=> Include the Adventure API BungeeComponentSerializer

src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java
This PR fixes ExprVectorRandom to strictly returning vectors with magnitude of 1.
Permission was granted to change the way vectors are generated within this PR scope.
---
=> ExprVectorRandom - Fix Vectors not Unit & Not True Random Generations

src/main/java/ch/njol/skript/variables/FlatFileStorage.java, src/main/java/ch/njol/skript/variables/SQLStorage.java, src/main/java/ch/njol/skript/variables/Variables.java
Fix databases not currently registering. Due to the security improvements in https://github.com/SkriptLang/Skript/pull/4873 Skript is currently unable to create a CSV database due to no method found caused by getConstructor and not using getDeclaredConstructor so a CSV is never created. This pull request fixes that and also makes SQLStorage public as that's what the goal of that abstract class was for.
---
=> Fix databases not currently registering

src/main/java/ch/njol/skript/expressions/ExprBlocks.java
This PR fixes ArrayStoreException thrown in ExprBlocks introduced in #5566, caused by when getting blocks from a list of locations.
---
**Related Issues:** #5566
=> ExprBlocks: Fix ArrayStoreException

src/main/java/ch/njol/skript/classes/data/JavaClasses.java
Reverts SkriptLang/Skript#4667 This is currently unstable at the moment and needs further improvements see https://github.com/SkriptLang/Skript/issues/5635
=> Revert "Allow literal-only string parsing"

src/main/java/ch/njol/skript/lang/VariableString.java
Fix error when calling a non default variable that wasn't saved in default variables. Also cache's classinfo result for performance rather than doing so each iteration of the variable string.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5647
=> Fix error in non default variables

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
```
05.05 00:29:27 [Server] ERROR #!#! Stack trace:
05.05 00:29:27 [Server] ERROR #!#! java.lang.IllegalArgumentException: World unloaded
05.05 00:29:27 [Server] ERROR #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
05.05 00:29:27 [Server] ERROR #!#!     at org.bukkit.Location.getWorld(Location.java:112)
05.05 00:29:27 [Server] ERROR #!#!     at Skript-2.6.4.jar//ch.njol.skript.classes.data.BukkitClasses$6.serialize(BukkitClasses.java:398)
05.05 00:29:27 [Server] ERROR #!#!     at Skript-2.6.4.jar//ch.njol.skript.classes.data.BukkitClasses$6.serialize(BukkitClasses.java:394)
05.05 00:29:27 [Server] ERROR #!#!     at Skript-2.6.4.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:178)
05.05 00:29:27 [Server] …
```
=> Fixes IllegalArgumentException throwing with unloaded worlds in location serialization

src/main/java/ch/njol/skript/expressions/ExprVersionString.java
This PR fixes a bug introduced in Skript 2.7, in ExprVersionString where the expression can't be used in 'server list ping' event, where it should, and performed class cleanup to follow latest code convention.
---
**Requirements:** Paper 1.12.2+
**Related Issues:** #5597
=> Fix ExprVersionString Unusable in Server List Ping Event

src/main/java/ch/njol/skript/doc/Documentation.java, src/main/java/ch/njol/skript/doc/HTMLGenerator.java
- Fixed docs examples non HTML tags not escaped (HTML tags have no use cases in skript examples)
- Also removed escaping quotes as that's only needed in attribute values which we don't use and it was causing problems as not appearing as quote symbol in HTML element content, see https://stackoverflow.com/a/25918549
---
- closes https://github.com/SkriptLang/skript-docs/issues/30
=> 🛠 Fix docs examples non HTML tags not escaped 

src/main/java/ch/njol/skript/entity/EntityData.java, src/test/skript/tests/syntaxes/expressions/ExprTotalExperience.sk
Apply EntityData#set before calling the consumer, so the changes are properly reflected in the section of the EffSecSpawn syntax.
Breaking change because people might have adapted to this weird behavior, although very low chance as it requires an expression in the entity data.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5711
=> Apply entity data changes before calling consumer

src/main/java/ch/njol/skript/aliases/ItemData.java, src/main/java/ch/njol/skript/aliases/ItemType.java, src/test/skript/tests/regressions/3419-item comparisons.sk
This PR aims to fix item comparisons for ItemTypes created through `type of <itemtype>`. The issue is rather simple, which is that ItemFlags (specifically for having non-default tags) is not correctly applied. This causes the related issue, since items like potions and goat horns do not have non-default tags.
Also, while slightly odd given the name, aliasCopy does *not* return a "default" item, and this is specifically mentioned in the method's javadoc. Thus, it needs to be handling this "CHANGED_TAGS" flag even for items that aren't potions or goat horns (since properties like lore are kept).
I have also gone ahead and removed some useless code that didn't actually do anything except add overhead.
---
- …
=> Fix Item Comparisons For "Base" ItemTypes

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Fix fireworkeffect classinfo doesn't have usage
---
- closes https://github.com/SkriptLang/skript-docs/issues/32
=> 🛠 Fix fireworkeffect classinfo doesn't have usage

src/main/java/ch/njol/skript/doc/HTMLGenerator.java
- Fix docs returntype check inverted 🤦
- This fixes 2 issues
- Java classinfos not appearing (related issue)
- Other classinfos have no links
---
- closes https://github.com/SkriptLang/skript-docs/issues/24
=> 🛠 Fix docs returntype check inverted

src/main/java/ch/njol/skript/aliases/AliasesParser.java, src/main/java/ch/njol/skript/aliases/AliasesProvider.java, src/main/java/ch/njol/skript/aliases/ItemData.java
- Switched `AliasesProvider.materials` set implementation from Java SE `HashSet` to FastUtil `ObjectOpenHashSet`.
- Re-wrote `AliasesParser#fixName(String)`.
> **Note**  
> The re-written method is stricter about which kinds of whitespace it strips. This doesn't affect any of our aliases, as the spaces are never used.
---
**Requirements:** n/a
**Related Issues:** n/a
=> Make aliases faster

build.gradle, gradle.properties, src/main/resources/lang/default.lang, src/test/skript/environments/java17/paper-1.20.1.json
Update 2.7.0 to Spigot 1.20.1
There is a warning present https://github.com/SkriptLang/Skript/issues/5740
=> [2.7.0 target] Update 2.7.0 to Spigot 1.20.1

src/main/java/ch/njol/skript/expressions/ExprBlocks.java
Fix null pointer exception in ExprBlocks when using the ExprDirection without a number defined.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5787
#5566
=> Fix null pointer exception in ExprBlocks when using the ExprDirection without a number defined.

src/main/java/ch/njol/skript/util/Utils.java
Since we're using the class loader of a provided plugin, the error if no class being found gets sent through NoClassDefFoundError and not ClassNotFoundException because NoClassDefFoundError refers to the class loader not being able to find the class.
This resulted in Skript critical hard failing, disabling itself and being unresponsive, becoming a pain to task manager end task for the testing environment and addons. Now it errors without crashing itself.
=> Fixes error not properly being caught

src/main/java/ch/njol/skript/events/SimpleEvents.java
Fix loot generate example, and include a reference to `event-location` as that's gonna be useful to this event.
---
=> Fix loot generate example

src/main/java/ch/njol/skript/effects/EffReturn.java, src/main/java/ch/njol/skript/structures/StructFunction.java
There was a need for cleaner return functions instead of the old one, because the `::` is so confusing for people who learn by looking at codes
``function getScore(player: player) :: number: `` old 
``function getScore(player: player) returns number:`` new 
---
any
=> Update the return function regex

src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java, src/test/skript/tests/regressions/pull-5748-fix bugs in the random number expression.sk
This PR fixes a variety of bugs and weird behaviors of the random number expression. Like:
```vb
random integer between 1 and 1 # Returns nothing. Should return 1
random integer between 1.9 and 2.1 # Returns nothing. Should return 2
random integer between 1 and 1.5 # Returns nothing. Should return 1
random integer between 1.5 and 2 # Returns nothing. Should return 2
```
---
https://github.com/SkriptLang/Skript/pull/5443
=> Fix bugs in the random number expression

src/main/java/ch/njol/skript/effects/EffTeleport.java
Add warning to notify the user about using teleport in the spawn section.
getParser().getCurrentSection(EffSecSpawn.class) did not work. Probably something @APickledWalrus could look at fixing. Used the custom SpawnEvent as it works just as fine.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5717
=> Add warning to notify the user about using teleport in the spawn section

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/util/BlockUtils.java
Add proper error for BlockData failing rather than can't compare.
Fixed indentation on the BlockData classinfo to match the rest of the file, and removed the 1.13+ required plugins method from the classinfo.
*Before*
*After*
---
**Target Minecraft Versions:** 1.14+
=> Add proper error for BlockData failing

src/main/java/ch/njol/skript/expressions/ExprBlocks.java
Fix null pointer exception in ExprBlocks when using the ExprDirection without a number defined.
2.7.0 target for https://github.com/SkriptLang/Skript/pull/5790
(cherry picked from commit 549ebc380b34dd544c760d7a2c23faa8973a12f7)
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5787
=> [2.7.0 target] Fix null pointer exception in ExprBlocks when using the ExprDirection without a number defined

src/main/java/ch/njol/skript/Skript.java
This PR address the issue of variables loading after script loading occurs (meaning events like `on script load` have already triggered). This change was made in https://github.com/SkriptLang/Skript/pull/4873, where the intent may have been to allow addons to provide users the ability to register their own variable storage implementations within scripts. Additional changes will need to be made and tested for something like that to be feasible. It is important to note that this PR will *not* affect the ability for addons to register their own storage implementations. This code is still executed within a delayed task (it is just executed before scripts load now).
---
- …
=> Address Variable Loading Changes

src/main/java/ch/njol/skript/util/chat/BungeeConverter.java, src/main/java/ch/njol/skript/util/chat/ChatMessages.java, src/main/java/ch/njol/skript/util/chat/MessageComponent.java, src/main/java/ch/njol/skript/util/chat/SkriptChatCode.java, src/main/resources/lang/default.lang
This PR implements keybind tags in Skript's formatting system. The syntax is `<keybind:value>`, where `value` is the node for the keybind
An example of how a keybind component looks like:
---
=> Add support for keybind components

src/main/java/ch/njol/skript/SkriptConfig.java, src/main/resources/config.sk
Prevents Skript from enabling Timings support for Paper versions 1.19.4 or greater. 
Fixes #5726
---
**Related Issues:** #5726
=> Disable Timings for 1.19.4+

src/main/java/ch/njol/skript/sections/SecConditional.java, src/test/skript/tests/syntaxes/sections/SecConditional.sk
(cherry picked from commit 639bcf7b06d293199664dc65d40328dcad6fa9d7)
2.7 target for https://github.com/SkriptLang/Skript/pull/5872
Related issue: https://github.com/SkriptLang/Skript/issues/5866
=> [2.7.0 target] Fix issue where mixing different types of conditionals

src/main/java/ch/njol/skript/effects/EffEnchant.java
A quick fix for #5530 instead of waiting for #4366 since that might take sometime and this fix should also target 2.7
---
- #5530
=> ⚒ Fix enchanting multiple items

src/main/java/ch/njol/skript/expressions/base/SimplePropertyExpression.java
Add defending for simple property expressions for %objects%
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5452
=> Add defending for simple property expressions

src/main/java/ch/njol/skript/expressions/ExprPercent.java, src/test/skript/tests/syntaxes/expressions/ExprPercent.sk
Adds `%number%(\\%| percent) of %numbers%`, as requested by #2692.
Arguably does not complete the issue, but I'm of the opinion that `500 + 1%` does not make much sense and should not equal 505.
---
**Related Issues:** #2692
=> Adds ExprPercent

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/effects/EffApplyBoneMeal.java
Added "apply bone meal" effect.
---
https://github.com/SkriptLang/Skript/issues/5869
=> Added "apply bone meal" effect.

src/main/java/ch/njol/skript/expressions/ExprTarget.java, src/test/skript/tests/syntaxes/expressions/ExprYawPitch.sk
Change ExprTarget to use raytracing.
Also added a test to ensure yaw and pitch matches after indirect modification.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5650
=> Change ExprTarget to use raytracing

src/main/java/ch/njol/skript/entity/SimpleEntityData.java
This PR aims to fix an issue with display entities.
Spawning 1 of each display entity type, then doing 
`send size of all displays` returns 0.
This is due to Display.class incorrectly being registered as a simple entity, which it should have been a super type.
---
**Target Minecraft Versions:** 1.19.4+
=> SimpleEntityData - Display should be super entity

src/main/java/ch/njol/skript/effects/EffChange.java
Adds `decrease` to `reduce` changer
*ignore that issue's close pull request, I did it for wrong branch*
---
**Target Minecraft Versions:** 'any'
**Requirements:** 'none'
**Related Issues:** #5595
=> Add decrease to EffChange

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
Renamed Slot classinfo name from Inventort Slot to Slot 
https://github.com/SkriptLang/Skript/issues/5931
---
=> Rename Slot classinfo name to Slot

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
There was no present time event-value registered for the book sign event. As stated in the JavaDoc of the `EventValues#registerEventValue` method that a default for present time must always be defined.
https://github.com/SkriptLang/Skript/blob/7632dd8fb367778bf9f28b59e4f147f091d37302/src/main/java/ch/njol/skript/registrations/EventValues.java#L187-L189
*Example script that now works.*
```vb
on book sign:
broadcast "%event-item%" # Did not work
if event-item will be a writable book: # Still works
broadcast "yes"
```
Original pull request adding this https://github.com/SkriptLang/Skript/pull/813
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5671
=> Fix event-item not being present in book sign

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
(cherry picked from commit bd134d05aaed31f7460bfc94ff9ad0acc94642cf)
2.7.1 target for https://github.com/SkriptLang/Skript/pull/5877
This is because we added a future event values but no present event value.
=> Fix book sign event item

.github/workflows/java-17-builds.yml, .github/workflows/java-8-builds.yml, .github/workflows/junit-17-builds.yml, .github/workflows/junit-8-builds.yml, .github/workflows/repo.yml
Adds GitHub's gradle wrapper checker for security.
See https://github.com/gradle/wrapper-validation-action for more information.
Notes:
- GitHub recently added this gradle wrapper validation action to the default gradle build script template.
- Dependabot will keep this version updated.
=> Add GitHub's gradle wrapper checker for security

src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
This PR fixes an issue where ExprRandomNumber used [RandomGenerator#nextLong(long,long)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/random/RandomGenerator.html#nextLong(long,long)), which was added in Java 17.
closes https://github.com/SkriptLang/Skript/issues/5819
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5819
=> Fix ExprRandomNumber using a method from Java 17

src/main/java/ch/njol/skript/command/ScriptCommand.java
Prevents setLastUsage from running if the execution of the command changed lastUsage already.
Also caps remaining time to the full length of the cooldown instead of throwing an exception.
---
closes #5861
closes #5862
=> Fix changing remaining time of command cooldown

src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
Adds a filter to prevent .getValue or .getBaseValue from being called on null values.
Cleans up variable names/conventions in ExprEntityAttribute
---
**Related Issues:** #5640
=> Fix NPE with invalid attributes and clean up ExprEntityAttribute

src/main/java/ch/njol/skript/command/ScriptCommand.java
Fix cast throwing if existing variable for command storage exists.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5935
=> Fix cast throwing if existing variable for command storage exists

src/main/java/ch/njol/skript/conditions/CondIsInfinite.java, src/main/java/ch/njol/skript/effects/EffPotion.java, src/main/java/ch/njol/skript/events/SimpleEvents.java
whoopsie daisy, there were a few INSERT VERSIONS left lying around!
---
=> fix 3 stray INSERT VERSIONs from 2.7.0

src/main/java/ch/njol/skript/effects/EffContinue.java, src/test/skript/tests/syntaxes/effects/EffContinue.sk
This PR adds the ability to continue parent loops from within an inner loop. Loops are numbered from 1 to n and goes from outer to inner. For example:
```vb
loop all players: # Loop 1
loop {values::%loop-value%::*}: # Loop 2
set {_x} to foo(loop-value-2)
if {_x} < 10:
continue the 1st loop # Continues the 'loop all players' loop
bar(loop-value)
broadcast "Player has valid values!"
```
---
**Related Issues:** #6012
=> Allow 'continue' the continue outer loops

.github/workflows/cleanup-docs.yml, .github/workflows/docs/generate-docs/action.yml, .github/workflows/docs/push-docs/action.yml, .github/workflows/docs/setup-docs/action.yml, .github/workflows/nightly-docs.yml, .github/workflows/release-docs.yml, build.gradle, src/main/java/ch/njol/skript/doc/Documentation.java
This PR fixes the documentation actions on the patch branch by including the changes of:
- #5735
- #5580 
---
**Related Issues:** n/a
=> Fix Documentation Actions on dev/patch

src/main/java/ch/njol/skript/command/ScriptCommand.java
Cherry pick of fix to patch branch.
* Fix cast throwing if existing variable for command storage exists
* Update src/main/java/ch/njol/skript/command/ScriptCommand.java
=> (Cherry Pick) Fix cast throwing if existing variable for command storage exists (#5942)

src/main/java/ch/njol/skript/structures/StructAliases.java, src/test/skript/tests/syntaxes/structures/StructAliases.sk
This PR fixes an issue where using multiple aliases section in a single script did not work. The last one to load would overwrite the values of any others. The values are now merged together. I've also added a test for this.
---
=> Fix multiple aliases sections not working

src/main/java/ch/njol/skript/structures/StructVariables.java, src/test/skript/tests/syntaxes/structures/StructVariables.sk
In `2.7.0` and potentially the latest 2.7 beta, having multiple `variables:` sections in a script would produce a severe error when trying to unload or reload.
This is described in issue #6013.
The cause of this error was both variables sections using the same `DefaultVariables.class` key in the data map, so the first one to unload would remove the data, leaving it `null` for the second unload.
As version `2.6.4` supported multiple `variables:` sections (although potentially unintentionally) I have re-created the original behaviour with a bandage bug fix.
**Note:** I make no comment about whether this behaviour is correct or incorrect, intended or unintended. This is simply a fix to restore the old, expected behaviour _for the time being_.
I used the following code to test:
Version …
=> Fix error when unloading a script with multiple variables sections

.github/workflows/docs/generate-docs/action.yml, .github/workflows/nightly-docs.yml, build.gradle, src/main/java/ch/njol/skript/SkriptCommand.java, src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java, src/main/resources/lang/english.lang, src/main/resources/lang/french.lang, src/main/resources/lang/german.lang, src/main/resources/lang/simplifiedchinese.lang
In this PR:
- Disable Javadocs generation for nightly docs (see note IMPORTANT)
- Fix various placing still using old docs templates path
- Reduced Docs Nightly Push branches to limit size (might need to limit more as we're at 3GB size atm 😬)
Nightly docs javadocs was causing the issue, each javadoc is ~50mb! right now javadocs generate is disabled for nightly docs with an option for flexibility. Each of our docs files is ~2mb so we're all good without nightly javadocs.
Reopened after old PR: https://github.com/SkriptLang/Skript/pull/6044
---
=> ⚒ Disable Javadocs generation for nightly docs & improvements

CLOCKWORK_RELEASE_MODEL.md, README.md, src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/java/ch/njol/skript/conditions/CondIsInfinite.java, src/main/java/ch/njol/skript/config/Config.java, src/main/java/ch/njol/skript/effects/EffPotion.java, src/main/java/ch/njol/skript/events/SimpleEvents.java, src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java, src/main/java/ch/njol/skript/structures/StructAliases.java, src/main/java/ch/njol/skript/structures/StructVariables.java, src/test/skript/tests/syntaxes/structures/StructAliases.sk, src/test/skript/tests/syntaxes/structures/StructVariables.sk
This cross-merges the recent bug fixes from dev/patch into dev/feature in case any new features depend or need to be tested against them.
I made sure to preserve the correct version numbers on each branch and the erroneous dependabot changes that ended up on dev/feature.
In the future I can set this up to be automatic but for the time being I'm doing it manually to be careful in case we run into any unforeseen issues.
=> Merge patches in to feature branch.

.github/dependabot.yml
Changes the target branch of dependabot to always be `dev/patch`
This is the lowest point of coverage with the newest branch structure. Any and all dependency updates will flood down into dev/feature and also master from dev/patch, so it's best to set dependabot to target `dev/patch`
=> Change the target branch of dependabot

src/main/java/ch/njol/skript/effects/EffStopSound.java
Fix an NPE in EffStopSound due to exprs not actually changing positions but code tried to handle that.
---
- #6066
=> ⚒ Fix stop all sounds NPE

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/EvtPlayerChunkEnter.java
This PR cleans up and fixes EvtPlayerChunkEnter for:
- Fix potential comparison issue
- Explicitly specify event chunk values from event locations to prevent unexpected conflicts from Converters
- Minor general cleanup
---
=> Fix EvtPlayerChunkEnter Comparison & Cleanup

src/main/java/ch/njol/skript/sections/EffSecSpawn.java, src/test/skript/tests/regressions/6032-local-vars-created-in-effsecspawn.sk
EffSecSpawn now gets the current local variables at the start of each consumer run instead of using a cached version from before any consumer runs.
---
**Related Issues:** #6032
=> Fixes EffSecSpawn not properly handling local variables created within the section

src/main/java/ch/njol/skript/effects/EffVectorRotateAroundAnother.java, src/main/java/ch/njol/skript/effects/EffVectorRotateXYZ.java, src/main/java/ch/njol/skript/expressions/ExprVectorAngleBetween.java, src/main/java/ch/njol/skript/expressions/ExprVectorArithmetic.java, src/main/java/ch/njol/skript/expressions/ExprVectorBetweenLocations.java, src/main/java/ch/njol/skript/expressions/ExprVectorCrossProduct.java, src/main/java/ch/njol/skript/expressions/ExprVectorCylindrical.java, src/main/java/ch/njol/skript/expressions/ExprVectorDotProduct.java, src/main/java/ch/njol/skript/expressions/ExprVectorFromXYZ.java, src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java, src/main/java/ch/njol/skript/expressions/ExprVectorLength.java, src/main/java/ch/njol/skript/expressions/ExprVectorNormalize.java, src/main/java/ch/njol/skript/expressions/ExprVectorOfLocation.java, src/main/java/ch/njol/skript/expressions/ExprVectorSpherical.java, src/main/java/ch/njol/skript/expressions/ExprVectorSquaredLength.java, src/main/java/ch/njol/skript/expressions/ExprVectorXYZ.java
Cleans up most vector files, removing author tags, replacing e with event, and some other misc improvements
Fixes a AIOOB with rotate around XYZ's toString, an issue where removing from vector length always sets to 0, 0, 0, and allows the setting of xyz components of multiple vectors at a time.
---
=> Clean up vector classes and fix a few bugs.

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/conditions/CondIsSlimeChunk.java, src/main/java/ch/njol/skript/effects/EffExplosion.java, src/main/java/ch/njol/skript/expressions/ExprAge.java, src/main/java/ch/njol/skript/expressions/ExprExplosionYield.java, src/main/java/ch/njol/skript/expressions/ExprExplosiveYield.java, src/main/java/ch/njol/skript/expressions/ExprGlidingState.java, src/main/java/ch/njol/skript/expressions/ExprScoreboardTags.java
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.
=> Update Minecraft wiki links to new domain

src/main/java/ch/njol/skript/expressions/ExprOnlinePlayersCount.java
The class was checking is super class while not anding it with !PAPER_EVENT_EXISTS
---
- #6088
=> ⚒ Fix fake player count paper check error

src/main/java/ch/njol/skript/command/CommandHelp.java
This PR fixes an issue with the CommandHelp class where if you had a 2 or more CommandHelp arguments deep, the language nodes would get messed up
---
=> Fix Command Help

src/main/java/ch/njol/skript/effects/EffScriptFile.java
Fixes the reloading/disabling script effect when used with a directory (e.g. `reload script "foo/"`) instead of a single file.
This moves both unloading actions to a common method that will check if the provided thing was a directory and, if so, unload everything in it.
---
**Related Issues:** #6096
=> Fix unloading/reloading a directory in the scripts effect

gradle.properties
Adds an argument to force the Gradle daemon to use UTF-8 encoding regardless of the system setting. This fixes the issue where lang files built on some systems are not properly encoded.
See: https://docs.gradle.org/current/userguide/common_caching_problems.html#system_file_encoding
---
=> Force UTF-8 encoding for Gradle daemon

src/main/java/ch/njol/skript/structures/StructFunction.java, src/test/skript/tests/syntaxes/structures/StructCommand.sk, src/test/skript/tests/syntaxes/structures/StructFunction.sk
This PR fixes an issue where options would not work in functions in some cases. With the Structure API, we should avoid having declaration order matter in cases where possible, meaning the following should work:
```
function {@name}():
...blah blah blah
options:
name: myFunction
```
This PR changes functions to load signatures in preLoad instead of init (in the same way that commands load). I have included tests for both.
---
=> Fix options issue in functions

src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/command/ScriptCommand.java
#5966 pushed the handling of commands to the proper Bukkit method of onCommand, using command events instead of a PlayerPreprocessCommandEvent listener. This has the side effect of changing the behavior of the "no permission" messages.
Spigot and Paper (1.19+) seem to send "Unknown command" messages when a player tries to use a command they do not have permission for. This is good for security, as a player should not know what is available that they do not have permissions for, but it changes the behavior of Skript, which is unacceptable for a patch version.
This PR re-adds the PPCE listener to handle permissions. It will match the command given to a Skript command and check the permissions if found. If the player does not have the permissions, it will send the message and cancel the …
=> Fix command permission messages (2.7.1 issue)

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
A partial fix to inventory holder stringifying.
The previous implementation used a fall-back `Classes.toString` on the holder, in the hope that an inventory holder was also some other kind of type (a player, an entity, whatever) which would be checked first and printed as that thing. Unfortunately, 1.20.2 added block inventory holders for inventories without a tile state, which aren't any other kind of thing and so will just recurse infinitely.
I have added an explicit check for that type, to print the block (as is done with block entities).
However, this is not a complete fix: obviously any other kind of inventory holder that is not also a kind of thing with its own class info will run into this problem, so it's going to need fixing again in the future.
---
**Target Minecraft Versions:** …
=> Fix stack overflow when stringifying block inventories.

src/main/java/ch/njol/skript/conditions/CondCompare.java, src/main/java/ch/njol/skript/util/Time.java, src/main/java/org/skriptlang/skript/lang/util/Cyclical.java, src/main/java/org/skriptlang/skript/lang/util/package-info.java, src/test/skript/tests/syntaxes/conditions/CondCompare.sk
This fixes one of the [oldest open issues](<https://github.com/SkriptLang/Skript/issues/1354>): times of day can't be compared correctly because a time can be both before or after another time depending on the context.
E.g. 06:00 is before 07:00, but it could also be after it (the following day).
This meant one of the examples `time in world of player is between 18:00 and 06:00` never worked as expected.
I added a special cyclical utility type for Time (and any future things we find/add that need to be compared in the same non-linear way). This might also be needed in future for things like angles (`360° == 0°`) or months of the year (January is between December and March, but not between March and December) or some other type.
Currently, this PR only fixes the `is between` check from …
=> Fix comparison of cyclical types (specifically comparing times)

src/main/java/ch/njol/skript/expressions/ExprTimes.java, src/test/skript/tests/syntaxes/expressions/ExprTimes.sk
Adjusts numbers by a tiny bit when used in `X times` to account for floating point errors.
The case seen in [this issue](https://github.com/SkriptLang/Skript/issues/5488) is fixed.
This shouldn't affect anything except for floating point errors since it shifts the number up by a tiny bit before it is rounded down when converted to a long.
---
**Related Issues:** #5488
=> Fix floating point rounding error in loop N times

src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
The ExprHotbarSlot currently requires a slot to be able to change the index of the slot.
This means that you have to type `set the currently selected hotbar slot of player to the slot 8 of player`
This pull request allows for that still, but also removes the redundancy of typing out the entire slot
`set hotbar slot of player to 8`
The `Player#setHeldItemSlot` method only takes in an integer, so it makes to sense to support a direct input of an integer.
Also fixes a bug where there was no integer check for the input value being under 0 which could lead to an IllegalArgumentException being thrown.
---
=> Allow numbers in the changer for ExprHotbarSlot

src/main/resources/lang/english.lang, src/main/resources/lang/french.lang, src/main/resources/lang/german.lang, src/main/resources/lang/japanese.lang, src/main/resources/lang/korean.lang, src/main/resources/lang/polish.lang
Fixes the colour being reset to white when reloading a number of scripts in a directory.
This appears to be safe since it's the only place this language entry is used, _however_ there might be another that didn't come up in my search.
---
**Related Issues:** #6136
=> Fix colour codes being reset in reload message.

src/main/java/ch/njol/skript/expressions/ExprDurability.java, src/test/skript/tests/syntaxes/expressions/ExprDurability.sk
This PR fixes an issue where if you try to modify an `itemstack`'s durability, it wouldn't properly update its `ItemMeta`.
Also cleans up the class a bit.
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/6147
=> Fix ExprDurability's Changer

src/test/java/org/skriptlang/skript/test/tests/syntaxes/EvtGrowTest.java
The JUnit test now bone meals the plants until they're grown, or it hits 100 attempts. This should help avoid test failures when the tree/wheat didn't grow (there was about a 0.5% chance the tree wouldn't grow with 10 bone meals).
---
=> Ensure EvtGrow Junit test always grows the plants/trees

src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java, src/main/java/ch/njol/skript/expressions/ExprSpecialNumber.java, src/test/skript/tests/syntaxes/functions/isNaN.sk
Adds a function to check if a value is NaN, so you don't have to go through the hassle of checking if it's not equal to itself.
Also replaces a very misleading example in ExprSpecialNumber.
---
=> add isNaN() function

src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
Prevents both left and right chaining on the InventoryHolder -> X converters.
Left because it could lead to converters like `(Entity -> Player, InventoryHolder -> Block)` which is fundamentally flawed. This issue caused #5755 and #5830.
Right because converters like `(InventoryHolder -> Entity -> Location)` are unreliable as Inventory holder could be a Block, resulting in a null value halfway through the converter.
I believe this to be a non-breaking change based on a pretty significant amount of testing, but I would appreciate second checks.
Considering making all default nullable converters unable to right chain, as the following converters rely on the first converter to have an accurate conversion, which it may not. However, this is a breaking change in at least one aspect, as it would …
=> Prevent InventoryHolder -> X chaining

src/main/java/ch/njol/skript/expressions/ExprSets.java
Fixes ExprSets conflicting with `set {_players::*} to all players`
The error mainly is present when parsing syntaxes with `%players%` not the above example.
The expression ExprSets should be returning false silently without an error to allow Skript to continuously keep checking for other syntaxes. Essentially grabbing Player EntityData instead of ExprSets.
We don't want to error when Skript checks ExprSets as it should be returning all the players on the server, not using the classinfo to collect all the players (which has no supplier causing this error).
---
=> Fix ExprSets conflicting

src/main/java/ch/njol/skript/effects/EffPotion.java
Simple switcheroo. I don't like the syntax for this effect, to be honest, but I don't think it's worth changing right now.
---
**Related Issues:** #6221
=> Fix incorrect examples for EffPotion

src/main/java/ch/njol/skript/aliases/ItemType.java, src/main/java/ch/njol/skript/expressions/ExprDrops.java
This PR fixes the drops NPE for the patch branch to resolve test failures.
---
=> (Patch) Fix NPE issue with drops in 1.20.2

src/main/java/ch/njol/skript/expressions/ExprAmount.java, src/main/java/ch/njol/skript/expressions/ExprItemsIn.java, src/test/skript/tests/syntaxes/expressions/ExprItemsIn.sk
Adds supports to get only certain item types when using ExprItemIn (e.g. `all swords in player's inventory`).
---
**Target Minecraft Versions:** All
**Related Issues:** #4612
=> Add filter support to ExprItemsIn

src/main/java/ch/njol/skript/conditions/CondCompare.java
This fixes logging problems with CondCompare that were the cause of the issue below. The errors in the linked issue are ghost errors from CondCompare reparsing literals to find a good comparison. The problem is, even when CondCompare is successful, it prints the entire log which includes errors from failed Classes.parse attempts.
To combat this issue, I have replaced the RetainingLogHandler with a ParseLogHandler. When it needs to print an error, it will print the most recent/relevant error. At the end, when successful, it will print all non-error log messages (e.g. warnings that are likely to be applicable).
---
- https://github.com/SkriptLang/Skript/issues/6251
=> Fix CondCompare Logging

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/test/runner/SkriptJUnitTest.java
Removes the final modifier on the 'cleanup' method, because this method will automatically cleanup all test data instantly, as JUnit runs instantly, and Skript itself will collect the results after the defined amount of shutdown time in ticks.
If a test is to be delayed, it needs to override the 'cleanup' method and do nothing in the method because the cleanup will happen at a later time in the junit script file code.
Added warnings to explain that if the test is delayed it needs to override the 'cleanup' method and do the cleanup itself.
---
=> Remove final on 'cleanup' method and provide JUnit implementation warnings.

src/main/java/ch/njol/skript/lang/VariableString.java
As a precursor to #5676, we need to add warnings to users to warn them of the incoming changes. This PR adds a warning whenever an expression with a `Player` return type is used in a VariableString, if the `use UUIDs in variable names` config option is false.
It directs users to https://github.com/SkriptLang/Skript/discussions/6270 to learn more about how to address the warning.
Ideally, this prompts players to switch to UUIDs through the config, but forcing them to use `player's name` is also an acceptable outcome. 
Critique on the warning's content and the explanatory discussion post is welcome.
---
**Related Issues:** #5676
=> Add warnings for using %player% without using the UUID config setting.

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/skript/tests/syntaxes/structures/StructCommand.sk
This PR fixes an issue that can occur with command parsing. #6000 made changes to the WILDCARD pattern. Reverting those changes resolved the issue.
Here is an example of the error:
(thanks @ShaneBeee)
---
=> Fix Command Parsing

src/main/java/ch/njol/skript/lang/VariableString.java
This PR fixes an issue with the warning introduced in #6271 where it would print for all usages of a player-returning expression. I have updated the check to ensure it is actually a variable being parsed.
Below is an example of the issue:
(photo credit @ShaneBeee)
---
=> Fix Erroneous Player UUID Warnings

src/main/java/ch/njol/skript/structures/StructEvent.java, src/test/skript/tests/regressions/6288-event data priority pollution.sk
Sets priority to null if not specified. Fixes #6288 
---
**Related Issues:** #6288
=> Fix event data pollution for event priority

src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java, src/test/skript/tests/regressions/6237-equip slot shoes exception.sk
Changes the parse tags of ExprArmor to avoid trying to get `EquipSlot.SHOES`, which doesn't exist and throws an exception. Instead uses `boots` as the parse tag for "shoes".
Adds a regression test to ensure it gets caught if something similar happens in the future.
---
**Related Issues:** Fixes #6273
=> Fixes IllegalArgumentException when trying to get shoes of entity

src/main/java/ch/njol/skript/expressions/ExprLocationFromVector.java
Requires `to location` in `%vector% to location in %world%` as `%vector% in %world%` was conflicting with some addon syntaxes and in my opinion, matched much to broadly.
---
**Related Issues:** #6285
=> Force "to location" in ExprLocationFromVector

build.gradle, src/main/java/ch/njol/skript/SkriptConfig.java, src/main/resources/config.sk
This PR updates the ReleaseChannel/UpdateChecker logic to account for our change in release naming. Right now it is set to have 2 channels, "stable" and "prerelease"
---
- https://github.com/SkriptLang/Skript/issues/6304
=> Fix ReleaseChannel Logic

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Fixes "parsed as a player" not working. The issue was caused by the new PARSE ParseContext not being considered in the Player ClassInfo's parse method. I have confirmed that it works as expected now.
---
- https://github.com/SkriptLang/Skript/issues/6316
=> Fix "parsed as a player" Not Working 

src/main/java/ch/njol/skript/events/SimpleEvents.java
Adds `armour` option to armor change event and adds that option to search keyworkds
---
**Related Issues:** none 
- #6355
=> 🚀 Allow `armour` in armor change event

src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
Fixes a simple bug in ExprArmorSlot class where it only returns not single if expr is not single, while this property expression may return non single while expr is single if user asked for armor of expr
---
**Related Issues:** none 
- #6354
=> ⚒️ Fix isSingle of ExprArmorSlot

src/main/java/ch/njol/skript/classes/data/JavaClasses.java
changed the `./strings/` to the `./text.html` in `.../Skript/src/main/java/ch/njol/skript/classes/data` path.
---
**Related Issues:** [from skript-docs](https://github.com/SkriptLang/skript-docs/issues/58#issue-2106753800)
=> fix 404 error

src/main/java/ch/njol/skript/entity/SimpleEntityData.java, src/main/resources/lang/default.lang
This PR aims to add the new entities from Minecraft 1.20.3, Breeze and Wind Charge
---
**Target Minecraft Versions:** 1.20.3+
**Related Issues:** #6345
=> SimpleEntityData - add new MC 1.20.3 entities

src/main/java/ch/njol/skript/Skript.java
Related #6351 
Adds the obfuscated name for Server#isRunning for 1.20 versions.
Please note that whilst this change is untested, it should be correct.
=> Fix Skript MinecraftServer.isRunning reflection on 1.20(.1)

src/main/java/ch/njol/skript/expressions/ExprLocationFromVector.java, src/main/java/ch/njol/skript/expressions/ExprLocationVectorOffset.java, src/main/java/ch/njol/skript/expressions/ExprVectorAngleBetween.java, src/main/java/ch/njol/skript/expressions/ExprVectorBetweenLocations.java, src/main/java/ch/njol/skript/expressions/ExprVectorCrossProduct.java, src/main/java/ch/njol/skript/expressions/ExprVectorCylindrical.java, src/main/java/ch/njol/skript/expressions/ExprVectorDotProduct.java, src/main/java/ch/njol/skript/expressions/ExprVectorFromDirection.java, src/main/java/ch/njol/skript/expressions/ExprVectorFromXYZ.java, src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java, src/main/java/ch/njol/skript/expressions/ExprVectorNormalize.java, src/main/java/ch/njol/skript/expressions/ExprVectorOfLocation.java, src/main/java/ch/njol/skript/expressions/ExprVectorSpherical.java, src/test/skript/tests/regressions/6348-vector from expressions conflict.sk
Updates the ExpressionType for all vector expressions. Since FromDirection is now PROPERTY and fromXYZ is now COMBINED, from XYZ now takes priority. This does technically mean you cannot do ``vector[s] from {_dir1}, {_dir2}, {_dir3}``, but personally I think that's not something to worry about.
---
**Related Issues:** #6348
=> Fix "vector from" syntax conflict by making ExprVectorFromDirection parse later.

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/expressions/ExprScripts.java
Disabled scripts are stored as files with relative paths, so the code works perfectly already.
Enabled scripts are Configs with Paths created by File#toPath(), so ExprScripts converts them back into Files with Path#toFile(). This creates a File with an absolute path, not relative. 
This fix relativizes the paths of all the scripts to the scripts folder.
There's an existing issue of accuracy in the disabled scripts that will be handled in another PR.
---
**Related Issues:** #6373
=> Fix paths for enabled scripts in ExprScripts.

src/main/java/ch/njol/skript/util/EnumUtils.java
If there isn't a language node available for an enum value, EnumUtil#toString() will return null. This is used in EnumClassInfo's Parser, which requires the toString to be non-null. Since we can pretty easily return null, this leads to an NPE later down the line when you attempt to `send <some expression that returns that enum value>`.
I've chosen to replace it with the enum value's name, so the user can still understand what it is, even if there's no lang node for them to use. Since this is fixing something that should only occur when we haven't yet updated to a newer minecraft version, I think this is an appropriate bandaid.
Prior to change: (creative has been manually removed from default.lang)
```
[17:32:47 ERROR]: #!#!
[17:32:47 ERROR]: #!#! [Skript] Severe Error:
[17:32:47 ERROR]: …
```
=> Avoid NPE by defaulting to enum name when no language node available in EnumUtil's toString.

gradle.properties, src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java, src/main/java/ch/njol/skript/log/ParseLogHandler.java, src/main/java/ch/njol/skript/patterns/TypePatternElement.java, src/test/skript/tests/misc/invalid unparsed literals.sk, src/test/skript/tests/syntaxes/expressions/ExprArithmetic.sk
This is an experimental fix for some issues with UnparsedLiterals that have gotten more exposure due to the changes in Arithmetic parsing. One now problematic expression is the following:
`index of event-slot - 9`
This would typically be interpreted (and expected to be interpreted as) `(index of event-slot) - (9)`. Skript is correctly identifying this as ExprArithmetic, but the left and right expressions are wrong. Skript will move from left to right trying to determine what group of characters makes up the expression. When Skript gets to the following, things go wrong: `(index of event)-(slot - 9)` Skript gets to this point and TypePatternElement does not continue as `index of event` and `slot - 9` are both valid UnparsedLiterals. ExprArithmetic then fails due to encountering …
=> Improve UnparsedLiteral Handling

src/main/java/ch/njol/skript/aliases/AliasesProvider.java
The set implementation used by Aliases is not available on some older Spigot versions.
---
- https://github.com/SkriptLang/Skript/issues/6398
=> Fix loading on Spigot versions older than 1.18

src/main/java/ch/njol/skript/expressions/ExprPlain.java, src/test/java/org/skriptlang/skript/test/tests/regression/ExprPlainAliasTest.java
Calls ItemType#getRandom() to ensure the item is a accurate representation of the alias (e.g. any sword) before getting the material.
---
**Related Issues:** #5994
=> Fix ExprPlain always getting the base material from ItemTypes

src/main/java/ch/njol/skript/expressions/ExprVectorXYZ.java, src/test/skript/tests/regressions/6385-x component of block.sk
Simple length check to prevent AIOOB when trying to mistakenly change the components of a non-vector.
---
**Related Issues:** #6385
=> Fix AIOOB with ExprVectorXYZ when used with non-vectors

src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java, src/test/skript/tests/syntaxes/expressions/ExprLastDamageCause
This fixes the recent compilation issues by using the correct damage event constructor depending on which is available.
I've included a test to ensure functionality is kept.
---
=> Fix Compilation Issues (Address DamageEvent Constructor Changes)

src/main/java/ch/njol/skript/classes/data/DefaultOperations.java, src/main/java/ch/njol/util/Math2.java, src/test/skript/tests/regressions/6328-timespan addition causes exception when overflow, src/test/skript/tests/regressions/6328-timespan operations can cause exceptions if there's an overflow.sk
This PR fixes an issue where if two timespans were to be added together and the resulting value is more than the `long` range, it would overflow into a negative value, which [causes an exception](https://pastebin.com/e5aPwtFz) since milliseconds of timespans must be 0 or above (non-negative number). To fix this, when an overflow happens the milliseconds would be the max `long` value.
---
=> Fix Timespan Addition Overflow Exception

src/main/java/ch/njol/skript/lang/function/Parameter.java
Changes Parameter#parse() to only compare lowercase parameter names if caseInsensitive is true.
Changes Parameter to store the original string, rather than the lowercased string.
Manual testing indicates this fixes the issue.
Technically breaking changes in a very niche scenario, but only because it's reverting to intended behavior, so as previously established, not marking as breaking changes.
---
**Related Issues:** #6379
=> Make function parameters respect the case-insensitive-variables setting. 

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/EvtBlock.java
Guess there was some very outdated workaround code to get the water block. It's just `getClickedBlock` now.
Tested on paper + spigot 1.20.4 and paper 1.13.2
---
**Related Issues:** #6268
=> Make bucket fill events provide the correct event-block.

src/main/java/ch/njol/skript/conditions/CondIsInvulnerable.java, src/main/java/ch/njol/skript/effects/EffInvulnerability.java, src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java
Syntaxes that use "invulnerable" will also allow "invincible" as well, to reduce confusion and make it slightly more likely someone can write the syntax from memory.
---
=> Add "invincible" as a synonym of "invulnerable" in related syntaxes.

src/main/java/ch/njol/skript/events/EvtClick.java
Fixes a bug where right clicking on an entity can fire a right click event twice.
When you right click on an entity with no block in reach, a PlayerInteractEntityEvent is called like normal
However, a PlayerInteractEvent is also called, with the type of RIGHT_CLICK_AIR.
(This is also the case if there's a block in reach, but the SkriptEventHandler filters out non-air clicks with a useItemInHand value of DENY. air clicks ALWAYS have useItemInHand value of DENY for, like, non-usable items. So those aren't an issue). This causes the following:
```applescript
on right click: # fires twice
on right click with <item>: # fires twice
on right click on player: # fires once
on right click on air: # fires once
```
The solution chosen is to combine the PIEE and PIE trackers, so we can only have one …
=> Fix duplicate calls of certain click events

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/skript/tests/regressions/6246-special character parsing issues.sk
This PR fixes an issue that could occur with the keyword search (https://github.com/SkriptLang/Skript/pull/5103) system that caused valid code with special characters to fail to parse.
This issue is caused by the fact that the problematic code assumes `String#toLowerCase` will result in a String of the same length, which is not guaranteed. As a result, the used and returned indices do not align between the regular and converted strings.
To correct this issue, I have moved the code away from using lowercase conversion. Instead, it uses `String#regionMatches` (case-insensitive) instead of `String#startsWith` with `String#toLowerCase` to accomplish the same thing.
Test included! :)
---
- …
=> Fix parsing errors caused by special characters

src/main/java/ch/njol/skript/entity/EntityData.java
This PR aims to add a check to see if a specific entity can spawn dependant on data packs.
Minecraft has started adding "Experimental Datapacks" which allow the server owner to use new things which are aimed for the next major update.
Currently in Skript, if a data pack is not enabled, and you attempt to spawn one of these entities an error is thrown.
This applies a check before spawning the entity.
I added a method rather than just directly applying this in the spawn method, this way classes which extend and override this method can also check using this method.
Also fixed a couple typos that were right there.
NOTE: Incase anyone wonders, we don't have to do this for items too. You can actually give an experimental item to a player and it will have in the lore "Disabled Item"
Same with …
=> EntityData - check if entity can spawn

src/main/java/ch/njol/skript/entity/EntityData.java
Fixes an exception from being thrown when attempting to spawn an EntityData when there is no World involved with the Location.
See header of EntityData for an explanation of this reflection https://github.com/SkriptLang/Skript/blob/11327579a9af912221ba6e0864d937935ead8799/src/main/java/ch/njol/skript/entity/EntityData.java#L73-L77
```
[09:48:07] [Server thread/ERROR]: #!#! 
[09:48:07] [Server thread/ERROR]: #!#! Stack trace:
[09:48:07] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[09:48:07] [Server thread/ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:561)
[09:48:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.spawn(EntityData.java:654)
[09:48:07] [Server …
```
=> Fixes entitydata consumer on versions 1.20.1 and below.

src/main/java/ch/njol/skript/expressions/ExprRandomCharacter.java, src/test/skript/tests/syntaxes/expressions/ExprCharacters.sk
Previously, there were no guards against `infinite value random characters between "a" and "b"`, or `-10 random characters`. 
This also fixes an issue where a null value for the amount would default to 1 character instead of 0. Needs a warning on release, but arguably a bug so not a breaking change imo.
---
=> Handle invalid amounts in ExprRandomCharacter

src/main/java/ch/njol/skript/expressions/ExprRandom.java
This expression was missing `LiteralUtils#canInitSafely()` which caused it to throw an exception because it allowed parsing literally anything that is whether known or not and failing when an unknown expression is used such as `random color of somethingunkown`
---
**Related Issues:** none 
- #6511
=> 🛠️ Fix ExprRandom missing canInitSafely

src/main/java/ch/njol/skript/lang/VariableString.java
Since the default has been updated in config, this warning isn't needed anymore.
---
=> Remove Player name/UUID in variables warning.

src/main/java/ch/njol/skript/aliases/ItemData.java, src/main/java/ch/njol/skript/aliases/ItemType.java, src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/main/java/ch/njol/skript/bukkitutil/block/BlockCompat.java, src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java, src/main/java/ch/njol/skript/entity/FallingBlockData.java, src/main/java/ch/njol/skript/events/EvtBlock.java, src/main/java/ch/njol/skript/events/EvtGrow.java
This PR was originally meant to fix an issue with FallingBlocks loading chunk(0,0).
~~It turned into stripping out all references of BlockState in ItemType/ItemData/BlockCompat.~~
It turned into deprecating all references of BlockState in ItemType/ItemData/BlockCompat and using BlockData instead.
These classes never cached nor actually ever used BlockState, it was merely a middle man to get to BlockData.
My guess is this was a pre-1.13 thing that just never properly got stripped out.
---
**Related Issues:** #6471
=> ItemData/BlockCompat - strip out BlockState middleman

src/main/java/ch/njol/skript/expressions/ExprIndices.java, src/main/java/ch/njol/skript/expressions/ExprSortedList.java, src/test/skript/tests/syntaxes/expressions/ExprIndices.sk
This PR aims to fix the alphabetically sorted issue with the sorted indices expression.
NOTE:
This changes the behaviour of ExprSortedList by sorting alphabetically ignoring case.
Previous:
```
A
B
C
a
b
c
```
NEW:
```
A
a
B
b
C
c
```
---
**Related Issues:** none #6492
=> ExprIndices - fix strings not sorting alphabetically

src/main/java/ch/njol/skript/entity/EntityData.java, src/main/java/ch/njol/skript/lang/SkriptParser.java
If an expression returns null as it's return type, it throws a NullPointerException at parse time. This pull request makes the error a safe SkriptAPIException.
Error this pull fixes:
```
[02:29:38] [Server thread/ERROR]: #!#! Stack trace:
[02:29:38] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[02:29:38] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.isAssignableFrom(Native Method)
[02:29:38] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:540)
[02:29:38] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:752)
[02:29:38] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.j …
```
=> Fix expression null pointer exception on expressions with null return type

gradle.properties, settings.gradle, src/main/java/ch/njol/skript/aliases/ItemData.java, src/main/java/ch/njol/skript/aliases/ItemType.java, src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/main/java/ch/njol/skript/bukkitutil/block/BlockCompat.java, src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java, src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java, src/main/java/ch/njol/skript/entity/EntityData.java, src/main/java/ch/njol/skript/entity/FallingBlockData.java, src/main/java/ch/njol/skript/events/EvtBlock.java, src/main/java/ch/njol/skript/events/EvtGrow.java, src/main/java/ch/njol/skript/expressions/ExprAnvilText.java, src/main/java/ch/njol/skript/expressions/ExprIndices.java, src/main/java/ch/njol/skript/expressions/ExprRandom.java, src/main/java/ch/njol/skript/expressions/ExprRandomCharacter.java, src/main/java/ch/njol/skript/expressions/ExprSortedList.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/resources/lang/default.lang, src/test/skript/tests/syntaxes/expressions/ExprCharacters.sk, src/test/skript/tests/syntaxes/expressions/ExprIndices.sk
=> Merge dev/patch into master

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/java/org/skriptlang/skript/test/tests/parsing/StaticParseTest.java
Some addons (including skript-reflect) are using the private `parse_i` method reflectively. This PR adds a proper way to do the same thing.
---
=> Add more flexible static parse method

src/main/java/ch/njol/skript/expressions/ExprElement.java
This PR adds more examples to ExprElements to showcase syntax from 2.7 and 2.8
---
**Related Issues:** #6397
=> Update examples for Elements expression

src/main/java/ch/njol/skript/effects/EffLeash.java
Changes the examples and description of the Leash effect to make it more clear.
---
=> Changes to the Leash effect's Description and Examples.

src/main/java/ch/njol/skript/expressions/ExprValueWithin.java, src/main/java/ch/njol/skript/util/ClassInfoReference.java, src/test/java/org/skriptlang/skript/test/tests/utils/ClassInfoReferenceTest.java
This PR adds a ClassInfoReference API which provides an easy wrapper around handling the plurality of ClassInfo literals. An example of the existing way can be seen in the edits to `ExprValueWithin`, although that expression doesn't take full advantage of the API since it's limited to literal classinfos.
---
=> Add ClassInfoReference system

src/main/java/ch/njol/skript/test/runner/ExprParseLogs.java, src/main/java/ch/njol/skript/test/runner/SecParse.java, src/main/java/ch/njol/skript/test/runner/StructParse.java, src/test/skript/tests/syntaxes/structures/StructParse.sk
Adds a parse structure to allow testing structures for errors. 
---
=> Add parse structure for testing

src/main/java/ch/njol/skript/events/EvtMove.java
There was a tab missing on the last line of the move event's example. I thought I might as well fix it since I stumbled upon it.
---
=> Fix Move Event's example

src/main/java/ch/njol/skript/conditions/CondCompare.java, src/test/skript/tests/syntaxes/conditions/CondCompare.sk
Currently, the only way to compare two lists for exact equality is to check each element individually within a loop. Attempting to do `1, 2, 3 is 1, 2, 3` will always fail, because Skript compares lists by comparing each element in A to every element in B. This is great for most comparisons, like >, is between, or when using OR lists like `1, 2 is 1, 2, or 3`. 
This PR adds a special case when comparing two AND lists for equality only which will compare each element to its corresponding position in the other list. This allows users to directly compare lists without having to manually loop.
Caveats: 
- If you have lists with different indices, `{indexed by name::*} = {indexed by number::*}` will return true if the values are the same (and the same order). I think this is fine, personally. …
=> Changes CondCompare to be able to directly compare two AND lists.

src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
Removed an extra [the] in the syntax to stop weird grammar such as `send the player's the hotbar slot`
It's a big change, I know
---
**Related Issues:** #6563
=> Remove redundant [the] in hotbar expression

src/main/java/ch/njol/skript/patterns/Keyword.java, src/main/java/ch/njol/skript/patterns/SkriptPattern.java
This PR implements some enhancements to the keyword system to further reduce parse times (notably on servers with a larger number of scripts).
Essentially, support is added for starting and ending keywords (keywords that appear at the start/end of a pattern). This allows usage of `String#startsWith`/`String#endsWith` over `String#contains`.
Support is also added for keywords from choice elements. That is, `(one|two)` may now be represented by a keyword that searches for either `one` or `two` in the string. If neither are present, it fails. This supports the starting/ending behavior described above.
As a breaking change, `SkriptPattern#getKeywords` was removed. I do not believe this method is used by any addons (it is only used in one place in Skript).
---
**Target Minecraft Versions:** …
=> Pattern Keyword Enhancements

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
adds a null check to the event-slot of the inventory click event
I tested it, it just returns air when clicking outside the inventory, which should be fine (probably)
---
**Related Issues:** https://github.com/SkriptLang/Skript/issues/6458
=> Inventory Click event-value null check

src/main/java/ch/njol/skript/conditions/CondCompare.java, src/main/java/ch/njol/skript/conditions/CondIsSet.java, src/main/java/ch/njol/skript/lang/VerboseAssert.java, src/main/java/ch/njol/skript/test/runner/EffAssert.java, src/main/java/ch/njol/skript/test/runner/TestTracker.java
Adds the ability to provide expected and received values for an assertion that will be provided in the error message.
```
assert <.+> [(1:to fail)] with [error] %string%, expected [value] %object%, [and] (received|got) [value] %object%
```
For assertions using conditions that implement VerboseAssert (and that don't provide custom expected/got values), EffAssert will automatically grab expected/got messages from the condition itself. This will not work reliably for expressions that change between calls, like random expressions or ExprNow, as the assert effect calls getSingle/getAll a second time. For those scenarios, using a variable or a custom expected/got message is recommended.
So far, only CondCompare and CondIsSet implement VerboseAssert, but any condition that has significant use in …
=> Improvements to EffAssert Logging

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/patterns/TypePatternElement.java
SkriptParser checked for nullable/default inputs to start with `-`, which would fail if the input was something like `%~-objects%` (since it starts with `~`, not `-`).
I delegated it to a method that checks the first `n = min(length, 5)` characters of the string for the `-` and fails if one isn't present, or the text of the input (like `objects`) starts before the `-` is found.
Obviously, if we add a hundred new `%!?^&*$-~+objects` modifiers in future this limit will need to be increased, but I kept it low for safety in case of some unusual (addon) pattern.
---
**Related Issues:** closes #6202
=> Allow nullable patterns with different modifier orders.

src/main/java/ch/njol/skript/bukkitutil/PaperEntityUtils.java, src/main/java/ch/njol/skript/effects/EffLook.java
Previously, if you asked an entity to look at a location that had no attached world it would fail with an error.
Now, it will replace the location with the equivalent one in the entity's world.
Note that this won't fix entities being asked to look at locations in _different_ worlds (which I presume will probably error or do nothing, I don't know how Minecraft deals with that) but that seemed a little out of scope for this bug fix.
This should also fix the equivalent issue in legacy versions which use the old mob goal. I don't know if this issue occurred there, but in the case that it did I've done my best to support it.
---
**Related Issues:** closes #6476
=> Looking at locations permits (relative) locations without worlds.

src/main/java/ch/njol/skript/expressions/ExprBlocks.java
The other cases all check if the world exists and return null if not, but the direction case checks only the *direction* and not the world, so this fails later on in the iterator if there isn't a world.
I followed what the other cases do and return null if the world is null.
I also added an `isWorldLoaded` filter to the getter, which *should* be okay since it checks if the world is null and if Bukkit has actually initialised the world.
---
**Related Issues:** closes #6480, closes #6479
=> Fix exception when the location has no world in ExprBlocks.

src/main/java/ch/njol/skript/effects/EffExplosion.java
Adds a check for the location having a world in the create explosion effect.
If there is no world present then the effect will not occur (since we do not know where it should take place!)
---
**Related Issues:** closes #6481
=> Fix exception when no world available to explode effect.

src/main/resources/lang/english.lang, src/main/resources/lang/french.lang, src/main/resources/lang/german.lang, src/main/resources/lang/japanese.lang, src/main/resources/lang/korean.lang, src/main/resources/lang/polish.lang, src/main/resources/lang/simplifiedchinese.lang, src/main/resources/lang/turkish.lang
Went through all the lang files and added `<light red>` color code in error messages for `/sk enable` so that it matches `/sk reload`.
Note: I do not speak any of the other languages so I relied on the structure of the reload message and the usage of placeholders so there is a chance I might have ruined the sentences.
---
**Related Issues:** #5728
=> Updated Error messages in lang files to use light red and gold

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/patterns/MatchResult.java, src/main/java/ch/njol/skript/patterns/SkriptPattern.java
This PR is a follow up to #6591. It aims to replace the ExprInfo cache with the usage of the existing, compiled SkriptPatterns (rather than creating csubstrings). This should help to reduce any performance impact.
---
=> Replace SkriptParser ExprInfo Cache

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/lang/function/FunctionReference.java, src/test/skript/tests/regressions/4988-function uuid multiple parameters.sk
Upon failing to parse a function (with too few arguments) Skript will re-attempt it explicitly as an ExpressionList of arguments.
This fixes `func(uuid of player, "hello")` being wrongly-interpreted as `func(uuid of (player, "hello"))` and failing to parse.
**Note**: the Git diff is a nightmare because the methods in SkriptParser are nine million lines long, I can't do anything about that, sorry 😦
Functions struggle with ambiguous parameters: is `func(uuid of {_a}, {_b})` asking for a function with two parameters (`uuid of {_a}` and `{_b}`) or is it asking for a function with a _single_ parameter (`uuid of {_a} and {_b}`)?
Most rational people would say the first, but Skript does not think so! Lists are checked after singular expression parsing (for arguably good reason), so `uuid of {_a} …
=> Fix function parsing with ambiguous lists in parameters.

src/main/java/ch/njol/skript/lang/Variable.java, src/test/skript/tests/regressions/pull-6600-variable-set-changer-aiiob.sk
Variable's SET changer assumes that delta is either an array of length >=1 or null, and doesn't properly handle empty arrays in some cases. This adds a check for empty arrays, which then just ignores the set.
---
**Related Issues:** https://github.com/SkriptLang/skript-reflect/issues/99
=> Fix AIIOB in Variable SET changer

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/lang/SkriptEvent.java, src/main/java/ch/njol/skript/structures/StructAliases.java, src/main/java/ch/njol/skript/structures/StructCommand.java, src/main/java/ch/njol/skript/structures/StructEvent.java, src/main/java/ch/njol/skript/structures/StructFunction.java, src/main/java/ch/njol/skript/structures/StructOptions.java, src/main/java/ch/njol/skript/structures/StructVariables.java, src/main/java/org/skriptlang/skript/lang/structure/Structure.java, src/main/java/org/skriptlang/skript/lang/structure/StructureInfo.java
This PR adds support for registering Structure that do not have sections. That is, they are based on SimpleNodes rather than SectionNodes. They simply look like:
```
do something cool
command /foo:
trigger:
...
```
A Structure may be registered this way using `Skript#registerSimpleStructure`.
An API change was required that makes `EntryContainer` nullable in Structure's init. This will not break any existing code as for non-simple Structures, it is guaranteed that EntryContainer is NotNull.
`Structure#getEntryContainer` has also been deprecated. This method's existence was previously justified for internal reasons, but those reasons no longer exist (design has improved), so neither will this method in the future. Developers are encouraged to save a reference to the entry container during …
=> Simple Structures

src/main/java/ch/njol/skript/bukkitutil/CommandReloader.java
This PR aims to update the reloader code for modern PaperMC servers.
Paper has removed the CB Relocation revision number for the packages. 
As it stands right now Skript fails to load command and/or allow for reloading on Paper 1.20.5.
---
=> CommandReloader - fix reload issue on paper

src/main/java/ch/njol/skript/lang/SkriptParser.java
Related to #6594
This PR updates the code in SkriptParser to only obtain the TypePatternElements cache (or calculate it if it is the first time) if the exprs array has a null value (that is, potentially has a default expression). This should prevent any unnecessary calls from being made.
---
=> Only determine cache if needed

src/test/skript/README.md
updates test readme with new assertion feature info
---
=> Update Tests README.md

build.gradle
Appends the version number to build artefacts, e.g. `Skript-2.8.4.jar`.
---
**Related Issues:** fixes #6622
=> Append version to artefact name.

src/main/java/ch/njol/skript/effects/EffChargeCreeper.java, src/main/java/ch/njol/skript/expressions/ExprNearestEntity.java, src/main/java/ch/njol/skript/util/Utils.java, src/test/skript/tests/regressions/6612-nearest entity cast error.sk
Fixed the entity bug thingy.
I also cleaned up the supertype-finder method so it's a little more useful in these situations.
I don't think any other Entity-returning classes make the same mistake, but there might be syntax returning other types that also gets it wrong.
---
**Related Issues:** fixes 6612
=> Fix entity casting issue and add regression test.

src/main/java/ch/njol/skript/effects/EffHealth.java, src/test/skript/tests/regressions/6643-effhealth slot not accounting existing damage
This PR aims to fix my mistake in #6586 where I forgot to update slot durability accordingly.
Do we believe this pr should also include the 1.20.5/6 changes to durability? Based off my testing earlier this morning they are pretty bugged and adding support for at least being functional isn't out of the scope entirely.
It's possible I didn't test this correctly as the related issue is very hard for me to read with how much random junk is included in it.
---
**Related Issues:** #6643
=> Fix EffHealth - slot durability not accounting correctly 

src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/java/ch/njol/skript/events/bukkit/PreScriptLoadEvent.java, src/main/java/ch/njol/util/Validate.java
Technically does change some behaviour (no longer checks for null parameters in some cases) but as these are marked with the NotNull annotation developers should not expect it to work when null gets passed anyways.
I did keep the validation in CommandAliasHelpTopic since it actually checks something that isn't covered by annotations
=> Deprecate outdated utils/validate

src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java, src/main/java/ch/njol/skript/classes/data/DefaultOperations.java, src/test/skript/tests/misc/string concatenation.sk, src/test/skript/tests/syntaxes/functions/concat.sk
1. Allows the joining of **strings** with `+`, e.g. `"foo" + "bar" = "foobar"`. \
Does **not** allow the joining of strings and numbers or other non-coercible objects.
2. Adds a var-args `concat(...)` function that permits joining anything into a single string (including non-texts).
I'm not a fan of strings as they are in Skript: I dislike that there's no true literal, I dislike how cumbersome and inefficient `"%...%"` interpolation is (both to write and to actually evaluate).
Aside from interpolation, our only other option for joining strings is the expression `(concat[enate]|join) %texts% [(with|using|by) [[the] delimiter] %text%]` which has a rather unpleasant pattern (it sounds more like an effect than an expression).
This is designed for joining texts, but _it can't coerce types …
=> Support string concatenation.

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/lang/Statement.java
When a Section `init`s, it is given a list of the preceding trigger items.
This is how an `else:` block searches for the `if..:` it belongs to.
This list basically contains information about the lines before a syntax.
However, effect sections do not get given this information **unless** they are heading a section (i.e. if they're used as inline effects rather than sections with a `:`).
This means that
```cpp
spawn a zombie:
```
gets the list of trigger items, whereas
```cpp
spawn a zombie
```
does not, despite both being the same syntax.
Presumably, this was historically done when EffectSections were made to avoid changing the signature of the `parse` method they use.
This change gives the trigger items to effect sections _whether-or-not_ they are starting a section. The `SectionNode` …
=> Allow look-behind for headless effect sections during init.

src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/main/java/ch/njol/skript/effects/EffHealth.java
This PR aims to fix an issue with max damage on custom damageable items.
EX: In MC 1.20.5+ I can create an apple that is able to take damage.
This checks the max damage from ItemMeta (if available) otherwise falls back to max durability from Material
(ive also taken into account Fuse's PR fixing the other bug in the same class since the PR isn't merged.)
---
=> EffHealth - fix max damage on custom items

src/main/java/ch/njol/skript/command/CommandUsage.java, src/main/java/ch/njol/skript/command/ScriptCommand.java, src/main/java/ch/njol/skript/structures/StructCommand.java
This changes the usage field in StructCommand to use VariableString, allowing the input of expressions.
The Bukkit command registration wants a static usage message, though, so a default usage message is also supplied (if the varString is simple, it's the varString, otherwise the default usage message for the command)
I'd prefer this to have more features, like a whole section for usage validation based on what arguments were misused, but that's for the command rework, not now.
---
=> Add dynamic usage messages for commands

src/main/java/ch/njol/skript/effects/EffSuppressWarnings.java, src/main/java/ch/njol/skript/expressions/ExprVectorArithmetic.java, src/main/java/org/skriptlang/skript/lang/script/ScriptWarning.java
For use when we intend to remove a syntax in a future version. The warning is locally, but not globally, suppressible for those who refuse to update. 
I chose to make it a static method, as opposed to an automatic warning in the parser, so that we can call it with whatever message is appropriate in a element's init method.
---
=> Add deprecated syntax warning type

src/main/java/ch/njol/skript/lang/function/Parameter.java, src/test/skript/tests/regressions/pull-6361-function-param.sk
Today is another day making Skript making more sense 🙃
After playing around with #6358 we found out that function parameters actually have almost zero limitation and @sovdeeth was generous enough to provide the weirdest valid param examples, enjoy it:
```v
function testA(loc): location, previoustype(): text):
broadcast "a"
function testB(loc(: location, previoustype): text):
broadcast "b"
function testE(loc: location, previoustyp): returns text: object = (")")):
broadcast "%{_loc}% %{_previoustyp): returns text}%"
function this((function should(not: exist) returns text:) ? object : text) :: text:
return {_(function should(not: exist) returns text:) ? object }
function never(gonna: give = (you - up)): and function never(gonna: let, you: down) :: text):
broadcast {@magic}
function …
```
=> 🚀 Making function param rules stricter for the better

src/main/java/ch/njol/skript/expressions/ExprCharacterFromCodepoint.java, src/main/java/ch/njol/skript/expressions/ExprCodepoint.java, src/test/skript/tests/syntaxes/expressions/ExprCodepoint.sk
This PR adds two expressions allowing you to get the codepoint of a character and get a character at a codepoint
---
=> Add support for character codepoints

src/main/java/ch/njol/skript/conditions/CondHasResourcePack.java, src/main/java/ch/njol/skript/conditions/CondIgnitionProcess.java, src/main/java/ch/njol/skript/conditions/CondIsFuel.java, src/main/java/ch/njol/skript/conditions/CondIsInteractable.java, src/main/java/ch/njol/skript/conditions/CondIsPassable.java, src/main/java/ch/njol/skript/conditions/CondIsSwimming.java
Removes the 1.13 version checks from conditions that still have them.
Skript doesn't run on versions below 1.13 so the condition isn't helping.
---
**Related Issues:** #6641
=> Remove 1.13 method/version checks from conditions.

src/main/java/ch/njol/skript/effects/EffMakeFly.java, src/main/java/ch/njol/skript/effects/EffPlayerVisibility.java, src/main/java/ch/njol/skript/effects/EffSendBlockChange.java, src/main/java/ch/njol/skript/effects/EffSendTitle.java
Removes the 1.13 version checks from old effects, since Skript does not support versions under 1.13.
---
**Related Issues:** #6641
=> Remove 1.13 version checks from effects.

src/main/java/ch/njol/skript/lang/util/SimpleLiteral.java
Instead of directly exposing the so-called "constant" data array, SimpleLiteral now returns an array copy of it.
This stops a malformed syntax (e.g. an addon syntax) from just doing `values[0] = ...` and permanently changing the literal value for all future reads.
---
**Related Issues:** fixes #6682
=> Copy the SimpleLiteral backing data instead of exposing it.

src/test/java/org/skriptlang/skript/test/tests/lang/CancelledEventsTest.java, src/test/skript/junit/CancelledEventTest.sk
Switched to BlockFormEvent to avoid any versioning issues.
~~Unsure why the bell tests are failing.
@bluelhf any ideas?~~
Perhaps the failures were just on my local builds for some reason.
---
=> Fix compilation error due to Spigot changes to EntityDeathEvent

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/SimpleEvents.java
This PR removes some redundant exists checks for BukkitClasses, SimpleEvents and BukkitEventValues.
- BukkitEventValues: just the AoE cloud handles were removed. The behaviour should (I think) be the same, but reflection is no longer needed.
- BukkitClasses: removes the getEntity exists check, as it should always exist in 1.13+
- SimpleEvents: initially didn't plan on including this in this PR, but saw some exists checks that could be removed. Then I saw that the formatting was a bit random at times, so I made it a bit more consistent. Happy to revert this file to what it was before if the formatting stuff is out of the scope of this housekeeping stuff.
---
**Related Issues:** #6676 #6641
=> Removed some redundant exists checks and formatting stuff

src/main/java/ch/njol/skript/util/visual/VisualEffect.java, src/main/java/ch/njol/skript/util/visual/VisualEffects.java, src/main/resources/lang/default.lang, src/test/skript/tests/regressions/3284-itemcrack particle.sk, src/test/skript/tests/syntaxes/effects/EffVisualEffect.sk
This PR intends to fix particle compatibility between versions and fix some other issues that have arisen, especially after the 1.20.5 update (where the Particle enum saw major changes). For this, I have remade the particle definitions in the default language file. They are organized based on the Spigot Particle enum as of 1.20.6, with duplicate definitions for particles that had name changes present.
I have also gone ahead and rewritten the Data Suppliers for Particles with extra data. To ensure all particle are representable, I have made some tweaks to the way data is passed to the suppliers. For visual effects with patterns containing multiple expressions, they receive an array of values (may contain null).
This PR is not aiming to make any major changes to the Visual Effect system. …
=> Particle Compatibility Improvements

src/main/java/ch/njol/skript/expressions/ExprTarget.java
Fixes bug described in #6722, where the target expression doesn't raycast for entities if there's no block within 100 meters.
---
**Related Issues:** #6722
=> Fix bug with target distance and clean up method

src/main/java/ch/njol/skript/bukkitutil/PaperEntityUtils.java
Makes the target look in the direction of the vector (by making them look at their location offset by the vector) instead of using the vector components as coordinates
Also I am not fully sure how I would add tests for this so any suggestions for that would be great
---
**Related Issues:** #6723
=> Fix make look at vector

src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java, src/main/java/ch/njol/skript/expressions/base/WrapperExpression.java, src/main/java/ch/njol/skript/lang/Expression.java, src/main/java/ch/njol/skript/lang/ExpressionList.java, src/main/java/ch/njol/skript/lang/LiteralList.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/lang/util/ConvertedExpression.java, src/main/java/ch/njol/skript/lang/util/SimpleExpression.java, src/main/java/ch/njol/skript/util/LiteralUtils.java, src/main/java/org/skriptlang/skript/lang/arithmetic/Arithmetics.java, src/test/skript/tests/regressions/6623-wrong parsing order for math.sk
Fixes weird parse error from converted object return types.
`send health of {z} / max health of {z}` was originally interpreted as `send health of ({z} / max health of {z})` since the arithmetic has an Object return type, which is vacuously convertible to LivingEntity.
This change does several things:
1. Expressions can now return an array of multiple _possible_ return types (by default this is an array of the `getReturnType()`)
2. Expressions now have authority over whether something is a valid return type of theirs (by default this checks if it's assignable to one of the possible types)
3. Parser (and converted expressions) now use this method
This now means that: 1. fewer things are converted (when they don't need to be) 2. things are less likely to attempt a conversion when it's …
=> Allow multiple potential return types & defer expression type checking.

src/main/java/ch/njol/skript/entity/DroppedItemData.java, src/main/java/ch/njol/skript/sections/EffSecSpawn.java, src/test/skript/tests/regressions/pull-6746-spawn-dropped-item.sk
Allows DroppedItemData to be spawned via the World#dropItem method.
I'm kind of shaky on how the EntityData system works, so please correct me if I misunderstood parts!
This is marked as a bug fix since you could `spawn dropped stone` and it would do nothing, despite the fact that logically it should work, since you can drop stone just fine.
---
**Target Minecraft Versions:** 1.17+ 
**Related Issues:** #6745
=> Add support for spawning dropped items

src/main/java/ch/njol/skript/classes/data/DefaultConverters.java, src/test/skript/tests/regressions/6424-inventory-holder-location.sk
Re-enables the ability to get the location of an inventory holder. This feels a little hacky, but it's the best I could do without delving into BlockStateBlock.
---
**Related Issues:** #6424
=> Add InventoryHolder -> Location converter

build.gradle, src/main/java/ch/njol/skript/SkriptConfig.java
Avoids update checker thinking beta releases are stable.
---
**Related Issues:** #6714
=> Treat beta releases the same as prereleases in update checker

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
This PR aims to add missing event-values for EntityDropItemEvent
---
=> BukkitEventValues - add missing event-values for EntityDropItemEvent

src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java
This PR aims to fix two issues with ExprArithmetic introduced in https://github.com/SkriptLang/Skript/pull/6624.
Since the PR was merged into 2.8 instead of 2.9, the `Set#of` case was not safe since it requires Java 9. Additionally, `Set#of` throws an error in some cases of Vector arithmetic (multiplication) when the `returnTypes` list may contain duplicate values.
---
**Related Issues:** This was reported in Discord. The fix was confirmed to be working for the affected user.
=> Fix ExprArithmetic Set Construction

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/util/PotionEffectUtils.java, src/test/skript/tests/regressions/6756-potion missing base type causes npe.sk
This PR fixes an NPE that can occur on when attempting to obtain the potion effects of a potion without a base type.
I have removed the reflection usage for a method that was originally removed when I made the 1.20.5+ support PR. The method seems to have been added back in. However, I am forcing the usage of the recommended method when it is available.
---
- https://github.com/SkriptLang/Skript/issues/6756
=> Fix PotionData NPE

src/main/java/ch/njol/skript/structures/StructCommand.java
This PR aims to fix the CME that occurs when syncing commands on Paper 1.20.5+ versions due to internal command changes. This issue only seems to occur when a command is unregistered, registered, and then synced in the same tick. Adding a single tick delay seems to remove the error. I would prefer a fix that doesn't force a delay, but I could not find any other solutions.
---
- https://github.com/SkriptLang/Skript/issues/6735
=> Fix Command Syncing CME

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java, src/main/resources/lang/default.lang, src/test/skript/tests/regressions/pull-6760-particle itemtype conflicts.sk, src/test/skript/tests/syntaxes/effects/EffVisualEffect.sk
This PR aims to fix some particle-itemtype conflicts that were introduced in https://github.com/SkriptLang/Skript/pull/6716
For example, some inputs such as `totem of undying` would parse as a visual effect rather than an itemtype. This caused errors with variables as visual effect serialization is broken. To combat this, I've made it so that visual effects are parsed *after* item types. Additionally, I've added some additional optional keywords to the affected particle definitions.
We might also prefer a more aggressive route of requiring the usage of keywords like `particle`. I wanted to avoid this if possible. We may choose to pursue this if the parse-order changes reveal any unexpected issues.
There is one breaking change that affects the `elder guardian` option that was added in …
=> Fix Particle Definition Conflicts

src/main/java/ch/njol/skript/expressions/ExprStringCase.java
I noticed in a previous error in the issues (which was forwarded to SkBee) that the toString for the case expression doesn't include the actual string used, exhibit A:
` Current item: add nbt from "{Trim:{material:"minecraft:%lowercase%",pattern:"minecraft:%lowercase%"}}"`
As we can see here, it just says `%lowercase%`
So this PR aims to fix that, by actually sending the expression
---
=> ExprStringCase - include expression in toString

src/main/java/ch/njol/skript/entity/SimpleEntityData.java, src/test/skript/tests/regressions/6762-cant spawn a firework.sk
This PR aims to fix fireworks not being able to be spawned. This issue was caused by https://github.com/SkriptLang/Skript/pull/6523, as Fireworks are (for whatever reason) considered not spawnable.
@sovdeeth has opened an issue with Spigot: https://hub.spigotmc.org/jira/browse/SPIGOT-7677
I've added additional API for a SimpleEntityData to specify whether it overrides the canSpawn behavior. I'm not sure if we would wish to expand it to properly check for entities blocked by experiments.
---
- https://github.com/SkriptLang/Skript/issues/6762
=> Fix firework spawning

src/main/java/ch/njol/skript/structures/StructCommand.java
Related to https://github.com/SkriptLang/Skript/pull/6763
Fixes an error that can occur from StructCommand registering a task when Skript is disabled. I noticed this error in the testing suite. I did not notice this issue in-game.
---
- https://github.com/SkriptLang/Skript/issues/6801
=> Fix StructCommand Illegal Task Scheduling

build.gradle
Automatic release documentation has not been working for some time now. This was caused by https://github.com/SkriptLang/Skript/pull/6628 not updating the releaseDocs check which expected the jar name to be 'Skript-github.jar' rather than the versioned name (e.g. 'Skript-2.8.7.jar'). Since the jar name was wrong, it could not be copied over properly for testing. I have verified that the Skript jar is properly copied over now.
---
=> Fix releaseDocs looking for wrong Skript jar

src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/test/skript/tests/regressions/6830-remove air from slot.sk
Ensures the item metas both actually exist.
---
**Related Issues:** #6830
=> fix exception when removing air from slot

src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java, src/main/java/ch/njol/skript/expressions/ExprLastDamage.java, src/test/skript/tests/syntaxes/expressions/ExprLastDamage.sk
This PR aims to fix the `last damage of %entity%` expression.
Someone recently stated in a help channel it threw errors.
Lo and behold it was riddled with errors.
I'm not sure how this got merged, it was horribly broken.
This fixes it, and has been tested well.
---
=> ExprLastDamage - fix everything

build.gradle, gradle.properties, src/main/java/ch/njol/skript/aliases/AliasesProvider.java, src/main/java/ch/njol/skript/aliases/ItemData.java, src/main/java/ch/njol/skript/aliases/ItemType.java, src/main/java/ch/njol/skript/bukkitutil/block/BlockCompat.java, src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java, src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/test/skript/environments/java21/paper-1.21.0.json, src/test/skript/tests/regressions/5491-xp orb merge overwrite.sk, src/test/skript/tests/syntaxes/effects/EffGlowingText.sk
This PR intends to add support for Minecraft 1.21.
I have added a new testing environment for Paper 1.21. Skript compiled without issue (at the time of writing this).
However, without this PR, Skript fails to load on Paper 1.21 (and presumably any further new releases) due to ItemStack changes. ItemStacks can no longer represent block-only materials (that is, materials such that `!Material#isItem`). This is only more of a push for us to make strong changes regarding the ItemType/ItemStack/BlockData trio, but an ideal fix would likely require a significant time investment to completely rework the alias/ItemType system.
Fortunately, I have managed to get Skript loading and tests passing without *too* many changes. One significant change is that `ItemStack#getRandom` is now nullable. There …
=> 1.21 Support

src/main/java/ch/njol/skript/lang/Section.java, src/main/java/ch/njol/skript/lang/TriggerSection.java, src/test/skript/tests/regressions/6843-current section reference issue.sk
This PR fixes an important issue where, when loading a new section, Skript may fail to remove the newly-loaded section from the current sections list. This is caused by the methods holding onto an unsafe. This issue was exposed by https://github.com/SkriptLang/Skript/pull/6699 which makes changes to the list being referenced. However, even before this PR, this was unsafe as the method `ParserInstance#setCurrentSections` exists (meaning any addons changing the list reference could introduce issues).
I have resolved this issue by creating and setting a copy of the current sections list, and then setting it back to the original list when it is time to exit.
---
**Related Issues:*
- #6843
=> Fix current section update issues

src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/test/skript/tests/syntaxes/expressions/ExprDurability.sk
This PR aims to fix an error when setting damage of an item to less than 0
---
**Related Issues:** #6869
=> ItemUtils - fix error when setting damage lower than 0

src/main/java/ch/njol/skript/util/EnchantmentType.java
This PR aims to fix an issue with how EnchantmentType#toString works.
Issue was it tried to pull names from EnchantmentUtils, but since they're not set (when using registry) it just used keys.
BEFORE PR:
AFTER PR:
---
=> EnchantmentType - fix toString showing namespacedkeys

src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
This PR fixes a small but major mistake I made with the ItemType changes in https://github.com/SkriptLang/Skript/pull/6798. I added a new BlockValues getter for Materials, but I accidentally marked the returned instance as NOT being default (i.e. having special block values). Of course, this is wrong because the BlockData used is freshly created. This caused many comparison issues as items without specific block values were considered as having them.
---
- https://github.com/SkriptLang/Skript/issues/6864
=> Fix Incorrect BlockValues#isDefault

src/main/java/ch/njol/skript/bukkitutil/InventoryUtils.java, src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/expressions/ExprName.java, src/main/java/ch/njol/skript/expressions/ExprOpenedInventory.java
This fixes an issue where `name of <inventory>` does not work on versions older than 1.21. This is caused by InventoryView now being an interface on 1.21 rather than an abstract class.
---
- https://github.com/SkriptLang/Skript/issues/6872
- https://github.com/SkriptLang/Skript/issues/6879
=> Fix ExprName InventoryView IncompatibleClassChangeError

src/main/java/ch/njol/skript/aliases/ItemType.java, src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/conditions/CondIsPreferredTool.java, src/main/java/ch/njol/skript/effects/EffOpenBook.java, src/main/java/ch/njol/skript/effects/EffReplace.java, src/main/java/ch/njol/skript/entity/BoatChestData.java, src/main/java/ch/njol/skript/entity/BoatData.java, src/main/java/ch/njol/skript/entity/DroppedItemData.java, src/main/java/ch/njol/skript/expressions/ExprMaxStack.java, src/main/java/ch/njol/skript/expressions/ExprPlain.java, src/main/java/ch/njol/skript/util/visual/VisualEffects.java, src/test/java/org/skriptlang/skript/test/tests/regression/ExprPlainAliasTest.java
This PR aims to fix usages of ItemType#getRandom that did not properly check whether it is null (as is possible due to 1.21 changes).
I've updated `ItemType#getMaterial` to instead return a random Material rather than the material of the first ItemData. Some places do not need a random ItemStack, just a random Material (which can never be null).
Additionally, I've added a new method, `getRandomStackOrMaterial` (terrible I know, suggestions welcome) which grabs a random ItemData from the ItemType, and returns its ItemStack or Material (if it does not have stack). This is for cases where either an ItemStack or a Material is valid (e.g. max stack size). We may also choose to not return values for these materials, even though they exist. Thoughts welcome 🙂 
---
**Target Minecraft Versions:** …
=> ItemType Random Safety Improvements

src/main/java/ch/njol/skript/aliases/ItemData.java, src/test/skript/tests/syntaxes/effects/EffEquip.sk
This PR aims to fix an issue where ItemData#equals did not use the proper method of determining whether an ItemData represented an alias (e.g. a default item). This fixes an issue introduced by https://github.com/SkriptLang/Skript/pull/6834 where code like `equip the player with a diamond chestplate named "Test"` did not place the armor in the correct slot.
---
=> Fix ItemData#equals check

src/main/java/ch/njol/skript/effects/EffReturn.java, src/main/java/ch/njol/skript/lang/ReturnHandler.java, src/main/java/ch/njol/skript/lang/ReturnableTrigger.java, src/main/java/ch/njol/skript/lang/function/ScriptFunction.java, src/main/java/ch/njol/skript/test/runner/SecReturnable.java
This PR modifies the `ReturnHandler#returnValues` method to pass in an event and an expression object for more control on the user's end
---
=> Improve ReturnHandler#returnValues method

gradle.properties, src/main/java/ch/njol/skript/effects/EffBroadcast.java, src/main/java/ch/njol/skript/expressions/ExprInput.java
=> Prepare For Release (2.9.0)

src/main/java/ch/njol/skript/util/Timespan.java, src/test/skript/tests/regressions/6908-timespan too big.sk
Remove rounding from getAs (it should truncate anyway) to avoid limiting as int max value. Fix bug where millis was multiplied instead of divided.
---
**Related Issues:** #6908
=> Fix bugs with Timespan#getAs

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/entity/CatData.java, src/main/java/ch/njol/skript/entity/FrogData.java, src/main/java/ch/njol/skript/entity/VillagerData.java, src/main/java/ch/njol/skript/entity/ZombieVillagerData.java
This PR aims to implement a more-temporary fix for the compilation and runtime errors due to Bukkit converting some classes from Enums to Interfaces. These changes should maintain the existing behavior.
I plan to implement a longer-term replacement with proper registry usage on dev/feature (where registries are available on all supported versions). Additionally, registry support is complicated by widespread matchedPattern/ordinal usage. Any solutions should not depend on any kind of entry ordering.
---
- https://github.com/SkriptLang/Skript/issues/6924
=> Fix compilation/runtime errors due to Bukkit enum changes

src/main/java/ch/njol/skript/command/Commands.java
This PR allows effect commands to always be executed in game when using a testing server (skriptTestDev task).
---
=> Always allow effect commands on testing servers

src/main/resources/lang/default.lang
This PR aims to properly name the PotionEffectType in lang.
A few years back I did a change in the class info, from potion -> potion effect type
I think I forgot to do the lang.
This rename is more precise to the actual name of the class.
---
=> Properly name PotionEffectType in lang

src/main/resources/lang/default.lang
allows `pufferfish` as entitydata instead of just `puffer fish`
related: https://github.com/SkriptLang/skript-aliases/pull/116
---
=> allow pufferfish as entitydata

src/main/resources/lang/simplifiedchinese.lang
Previously, this would throw a severe error on load because of an extraneous %s format specifier. This is caused by the message seemingly referencing commands when that is no longer done. (According to pickle)
Credit: Msyial & NotSoDelayed (for the fixed translation)
---
**Related Issues:** #6928
=> Fixes an error with SimplifiedChinese language file

src/main/java/ch/njol/skript/aliases/AliasesProvider.java
This PR fixes an issue where missing aliases would not regenerate when doing `/sk reload aliases` or `/sk reload all`. Specifically, the bug was caused by the materials tracker of a provider not being cleared when the provider was cleared. This seems to have been a simple mistake from the original PR.
---
- https://github.com/SkriptLang/Skript/issues/6946
=> Fix missing aliases not regenerating for reloads

src/main/java/ch/njol/skript/events/EvtMove.java, src/main/java/ch/njol/skript/lang/SkriptEvent.java
This PR fixes an error that could occur for events that depend on `init` to determine the values for `getEventClasses()`. This caused an error with EvtMove as listening behavior attempted to use `getEventClasses` before it was ready (that is, before EvtMove initialized). This error *only* occurred on Spigot (where entity move does not exist)
---
- https://github.com/SkriptLang/Skript/issues/6938
=> Delay listening behavior logic until after the event implementation initializes

src/main/java/ch/njol/skript/expressions/ExprRemainingAir.java, src/test/skript/tests/syntaxes/expressions/ExprRemainingAir.sk
This PR aims to fix ExprRemainingAir issues with negative value handling. It is possible for the API to return a negative value (from -1 to -19). This appears to be used for controlling when damage occurs. I have elected to interpret negative values as 0 seconds. Additionally, while it is possible to use any negative values, the behavior is a bit strange and unlikely to be useful. I have also removed the upper limit of 10000 seconds. I was unable to replicate any client or server issues from high values. It seems to count down when in water as expected.
---
- https://github.com/SkriptLang/Skript/issues/6940
=> Fix ExprRemainingAir Negative Value Handling

src/main/java/ch/njol/skript/effects/EffPlaySound.java, src/test/skript/tests/regressions/6907-playsound entity method doesn't exist.sk
Not the nicest fix, but couldn't think of much else. I'm not a fan of how all this functional interface stuff is set up.
---
**Related Issues:** #6907
=> allow entity emitters to be null, since 1.17 and below don't support them.

src/main/java/ch/njol/skript/effects/EffLook.java
The `force the head of the player to look towards event-entity's feet` example contained something not in the actual syntax. It is now `force the player to look towards event-entity's feet`.
---
**Related Issues:** fixes #6967
=> Fix bad EffLook example.

src/main/java/ch/njol/skript/command/CommandUsage.java, src/test/skript/tests/regressions/pull-6936-single quotes in commands.sk
Manually escapes single quotes in the generated command usage message to avoid errors when trying to use single quotes as command arguments. The fix is a bandaid as there are many more problems with command parsing/argument parsing that should be addressed: ``command test %now%`` being a good example. This can come in a later pr.
---
=> Bandaid fix for single quotes in command args

.github/workflows/junit-21-builds.yml, build.gradle, src/test/skript/junit/BellEvents.sk
EasyMock 5.4.0 has released, which includes fixes for the issues that prevented us from using it for our Java 21 testing suite. This PR aims to update the dependency and re-enable JUnit Testing for the Java 21 environments.
---
**Related Issues:*
- https://github.com/SkriptLang/Skript/pull/6204#discussion_r1405302009
=> Update EasyMock to 5.4.0; Re-enable JUnitJava21

src/main/java/ch/njol/skript/effects/EffReturn.java
Previously, one of the error messages in EffReturn mistakenly used the return type's tostring method instead of getting the name of its classinfo. This PR fixes that issue
---
=> Fix EffReturn error message

src/main/java/ch/njol/skript/util/Timespan.java
Adds two simple converter methods for Skript Timespan <-> Java Duration.
Duration is the common Java timespan class, which is probably more useful to addon developers.
Since the direct milliseconds method in Timespan was deprecated and the replacement requires a few more steps to use, I thought it would be nice to have a converter for anybody wanting durations for external API.
=> Timespan <-> Duration Conversion methods.

src/main/java/ch/njol/skript/structures/StructVariables.java
This PR fixes to aim rare concurrency issues that can occur with default variables. Specifically, this may occur when two (or more) parts of a script operating on different threads (e.g. a script has an async event) try to work with default variables at the same time. What occurs is that not all `push` calls are successful (e.g. one overrides another), leading to the `pop` calls causing NoSuchElementExceptions.
I have chosen to use synchronization blocks over implementations such as [ConcurrentLinkedQueue](https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/util/concurrent/ConcurrentLinkedQueue.html). I found performance of the synchronization blocks to be better, and this is not a common occurrence that would lead to threads waiting for access.
---
**Target …
=> Fix default variables concurrency issues

src/main/resources/lang/dutch.lang, src/main/resources/lang/german.lang
Added german translation for "Nightly Build" message, it was previously still english
Added dutch.lang, have seen a lot of dutch people using Skript so thought to add it.
=> Small fix in german.lang and adds dutch.lang

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/SkriptConfig.java, src/main/java/ch/njol/skript/config/Option.java, src/main/java/org/skriptlang/skript/SkriptMetrics.java, src/main/java/org/skriptlang/skript/bukkit/SkriptMetrics.java, src/main/resources/config.sk
- every exposed config option now has a pie chart
- the config options with multiple settings have a drill chart, where layer one shows the default value and "other". Clicking on other will show you a pie chart of all the options people chose.
- effects commands also got a drilldown, showing the character people use for effect commands
- there's a new mc and skript version chart that only shows major versions on the top level and can be clicked to see the details for each major version
All the legacy charts will stick around but will be relegated to the bottom of the page after a few versions pass. The new charts will only show users on 2.9.2+, so the legacy charts are still interesting to view, but by the time 2.10.x is out they shouldn't be that useful for us.
Chart changes are live at …
=> BStats overhaul

src/main/resources/lang/default.lang
Fix key attribute missing horse
```
[00:39:02 INFO]: [Skript]     Missing entry 'attribute types.horse.jump_strength' in the default/english language file
[00:39:02 INFO]: [Skript]     Missing entry 'attribute types.horse.jump_strength' in the default/english language file
[00:39:02 INFO]: [Skript]     Missing entry 'attribute types.horse.jump_strength' in the default/english language file
```
---
**Target Minecraft Versions:** All Java 17 test versions
=> Fix key attribute missing horse

src/main/java/ch/njol/skript/util/Utils.java, src/test/java/org/skriptlang/skript/test/tests/localization/UtilsPlurals.java
Some plural word endings are incorrectly detected, e.g. `-us` -> `-i` picks up "gui" as being a plural of (the well known word) "guus", and `-fe` -> `-ves` picks up "objectives" as being a plural of "objectife".
This PR patches these two cases _for now_ (by adding an alternative first) and I've moved to a queue and a helper class rather than a fixed-size array to make the follow-up API a little easier: you should be able to add stuff to the beginning or end of the queue without trouble.
I'd like to follow up with a proper system for doing this a little more effectively, and the ability for addons to fix any of their own problematic cases by registering plural overrides.
That's probably out of scope for a patch version so it will likely be a 2.10 feature, maybe using some registrations …
=> Temporary fix for plural endings error.

src/main/java/ch/njol/skript/effects/EffPlaySound.java
on 1.18 the entity emitters pr causes playsound to emit:
`java.lang.NoSuchMethodError: 'void org.bukkit.entity.Player.playSound(org.bukkit.entity.Entity, java.lang.String, org.bukkit.SoundCategory, float, float)'`
This changes the required methodExists check to look for `playSound(org.bukkit.entity.Entity, java.lang.String, org.bukkit.SoundCategory, float, float)` instead of `playSound(org.bukkit.entity.Entity, org.bukkit.Sound, org.bukkit.SoundCategory, float, float)`, which causes the functionality to be 1.19+ but fixes the bug for now.
Further refactoring should be done to the logic here to allow 1.18 to work with entity emitters too, but it's more involved than I think I can do in a day.
---
=> Fix NoSuchMethodError with play sound effect on 1.18

src/main/java/ch/njol/skript/expressions/ExprVehicle.java
This PR attempts to fix a NoClassDef error that occurs with ExprVehicle on newer versions of Paper. While I couldn't reproduce the issue, it appears to come from the `classExists` check. This just ensures that check is not performed in "new" support is already true/initialized.
---
- https://github.com/SkriptLang/Skript/issues/6882
=> Attempt to fix ExprVehicle NoClassDef

src/main/java/ch/njol/skript/expressions/ExprBookAuthor.java
During a profiler, I noticed book author expression was a hotspot class during Skript tests at (3.60ms 72.4%) after adapting the class to Java 17 pattern matching, it has been reduced to (1.31ms 44.8%)
---
=> Fix ExprBookAuthors performance Java 17

src/main/java/ch/njol/skript/classes/data/DefaultOperations.java, src/test/skript/tests/regressions/7059-exponent overflow.sk
an optimization for long exponents was casting to a long, resulting in capped values. Good optimization for low numbers, bad for high numbers. Just removed it since it's extremely minor benefit anyway.
---
**Related Issues:** #7059
=> fix exponent capping at long max value

src/main/java/org/skriptlang/skript/commands/CommandModule.java, src/main/java/org/skriptlang/skript/commands/api/Argument.java, src/main/java/org/skriptlang/skript/commands/api/CommandCooldown.java, src/main/java/org/skriptlang/skript/commands/api/CommandHandler.java, src/main/java/org/skriptlang/skript/commands/api/CommandSenderEvent.java, src/main/java/org/skriptlang/skript/commands/api/EffectCommandEvent.java, src/main/java/org/skriptlang/skript/commands/api/ScriptCommand.java, src/main/java/org/skriptlang/skript/commands/api/ScriptCommandEvent.java, src/main/java/org/skriptlang/skript/commands/api/ScriptCommandSender.java, src/main/java/org/skriptlang/skript/commands/bukkit/BukkitCommandHandler.java, src/main/java/org/skriptlang/skript/commands/bukkit/BukkitCommandSender.java, src/main/java/org/skriptlang/skript/commands/bukkit/BukkitScriptCommand.java, src/main/java/org/skriptlang/skript/commands/bukkit/CommandUtils.java, src/main/java/org/skriptlang/skript/commands/elements/EffCancelCooldown.java, src/main/java/org/skriptlang/skript/commands/elements/ExprAllCommands.java, src/main/java/org/skriptlang/skript/commands/elements/ExprArgument.java, src/main/java/org/skriptlang/skript/commands/elements/ExprCommand.java, src/main/java/org/skriptlang/skript/commands/elements/ExprCommandCooldown.java, src/main/java/org/skriptlang/skript/commands/elements/ExprCommandInfo.java, src/main/java/org/skriptlang/skript/commands/elements/StructCommand.java
Cleans up and reformats the existing changes made by Pickle and Sovde to modern standards.
Please do not comment on design choices or logic when reviewing this, it will be followed by a PR that's focused on filling out the existing code and reworking it a bit. It's very likely the code has some major issues right now.
---
=> Command Rework - Clean up existing code

src/main/java/ch/njol/skript/lang/SkriptParser.java
This PR fixes a null pointer caused when an unregistered ClassInfo is in an accepted changes list, and the change type is not valid. There may be other execution paths affected by this.
The proposed change will use the class' full path (or primitive name) as a fallback value in the error message if there is no ClassInfo.
---
=> Fix NPE caused by unregistered ClassInfo

src/main/java/ch/njol/skript/conditions/CondIsWithin.java, src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
This PR fixes the fact that CondIsWithin always returns false if:
- either of the two locations in `is within %location% and %location` is null, or if both are in separate worlds
- if the "container" is null in `is within %entity/chunk/world/block%`
Now, it takes into account whether the condition is negated, and returns true or false appropriately.
Say I have a guard clause like so:
```applescript
if player is not within {_loc1} and {_loc2}:
send "&cThe region specified is invalid."
stop
```
If the condition fails, one would assume that the player _is_ within the two locations. However, this precondition is violated if either of the two locations are not set. As the condition is doomed to _always fail_ if the locations are null (regardless of negation), the following code will still run. …
=> Return isNegative() and not false, if CondIsWithin is invalid

.github/workflows/checkstyle.yml, build.gradle, checkstyle.xml, code-conventions.md
This PR adds [checkstyle](https://checkstyle.sourceforge.io/) to the Skript project, ensuring adherence to the coding standards described in the [code-conventions.md](https://github.com/SkriptLang/Skript/blob/master/code-conventions.md) file.
Currently checkstyle does not run automatically after the build task and must be executed manually. This is intentional to avoid increasing build times.
Additionally I have added a GitHub actions workflow for checkstyle. The workflow is configured not to fail even when code violations are detected as the severity level is set to 'warning' rather than 'error'. This is because there are currently over 6,000 code violations in the project, and failing the check would block the CI pipeline.
Once all these issues are resolved the severity can be changed …
=> Introduction of checkstyle

src/main/java/ch/njol/skript/aliases/ItemType.java, src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/main/java/ch/njol/skript/expressions/ExprSkull.java, src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
There's currently a bug when setting the profile of a skull using an OfflinePlayer without a username. SkullMeta#setOwningPlayer(OfflinePlayer) do not check if the username is present and still creates a new GameProfile, leading to a NPE. This PR addresses the issue by providing an alternative player profile with empty username.
Although this has been fixed in [SPIGOT-7882](https://hub.spigotmc.org/jira/browse/SPIGOT-7882) (the same way I did here), the bug persists in older versions supported by Skript.
---
**Related Issues:** #7090
=> Preventing NPE caused by creation of PlayerProfile from OfflinePlayer

src/test/skript/tests/regressions/5804-is-burning.sk
This PR fixes Skript tests failing, due to a wait being used to allow the pig's fire ticks to update. Waits aren't allowed in tests, so now just uses the ignite effect.
---
=> Fixes 5804-is-burning regression test

src/test/skript/tests/syntaxes/expressions/ExprJoinSplit.sk, src/test/skript/tests/syntaxes/sections/SecFilter.sk
Fixes missing and/or warnings in ExprJoinSplit.sk and SecFilter.sk.
Tests only failing due to what #7124 tries to resolve
---
=> Fixes missing and/or warnings

src/main/java/ch/njol/skript/SkriptCommand.java, src/main/java/ch/njol/skript/log/LogEntry.java
Fixes #7103 
---
**Related Issues:** #7103
=> Fix unformatted Skript system messages 

build.gradle, gradle.properties, src/main/java/ch/njol/skript/entity/BoatChestData.java, src/main/java/ch/njol/skript/entity/BoatData.java, src/main/resources/lang/default.lang, src/test/skript/environments/java21/paper-1.21.3.json, src/test/skript/tests/syntaxes/effects/EffHealth.sk
Fixes issue with spawning boats (though boats are still buggy and will be fixed in 2.10).
Bumps tests to 1.21.3, fixes issue with cow health test.
Adds new variants to attribute types lang file, apparently all the registry fields were renamed. 1 new one was added.
Adds pale garden to biome lang entry.
---
=> Adds basic 1.21.3 support.

src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java, src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/entity/SimpleEntityData.java, src/main/resources/lang/default.lang
creaking
attribute/biome de-enum-ing
baby squid/glowsquid/dolphin
---
=> more 1.21.3 support

src/main/java/ch/njol/skript/expressions/ExprTimeState.java
This PR fixes a bug (or so I believe) where the time states expression (`past something`, `future something`) *only* accepts expressions which have a single return value, which means registering a plural event value with a `FUTURE` or `PAST` time state, did not do anything.
---
=> Fix the time states expression not accepting plural expressions

src/main/java/ch/njol/skript/effects/EffContinue.java, src/test/skript/tests/syntaxes/effects/EffContinue.sk
This PR fixes a bug with `EffContinue` in 2.10 beta where `continue` (without specifying a loop) would continue the outermost loop rather than the innermost.
```applescript
loop x:
loop y:
continue # Would continue 'loop x'
```
---
=> Fix EffContinue

src/main/java/ch/njol/skript/expressions/ExprARGB.java, src/main/java/ch/njol/skript/expressions/ExprColorOf.java, src/main/java/ch/njol/skript/util/Color.java, src/main/java/ch/njol/skript/util/ColorRGB.java, src/main/java/ch/njol/skript/util/SkriptColor.java, src/test/skript/tests/syntaxes/expressions/ExprARGB.sk
Adds expression to get ARGB values of any color. 
Adds API to Color to get ARGB values.
---
**Related Issues:** #5492
=> Expression to get ARGB values of colours

src/main/java/ch/njol/skript/classes/data/DefaultOperations.java, src/test/skript/tests/regressions/7209-long overflow.sk
Catches long overflows in arithmetic by taking code from Math.addExact and multiplyExact to detect if an overflow occurred.
---
**Related Issues:** #7209
=> Prevent long overflow in arithemetic

src/main/java/ch/njol/skript/conditions/CondIsUsingFeature.java
The original purpose of the `is using` condition was to be able to test other scripts. Initially, this wasn't really possible (so it just supported the current script) but with script references it is.
Based on #6702, the only actual change is in `ch.njol.skript.conditions.CondIsUsingFeature`.
---
**Related Issues:** requires #6702
=> Allow any script in `using` condition.

src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java, src/test/java/org/skriptlang/skript/test/tests/regression/MissingTreeSaplingMapEntriesTest.java
Also adds a test to catch this in the future.
---
=> Add missing tree types to prevent EvtGrow causing errors.

src/main/java/org/skriptlang/skript/lang/arithmetic/Arithmetics.java
This PR aims to change the `exactOperationExists` method within the `Arithmetic` class allowing skript-addons to ensure an operation does or does not already exist if registered by another addon.
---
**Related Issues:** #7206
=> Arithmetic Private Methods Changed to Public

src/main/java/ch/njol/skript/Skript.java
Minecraft recently added a feature where the server "pauses" when no players are online for a while, which disables world and entity ticking until a player comes back. This sounds good in theory, but can really mess with what plugins may expect when no players are online, it may also cause some saving/loading issues, which is why it's for the best to add a warning about pausing in the plugin.
Read more about what paper said about it [here](https://forums.papermc.io/threads/1-21-3.1430/)
(This also had to be directed to dev/feature because dev/patch isnt updated to 1.21.3)
---
=> Add warning when pausing is enabled

src/main/java/ch/njol/skript/lang/Variable.java
This PR aims to fix the missing `changeInPlace` method implementation on Variable. For clarity, I have chosen to have both methods implemented, and the method with the unused parameter simply call the existing implementation.
---
=> Fix CIP implementation for Variable

src/main/java/ch/njol/skript/lang/SyntaxStringBuilder.java
Makes the SyntaxStringBuilder's append methods return itself.
Allows for stuff nicer feeling stuff like:
```java
String toString = new SyntaxStringBuilder(event, debug)
.append(x)
.append("and")
.append(y)
.toString()
```
---
=> Updates SyntaxStringBuilder to return itself

src/main/java/ch/njol/skript/sections/EffSecSpawn.java, src/main/java/ch/njol/skript/variables/Variables.java
Helper method to cut down on possible bugs when running an event with copied local variables.
Previous:
```
Variables.setLocalVariables(B, Variables.copyLocalVariables(A));
MY CODE HERE
Variables.setLocalVariables(A, Variables.copyLocalVariables(B));
Variables.removeLocals(B);
```
New:
```
Variables.withLocalVariables(A, B, () -> {
MY CODE HERE
});
```
---
=> Helper for running code with copied local variables

src/main/java/ch/njol/skript/entity/EntityData.java
Fixes async alias loading on 1.19.4's JUnit run.
**What went wrong**
While loading the aliases, SimpleEntityData's simple entities would be registered on the alias thread. This would then be registered into EntityData by registering `simple`. After this, parsing would start on the alias thread, specifically the (simple) entity `spectral arrow`. While this was happening, the code for registering non-simple EntityDatas would run, which modified the EntityData iterator while parsing of `spectral arrow` (or sometimes `arrow`) was ongoing, causing the exception. 
**Solution**
As the alias thread seems to only start parsing simple entities when it has completed, my solution is to avoid allowing modification of the iterator while looping. So far, this has not resulted in any problems. 
Before, …
=> Fix async alias loading on 1.19.4

src/test/skript/tests/syntaxes/effects/EffDetonate.sk
Moves detonations 100 blocks in the air to avoid messing with any other tests.
---
=> fix detonate test contamination

src/main/java/ch/njol/skript/expressions/ExprXOf.java, src/test/skript/tests/regressions/6817-null of x incorrect type.sk
This PR simply aims to resolve the issue where ExprXOf returns an improperly typed array when the `amount` expression evaluates to null. It is _not_ a goal to rewrite or improve the expression in any other way.
---
- https://github.com/SkriptLang/Skript/issues/6817
=> Fix Improperly Typed Array in ExprXOf

src/main/java/ch/njol/skript/SkriptConfig.java, src/main/java/org/skriptlang/skript/util/event/EventRegistry.java
This PR adds event support to SkriptConfig using the new event registry API. I added one event for when the config is reloaded, though it would be trivial to add other events should the need arise. I also made some minor changes to the EventRegistry implementation for thread-safety.
---
=> Add Reload Event for SkriptConfig

src/main/java/org/skriptlang/skript/bukkit/misc/expressions/ExprTextOf.java
This PR aims to fix an error with ExprTextOf when run on Spigot.
---
**Related Issues:** #7272
=> Fix ExprTextOf error on Spigot

src/main/java/ch/njol/skript/bukkitutil/sounds/SoundReceiver.java, src/main/java/ch/njol/skript/effects/EffPlaySound.java
This PR aims to fix an error when running Skript on Spigot when another plugin implements adventure API.
This issue was first brought to me by someone using Mohist, which I'm assuming implements adventure API but not fully.
---
**Related Issues:** #7261
=> SoundReceiver - fix error on Spigot when adventure API is implemented

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/events/EvtVehicleCollision.java, src/main/java/ch/njol/skript/events/SimpleEvents.java, src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtVehicleCollisionTest.java, src/test/skript/junit/EvtVehicleCollisionTest.sk
This PR aims to add additional Vehicle Events
---
=> Vehicle Events

src/main/java/ch/njol/skript/classes/EnumClassInfo.java, src/main/java/ch/njol/skript/classes/registry/RegistryClassInfo.java
This PR aims to add the option of registering a default comparator when creating a new EnumClassInfo and RegistryClassInfo
---
=> Optional Default Comparator

src/main/java/ch/njol/skript/SkriptCommand.java, src/main/java/ch/njol/skript/log/RedirectingLogHandler.java
This PR aims to fix an issue with double sending reload messages.
Reload in console:
Reload in game:
Reload in console:
Reload in game:
---
=> SkriptCommand - don't double send reload messages

build.gradle, src/main/java/ch/njol/skript/util/PotionEffectUtils.java
Suddenly, some transitive dependencies decided they would become incompatible this morning.
I excluded them from WorldEdit and Vault. This also made a potion class disappear, since it isn't present in 1.21 anymore, so I had to remove that too. I don't think anything used it, since it was deprecated in 2013, more than 11 years ago.
This should fix the build & test issues that appeared today.
---
=> Fix dependency incompatibility caused by Paper.

src/main/java/ch/njol/skript/aliases/Aliases.java
This PR aims to remove the Thread sleeping from modded aliases.
Skript loads aliases on another thread, so this sleep really doesn't have a benefit
---
=> Aliases - remove thread sleep

src/main/java/ch/njol/skript/entity/BoatData.java
Fixes a bug with boat data using `boat` or `any boat`.
Note to self: remember to merge patch into feature before release.
---
**Related Issues:** fixes #7300
=> Add boat data check to prevent error.

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
(edited)
`event-block` in event `BlockIgniteEvent` (`on ignite`) should return `getBlock()` instead of `getIgnitingBlock()`
issue occurred on:
- skript: 2.9.2
- engine:  paper-1.21.1-122
---
=> Fix BlockIgniteEvent 

src/main/java/ch/njol/skript/classes/registry/RegistryClassInfo.java
This PR aims to fix the comparator in RegistryClassInfo.
Paper recently did a change that broke `NamespacedKey == NamespacedKey`, luckily `.equals` works.
Due to this recent change, tests have all been failing.
---
=> RegistryClassInfo - fix comparator (Failing Tests)

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/util/Utils.java, src/main/java/ch/njol/skript/util/chat/ChatMessages.java, src/test/skript/tests/misc/unicode.sk
Adds unicode tag, which looks like `<u:00A7>` or `<unicode:00A7>`. Also updates the coloring code.
---
**Related Issues:** #4355
=> Add unicode tag

src/main/java/ch/njol/skript/expressions/ExprVillagerLevel.java, src/test/skript/tests/syntaxes/expressions/ExprVillagerLevel.sk
This PR aims to add villager experience to the villager level expression.
I forgot to do this when I did the Villager PR
---
=> ExprVillagerLevel -  add experience

src/main/java/ch/njol/skript/doc/DocumentationId.java, src/main/java/ch/njol/skript/doc/RequiredPlugins.java, src/main/java/ch/njol/skript/update/GithubChecker.java, src/main/java/ch/njol/util/Math2.java, src/main/java/ch/njol/util/NotifyingReference.java, src/main/java/ch/njol/util/SynchronizedReference.java, src/main/java/org/skriptlang/skript/bukkit/loottables/LootContextWrapper.java, src/test/skript/junit/-BellEventsPaper.sk, src/test/skript/junit/-BellEventsSpigot.sk, src/test/skript/junit/BellEvents.sk, src/test/skript/tests/regressions/4988-function uuid multiple parameters.sk, src/test/skript/tests/regressions/6288-event data priority pollution.sk, src/test/skript/tests/regressions/6290-item-inventory-conflict.sk, src/test/skript/tests/regressions/7279-create-uncreatable-inventory.sk, src/test/skript/tests/regressions/pull-6361-function-param.sk, src/test/skript/tests/syntaxes/conditions/CondIsOfType.sk, src/test/skript/tests/syntaxes/effects/EffDoIf.sk, src/test/skript/tests/syntaxes/effects/EffPvP.sk, src/test/skript/tests/syntaxes/expressions/ExprArithmetic.sk, src/test/skript/tests/syntaxes/expressions/ExprInventory.sk, src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk, src/test/skript/tests/syntaxes/sections/SecParse.sk, src/test/skript/tests/syntaxes/structures/StructParse.sk
Some pull requests over the years have introduced spaces rather than tabs in some lines, especially in test files (clearly the work of an enemy saboteur).
Usually, it's obvious when this happens because tabs are ninety metres wide on GitHub, and we spot them in review, but occasionally some slip through.
=> Use tabs consistently with all other files.

src/main/java/ch/njol/skript/classes/data/BukkitClasses.java, src/main/java/ch/njol/skript/classes/data/DefaultConverters.java, src/test/skript/tests/syntaxes/expressions/ExprEntitySnapshot.sk
This PR aims to give EntitySnapshots a string display rather than instance as well as retrieving the entity type of snapshot
---
=> EntitySnapshot ClassInfo Parser + Converter

src/main/java/ch/njol/skript/SkriptConfig.java, src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java, src/main/java/ch/njol/skript/bukkitutil/SoundUtils.java, src/main/java/ch/njol/skript/classes/SerializableGetter.java, src/main/java/ch/njol/skript/command/Commands.java, src/main/java/ch/njol/skript/effects/EffHidePlayerFromServerList.java, src/main/java/ch/njol/skript/entity/EntityData.java, src/main/java/ch/njol/skript/expressions/ExprAnvilRepairCost.java, src/main/java/ch/njol/skript/expressions/ExprAnvilText.java, src/main/java/ch/njol/skript/expressions/ExprColorOf.java, src/main/java/ch/njol/skript/expressions/ExprHoverList.java, src/main/java/ch/njol/skript/expressions/ExprMaxItemUseTime.java, src/main/java/ch/njol/skript/lang/SelfRegisteringSkriptEvent.java, src/main/java/ch/njol/skript/registrations/EventValues.java, src/main/java/ch/njol/skript/sections/EffSecShoot.java, src/main/java/ch/njol/skript/timings/SkriptTimings.java, src/main/java/ch/njol/skript/util/BlockStateBlock.java, src/main/java/ch/njol/skript/util/DelayedChangeBlock.java, src/main/java/ch/njol/skript/util/PotionDataUtils.java, src/main/java/ch/njol/skript/util/PotionEffectUtils.java, src/main/java/ch/njol/skript/util/Task.java, src/main/java/ch/njol/skript/util/visual/VisualEffects.java
There are about 70 warnings when you build Skript. Most of these are unavoidable: we need to use deprecated methods for cross-version compatibility.
Unfortunately, inline suppressions don't prevent them from being reported during build.
This makes it hard to spot when something's actually an issue, because it gets buried in all the other warnings.
I have manually silenced all of the (current) removal warnings, since we have no choice about using most of them.
A couple I could actually fix (there were actually ways around a few that were probably just missed at the time) and there were some warnings from our own deprecated classes being used (by us).
Maybe, but realistically we are ignoring the warnings anyway currently, and we only actually change stuff when a method stops working …
=> Silence unavoidable removal warnings during build & remove getters.

src/main/java/ch/njol/skript/util/chat/ChatMessages.java
Fixes code that was accidentally deleted in #6670. Oops!
---
=> Fix color chars not being registered

src/main/java/ch/njol/skript/doc/HTMLGenerator.java
Im really pushing my luck here....
This PR aims to fix new lines not working in doc descriptions:
---
=> HTMLGenerator - fix new lines not showing in docs

src/main/java/ch/njol/skript/Skript.java
Seems like tests are still intermittently failing due to the world not yet ticking.
This changes the test delay from 20 ticks to 50 ticks.
---
=> Increase test delay time.

src/main/java/org/skriptlang/skript/lang/script/ScriptWarning.java
Fix wrong unknown nullability on suppress warning enum
---
=> Fix wrong unknown nullability on suppress warning enum

src/main/java/org/skriptlang/skript/log/runtime/ErrorSource.java, src/main/resources/lang/english.lang
The error/warning lines were missing a newline at their ends, and syntaxes without a Name annotation were throwing exceptions.
Fallsback to the classname when no Name annotation is found.
I think not using syntaxinfos was a mistake that should be rectified, since things like Events or functions don't have docs annotations. That's for another PR, though.
---
=> Fix missing newline and handle syntaxes without documentation in Runtime Errors.

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/SkriptCommand.java, src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
This PR aims to fix the `/sk test` command yet again.
I recently realized the tab completion worked, but I was not able to actually test just one file/folder, it kept saying said file didnt exist.
I then looked over the code and realized I never actually passed the directory thru when looking for said script.
(its a mystery 🧐  how I never caught this before)
I had to add another method to allow passing the directory thru without breaking previous methods.
I also fixed an issue where the `/sk test/reload` commands both showed the same directories/files.
Now it will show the correct directories whether you're running reload or test.
---
=> SkriptCommand - fix test command again

src/main/java/ch/njol/skript/events/EvtCommand.java, src/test/skript/tests/syntaxes/structures/EvtCommand.sk
Allows the use of `on command "x" and "y"`.
Users were getting confused with `on command "x" or y"` varying in behavior due to which was selected during parsing.
The event now allows any number of commands and will trigger when any are detected.
I know this is not a bug, but I would like to treat it as if it were, since the previous behavior was confusing and not really intended. Let me know if you disagree.
---
=> Supports multiple commands in EvtCommand

src/main/java/ch/njol/skript/doc/DocumentationIdProvider.java
This PR aims to fix an issue in the docs where most elements had a "-2" appended in the link.
This was caused by a syntax info comparison that was failing.
Switched to comparing patterns instead.
(This made sure matching elements didn't increase the id)
---
**Related Issues:** #7367
=> DocumentationIdProvider - fix getId methods returning "2"

src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
This PR aims to fix an issue with some expressions (which check for enabled experiments) throwing errors in console when used in effect commands, due to no parser instance found.
The fix here is first checking if the parser instance is active before checking if a script has a feature.
---
**Related Issues:** #7397
=> ParserInstance - fix throwing errors in effect commands

src/main/java/ch/njol/skript/doc/HTMLGenerator.java
This PR aims to do yet another doc fix, I shall call it YADF.
Anyways, in my previous PR for the since annotation supporting multiple lines, pickle had made a code suggestion to change `<br>` to `<br/>`. 
I applied the code suggestion and didn't realize til after the PR was merged (and docs were created) that it did this:
(My fault for not testing... whoopsies)
(all on the same line, but no comma)
This PR fixes that issue by reverting that suggestion:
Might be my biggest PR to date 😂 
---
=> HTMLGenerator - fix new line in "since" not working

src/main/java/ch/njol/skript/ScriptLoader.java, src/main/java/ch/njol/skript/patterns/TypePatternElement.java, src/test/skript/tests/misc/expression sections.sk
This PR fixes the issue where, if a secspression's section contains errors, the first error is duplicated.
<details>
<summary>Error Screenshots</summary>
</details>
It turns out this issue was not related to secspressions (or Kenzie) at all! The issue was caused by a missing check in `TypePatternElement`. It was fine to omit this check previously, as it was assumed that if errors were logged during an Expression's parsing, the Expression would fail to init (and thus parsing would fail). However, with secspressions, it is possible for the Expression itself to parse/init properly, but a child element to error. As a result, both `printLog()` and `printError()` were called on the same LogHandler, causing the duplicated error. This can be simply resolved by checking whether the LogHandler is …
=> Fix Duplicate Secspression Logging

src/main/java/ch/njol/skript/ScriptLoader.java
This PR aims to fix an issue with ScriptLoader not catching Throwables which aren't Exceptions (ie: StackOverflowError)
I noticed this while doing a test in Dev mode. 
I made a booboo in SkBee here the toString of a condition was recursively calling itself. 
Unfortunately the test just halted, it wouldn't fail, it wouldn't throw a StackOverflowError
Exhibit A:
Then I moved onto a script to test (not a Test test, just running a script).
I had a similar issue.
Exhibits B and C:
The parser just halted. No error, no stack overflow, nothing.
After a lengthy talk with Pickle, he came to the idea that it had to do with the CompletableFutures, as they weren't catching anything.
There are a bunch of Try/Catches in the ScriptLoader, but they catch Exceptions not Throwables.
StackOverflowError …
=> ScriptLoader - fix error catching

.gitmodules, src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java, src/main/java/ch/njol/skript/registrations/EventValues.java
- Re-adds public Getter methods to EventValues to ensure backwards compatibility. 
- These have been deprecated for removal. 
- The returned Getters are just wrapping the returned Converter, visible in `#toGetter`.
- All method names have been updated as well, to accurately reflect that they return Converters now.
---
=> Re-add backwards-compatible Getter methods to EventValues

src/main/java/ch/njol/skript/Skript.java
Makes tests run when the first chunk can be retrieved in the world, ensuring the world is loaded before the tests run.
---
=> Fix tests running while world has not loaded

src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java
Adds a second pattern to ExprVectorFromYawAndPitch, so that users aren't restricted to `vector from yaw x and pitch z`, and can now also use `vector from pitch z and yaw x`
---
=> Adds second pattern to ExprVectorFromYawAndPitch

src/main/java/ch/njol/skript/Skript.java, src/main/java/ch/njol/skript/config/Config.java, src/main/java/ch/njol/skript/config/EntryNode.java, src/test/java/ch/njol/skript/config/ConfigTest.java, src/test/java/ch/njol/skript/config/NodeTest.java, src/test/resources/new-config.sk, src/test/resources/old-config.sk
- Actually make tests run, lol
- Fix entries being updated when only their comment is changed
- Disabling this will prevent unexpected changes to settings
- Fix duplicates appearing when adding a section
- Fix tests using wrong methods
---
=> Fix config sub-node duplication.

src/main/java/ch/njol/skript/classes/Converter.java, src/main/java/ch/njol/skript/registrations/Converters.java, src/main/java/ch/njol/skript/util/Utils.java
Despite the legacy converters class being scheduled for removal several years ago, some addons have not removed code depending on it.
As this class is (was) removed in 2.10, these addons will fail to load unless they are recompiled.
Many addons are unaffected by this, since the alternative has been around for a long time.
Since this issue seemed quite widespread (based on a GitHub all-repositories search),
I have added a temporary 'patch' to make these addons load, using a stub of the removed class. The stub will print a large warning if an outdated addon tries to use the class, and a large amount of its (unsupported) functionality is no longer available, but it does mean that most outdated addons, e.g. skript-gui, will still load.
These stubs have the maximum amount of compile-time …
=> Compatiblity patch for abandoned addons.

src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
Adds a missing check to see if the `currentEvents` field is set.
This fixes a problem in skript-reflect.
---
=> Add missing nullable check to `currentEvents`.

src/main/java/ch/njol/skript/expressions/ExprQueue.java, src/main/java/ch/njol/skript/registrations/Feature.java, src/main/java/ch/njol/skript/sections/SecFor.java, src/main/java/ch/njol/skript/sections/SecLoop.java, src/main/java/ch/njol/skript/structures/StructExample.java, src/main/java/org/skriptlang/skript/lang/util/SkriptQueue.java, src/main/resources/scripts/-examples/chest menus.sk, src/main/resources/scripts/-examples/commands.sk, src/main/resources/scripts/-examples/events.sk, src/main/resources/scripts/-examples/experimental features/for loops.sk, src/main/resources/scripts/-examples/experimental features/queues.sk, src/main/resources/scripts/-examples/experimental features/script reflection.sk, src/main/resources/scripts/-examples/functions.sk, src/main/resources/scripts/-examples/loops.sk, src/main/resources/scripts/-examples/options and meta.sk, src/main/resources/scripts/-examples/text formatting.sk, src/main/resources/scripts/-examples/timings.sk, src/main/resources/scripts/-examples/variables.sk, src/test/skript/tests/syntaxes/expressions/ExprQueue.sk, src/test/skript/tests/syntaxes/expressions/ExprScript.sk, src/test/skript/tests/syntaxes/structures/StructExample.sk
To help give testers some initiative, I've created some example scripts for `2.10`'s experimental features (queues, for each loops, script reflection).
I've also tweaked an issue I noticed with queues (namely, you couldn't loop them as a variable since they looked like a single value). I think this issue is probably more widespread (any containerised value) but that will need investigating later.
I added a new structure specifically for examples: `example`!
Code in this structure is parsed (so examples would still report parse errors) but the code is discarded and never run.
```applescript
example:
kill the player
teleport the player to {the moon}
```
This can be used to set up little code snippet examples, without needing to create some involved structure.
The existing example scripts …
=> Examples for the experimental features.

src/main/java/ch/njol/skript/classes/data/DefaultConverters.java, src/main/java/ch/njol/skript/expressions/ExprName.java, src/test/skript/tests/syntaxes/expressions/ExprName.sk
This PR aims to fix an issue with ExprName, and not being able to get/set the name of a block.
The issue as "inventories" was before "nameds", therefor forcing the Block to convert to an Inventory.
Reordering it solves that issue.
Also, had to update the BlockState to apply the name.
Added a test as well.
---
**Related Issues:** #7502
=> ExprName - fix not being able to get/set name of block

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java, src/main/java/org/skriptlang/skript/lang/util/SkriptQueue.java
Queues used an automatic serialiser, but the actual node fields in a linked list are transient (because it does it manually) so none of the values actually get stored.
This makes it just save the array of values instead.
---
=> Fix queue serialisation.

src/main/java/ch/njol/skript/effects/EffConnect.java, src/test/java/org/skriptlang/skript/test/tests/regression/EffSendEffConnectConflict7517Test.java
This PR fixes a possible conflict with the `send` effect and the `connect` effect having the same pattern `send x to y`, which causes the parser to pick the `connect` effect when both of those expressions have unknown types. This is fixed by making the `server` keyword required when using the `send` pattern in the `connect` effect
---
**Related Issues:** #7517
=> Fix a conflict with EffSend and EffConnect

src/main/java/ch/njol/skript/sections/SecFor.java, src/main/java/ch/njol/skript/sections/SecLoop.java, src/main/java/org/skriptlang/skript/lang/util/SkriptQueue.java, src/test/skript/tests/regressions/7536-for-loop-ending.sk, src/test/skript/tests/syntaxes/expressions/ExprQueue.sk, src/test/skript/tests/syntaxes/sections/SecFor.sk
Fixes an issue with subclasses of loop which couldn't call LoopSection's `setNext` because it was obscured by the overriding method.
This was causing triggers to terminate early (though I'm actually not sure why, it seems a bit dodgy, but this was definitely the cause). As a result, it was reporting as correct in the test system because the tests only measure for failures (and the assertions were just never being reached).
I also fixed a couple of other minor problems that had been _hidden_ by this, since their tests were getting skipped.
Fixes #7536
=> Fix loop behaviour from super call.

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/lang/parser/ParseStackOverflowException.java, src/main/java/ch/njol/skript/lang/parser/ParserInstance.java, src/main/java/ch/njol/skript/lang/parser/ParsingStack.java
Re-opening the abandoned #5277 with updated changes.
> This PR adds the parsing stack. This is a stack that keeps track of which syntax elements are currently being parsed.
With this feature, you could for example check in an expression's init method which expression it's being used in, or which effect is using the expression.
> Each stack element contains the `SyntaxElementInfo` (which contains info such as the syntax element class and the patterns), and which exact pattern was used.
> This PR also catches `StackOverflowError`s that occur during parsing, and adds the parsing stack to the exception message. AFAIK these exceptions are rare here, but the extra details don't hurt. Example stack trace (warning: long): https://pastebin.com/CNynV19h
> I also plan to add a watchdog system where …
=> Parsing stack (#5277)

src/main/java/ch/njol/skript/expressions/ExprExperienceCooldown.java, src/main/java/ch/njol/skript/expressions/ExprExperienceCooldownChangeReason.java
This PR removes redundant/duplicate "the"s from 2 elements. (It was me, and was before I knew `#register` added it by default)
😁 
---
=> Remove Redundant "The"s

src/main/java/ch/njol/skript/expressions/ExprNewBannerPattern.java
This pattern was responsible for significant slowdown in parsing due to its lack of required keywords.
Removing this pattern caused one test case of 3000 structures to go from a 4 minute parse time to a 1 minute parse time.
---
=> Removes no-keyword pattern from ExprNewBannerPattern

src/main/java/ch/njol/skript/conditions/CondIsWearing.java, src/test/java/org/skriptlang/skript/test/tests/regression/MissingCheckIfEntityCanUseSlot7524Test.java
This PR fixes a missing check whether an entity can use an equipment slot. For example, players cannot use the `body` equipment slot, causing an exception when using `CondIsWearing`. This was fixed by filtering the entities that can use the equipment slot inside the stream before calling `EntityEquipment#getItem(EquipmentSlot)`
---
**Related Issues:** #7524
=> Fix Invalid Equipment Slots in CondIsWearing

src/main/java/org/skriptlang/skript/bukkit/tags/elements/CondIsTagged.java, src/test/skript/tests/syntaxes/conditions/CondIsTagged.sk
Adds a check to ensure the value and the tag are actually valid to use with `isTagged()`. This is honestly a pretty awkward problem and I think the solution i have is reasonable, but not ideal. Better ideas welcome.
---
**Related Issues:** #7452
=> Fix cast exception when using invalid classes with CondIsTagged

src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
This PR aims to fix the date serialization issue on 2.10. Before 2.9, dates were serialized with the primitive field being represented as `timestamp` (the name of the old field). However, when serialization was updated in 2.10, the serializer was created using "time" as the Fields name, which is why old variables could not be deserialized.
I resolve this issue by changing the name _back_ to `timestamp` and adding a compatibility check for the `time` field name.
---
- https://github.com/SkriptLang/Skript/issues/7542
=> Fix Date Serialization

src/main/java/ch/njol/skript/classes/registry/RegistryParser.java
This PR aims to fix a tiny little bug with lang nodes in the RegistryParser.
What I noticed is if the lang file contains an entry that matches a custom entry, Skript attempts to use it, when it should only use `minecraft` namespaced entries.
Ex:
In the lang file under biomes, we have `desert_lakes` (Im assuming an old MC biome?!?!?)
When using a data pack that has `packname:desert_lakes` it grabs from the lang file.
This shouldn't happen.
We shouldn't be looking in the lang file for non-Minecraft entries.
The change I have implemented here was to only grab from the lang file if it's a minecraft namespaced object.
---
=> RegistryParser - fix pulling from the lang file on custom entries

src/main/java/org/skriptlang/skript/bukkit/loottables/LootTableModule.java
This PR adds a LootTable serializer.
---
=> Add a LootTable Serializer

src/main/java/org/skriptlang/skript/bukkit/fishing/elements/CondFishingLure.java, src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingApproachAngle.java, src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingBiteTime.java, src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingWaitTime.java
Fix examples for multiple fishing related syntaxes
---
=> Make examples use proper syntax

src/main/java/org/skriptlang/skript/bukkit/tags/elements/CondIsTagged.java, src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTag.java, src/test/skript/tests/regressions/7471-is tagged or list.sk
changes getArray to getAnd in CondIsTagged to fix #7471
adds runtime error to catch invalid tags in ExprTag
---
**Related Issues:** #7471
=> Fiix getArray mistake in CondIsTagged, add runtime error for bad namespace keys in ExprTag

src/main/java/org/skriptlang/skript/bukkit/log/runtime/BukkitRuntimeErrorConsumer.java, src/main/java/org/skriptlang/skript/log/runtime/RuntimeError.java
Treats the highlight text as a regex pattern to allow more flexible highlighting in errors.
---
**Related Issues:** #7446
=> Enable regex based highlighting for runtime errors

src/main/java/ch/njol/skript/expressions/ExprCompassTarget.java
This PR aims to update docs for the compass target expression.
As of Minecraft 1.21.4, the compass has been changed to no longer point to spawn of dimensions other than the vanilla overworld dimension.
This is now handled by the resource pack and can be modified in the pack.
---
=> ExprCompassTarget - update docs

src/main/java/org/skriptlang/skript/bukkit/displays/text/ExprTextDisplayAlignment.java
Fixes the incorrect example in text display alignment docs.
---
**Related Issues:** #7587
=> Fix Text Display Alignment Example

src/main/java/ch/njol/skript/classes/data/DefaultOperations.java, src/test/skript/tests/regressions/7645-floating point timespan math.sk
Does as much math in doubles as possible before clamping to long when creating the timespan.
---
**Related Issues:** #7645
=> Fix Truncation in Timespan Tabulation

src/main/java/ch/njol/skript/entity/EntityData.java, src/main/java/ch/njol/skript/entity/SimpleEntityData.java, src/main/java/org/skriptlang/skript/bukkit/displays/text/ExprTextDisplayAlignment.java, src/test/skript/tests/misc/sub entity datas.sk, src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
This PR aims to:
- Fix #7491 allowing users to detect if a projectile is a wind charge or wither skull
- Future proofing for any other entities that extend another entity
- Adds tests for entities extending another entity, such as: small fireball, large fireball, dragon fireball, wind charge and wither skull
- Adds fireball, wind charge and wither skull to the all entities test within `EffSecSpawn.sk`
---
**Related Issues:** #7491
=> Sub Entity Data Fix

CLOCKWORK_RELEASE_MODEL.md
As discussed during the 2.11 planning meeting, the current release model has two major flaws.
1) Mojang's shift to more frequent, smaller updates means Skript has significant lag time between features being available in Minecraft and Skript supporting them. 
2) The recent uptick in contributions meant that 2.10 was large enough to suffer from some of the same problems that 2.7 did. To keep update sizes smaller, 4 major updates a year will spread out the changes more evenly.
Note that April and October updates are not meant for major breaking changes, which should be saved for January and July.
---
=> Update release model to 4 feature releases a year.

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/doc/JSONGenerator.java, src/main/java/ch/njol/skript/expressions/ExprEntity.java, src/main/java/ch/njol/skript/registrations/EventValues.java, src/test/skript/tests/misc/EventValues.sk, src/test/skript/tests/syntaxes/effects/EffDetonate.sk
This PR aims to fix and update Event Values. (dev/patch branch)
- For the `PlayerDropItemEvent` and `PlayerPickupItemEvent` using `event-entity` was throwing a parse error of `multiple entities` which should not be the case. The easy solution to this was to register an `Entity` value directly to these classes. Though in their corresponding `SkriptEvent`s they are paired with their `Entity` counterparts, inside `EventValueExpression#init` only the Player event was being accessed.
- Adds the `#setTime` into `ExprEntity` which utilizes `EventValueExpression#setTime` allowing past and future `event-%entitydata%` resulting in the fix of not being able to grab the `future event-entity` in `ItemMergeEvent`
- Adds a new method within `EventValues`, `#stripConverters`
```
/*
In this method we can …
```
=> Event Values Fix

src/main/java/ch/njol/skript/effects/EffSort.java
Makes sure the mapping expression only returns a single value, rather than simply assuming it.
---
=> Adds an isSingle check to EffSort's mapping expression

src/main/java/ch/njol/skript/expressions/ExprAngle.java, src/test/skript/tests/regressions/7717-expr angle array store.sk
Fixes an ArrayStoreException in ExprArray when integers are input. The array from getArray can be a Integer[] array and does not accept Doubles. (the ide doesn't catch this because the variable is a Number[] array).
---
=> Fix array store exception in ExprAngle

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java, src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
EquipmentSlot was being called with an null value for equipment/slot, which resulted in NPE. This reinstates the null check and annotates the inputs as NotNull, so this can be caught more easily in the future.
---
=> Enforce NotNull on EquipmentSlot constructors.

src/main/java/ch/njol/skript/conditions/CondIsCharging.java, src/main/java/ch/njol/skript/conditions/CondIsChargingFireball.java, src/main/java/ch/njol/skript/expressions/ExprExplosiveYield.java, src/test/skript/tests/syntaxes/expressions/ExprExplosiveYield.sk
This PR aims to add support for Ghasts allowing users to check if a ghast is charging for a fireball and get+set the explosive power of ghasts.
---
=> Ghast Support

build.gradle
s01.oss.sonatype.org seems to be responding with 503s, while the main sonatype website and repo seems to be fine. It also appears that we do not need this repo, as the adventure text serializer is obtainable without it. This PR removes the repo to fix the tests failing from 503 responses.
---
=> Remove s01 sonatype maven repository

src/main/java/ch/njol/skript/lang/SkriptParser.java
Forces the parser to check the plurality of a function before returning it as a valid expression for a given exprInfo.
Also updates the other errors related to plural/single values that weren't being printed and were poorly written.
Before:
Note that the matched pattern only accepts a single number, but since the implementation uses getArray, no issue occurs.
This causes exceptions when used with implementations that use getSingle().
After:
---
=> Fix non-single functions being parsed for single-only expression infos

src/main/java/ch/njol/skript/events/EvtMove.java
`on entity move` did not previously trigger for players due to a bug in how the different move events were handled.
---
=> Include player as entity in on entity move

src/main/java/ch/njol/skript/conditions/CondIsEating.java, src/main/java/ch/njol/skript/conditions/CondPandaIsOnBack.java, src/main/java/ch/njol/skript/conditions/CondPandaIsRolling.java, src/main/java/ch/njol/skript/conditions/CondPandaIsScared.java, src/main/java/ch/njol/skript/conditions/CondPandaIsSneezing.java, src/main/java/ch/njol/skript/effects/EffEating.java, src/main/java/ch/njol/skript/effects/EffPandaOnBack.java, src/main/java/ch/njol/skript/effects/EffPandaRolling.java, src/main/java/ch/njol/skript/effects/EffPandaSneezing.java, src/main/java/ch/njol/skript/expressions/ExprPandaGene.java, src/test/skript/tests/syntaxes/effects/EffEating.sk, src/test/skript/tests/syntaxes/effects/EffPandaOnBack.sk, src/test/skript/tests/syntaxes/effects/EffPandaRolling.sk, src/test/skript/tests/syntaxes/effects/EffPandaSneezing.sk, src/test/skript/tests/syntaxes/expressions/ExprPandaGene.sk
This PR aims to add panda support by:
- Check if a panda is eating, with an effect (including horse types)
- Check if a panda is rolling, with an effect
- Check if a panda is scared
- Check if a panda is sneezing, with an effect
- Check if a panda is on its back, with an effect
- Expression for the main and hidden genes of a panda, with a changer
---
=> Panda Support

src/main/java/ch/njol/skript/aliases/ItemType.java
BlockStateMeta information is not copied to the placed block when settting blocks based on ItemTypes. 
I could not find any general method to do this, though BlockState#copy(Location) is experimental, so it may be viable in the future. For now, I resorted to manually copying inventory information over for Container BlockStates.
---
**Related Issues:** #7735
=> Copy item inventories when setting blocks.

src/main/java/ch/njol/skript/lang/Statement.java
The sectioncontext was not being cleared when attempting to parse sectionless statements, which resulted in sectionless Secspressions being given their parent section to claim, leading to shenanigans like the secspression parsing itself multiple times.
This ensures the section context is cleared before attempting to parse sectionless statements.
---
**Related Issues:** #7721
=> Fix double-claiming behavior with Secspressions that have no section.

src/main/java/ch/njol/skript/events/EvtPlayerArmorChange.java
References to the SlotType enum in switch statements forced the enum to be loaded on Spigot servers, causing an error.
This switches to a map and Enum.valueOf to prevent loading SlotType unless needed.
Also cleans up some logic in the class.
---
**Related Issues:** #7771
=> Fixes armor change NoClassDefFound error on Spigot 

src/main/resources/lang/default.lang
Adds lang entries for 1.21.4+ bundle inventory actions ~~(These actions appear to be unused as of Paper 1.21.4-222)~~.
Adds entry for `bucket` spawn reason. Due to conflicts, I chose `release from bucket` as the full entry. Suggestions welcome.
---
**Related Issues:** #7772
=> Adds missing lang entries for bundle inventory actions and bucket spawn reason

src/main/java/org/skriptlang/skript/bukkit/displays/generic/ExprDisplayTeleportDuration.java
The name and example used to use teleport delay even though syntax is teleport duration. I replaced the delay with duration but could also go the other way and add delay as a valid pattern.
---
**Target Minecraft Versions:** 1.20.4 
**Related Issues:** #7732
=> Update name and example of ExprDisplayTeleportDuration to match syntax

src/main/java/ch/njol/skript/util/BlockLineIterator.java, src/test/skript/tests/regressions/7768-block line iterator overshoot.sk
Changes overshoot check to ensure it's significantly behind the end point (1+ meter) instead of behind at all.
---
**Related Issues:** #7768
=> Fix BlockLineIterator error due to floating point error near edges of blocks.

src/main/java/ch/njol/skript/lang/EventRestrictedSyntax.java, src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/skript/tests/misc/supported events.sk
=> Make ERS use names of events instead of class names 

src/main/java/ch/njol/skript/aliases/ItemData.java
Material ordinals change between versions and cannot be relied upon for serialization.
This uses getKey to serialize and matchMaterial to deserialize.
We should recommend users upgrade to 2.11 without changing their minecraft version and run the server at least once before changing versions.
---
**Related Issues:** #7789
=> Use NamespacedKeys instead of Material ordinals for ItemData serialization

src/main/java/ch/njol/skript/ScriptLoader.java, src/test/skript/tests/misc/expression sections.sk
Failed SE parses would have their errors overwritten by the errors from a previous Section parse. 
This was likely to avoid errors like:
However, this meant that all errors produced intentionally by SectionExpressions would never see the light of day.
This PR reverses that policy by only overwriting the "Can't understand this condition/effect" error:
---
**Related Issues:** #7792
=> Fix SectionExpression errors not appearing in the final log.

src/main/java/org/skriptlang/skript/lang/entry/ContainerEntryData.java
This PR aims to expose the entry validator within container entry data, main goal of this decision was to offer documentation sites easier access to this without further reflection than already needed.
---
**Related Issues:** #7783
=> Expose EntryValidator within ContainerEntryData 😊

src/main/java/ch/njol/skript/expressions/ExprWithItemFlags.java
This PR aims to add a since value for "all item flags" onto the `ExprWithItemFlags` class, I've applied 2.11 since it was merged in this release. The decision to change this was to prevent further confusion between users on older versions
---
=> Add since tag onto ExprWithItemFlags for "all itemflags"

src/main/java/ch/njol/skript/expressions/ExprAnyOf.java
Switches to returning null to avoid assertion errors when trying to add/remove/set ExprAnyOf.
I believe the issue breaks testing for some addons that use skript-test-action
---
=> ExprAnyOf's acceptChange returning an empty array instead of null.

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Removes event-inventory from `InventoryOpenEvent` and `InventoryCloseEvent` and adds it to `InventoryEvent`
---
**Related Issues:** #7820
=> Add event-inventory to InventoryEvent

src/main/java/ch/njol/skript/util/BlockStateBlock.java, src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
There's a new isSuffocating method in 1.21.5 that BSB and DCB do not currently implement, causing builds to fail.
This implements it on both classes.
---
=> Add missing suffocation method for Block implementations.

src/main/java/ch/njol/skript/variables/FlatFileStorage.java
The CSV parsing regex is extraordinarily slow at matching quoted variable names, to the point it causes StackOverflows that prevent variables from being loaded at all. This is due to the regex matching checking for "", then matching "" or a single character, and repeat for the next character, until it recurses too far. This PR fixes that by allowing the matching of multiple non-" characters between each "" check.
---
=> Fix StackOverflow in variable parsing

src/main/java/ch/njol/skript/effects/EffBroadcast.java, src/main/java/ch/njol/skript/lang/VariableString.java, src/test/skript/tests/regressions/7718-broadcast evaluates vstrings twice.sk
Adds a StringBuilder parameter to VariableString.getMessageContents in order to allow capture of both the components and the unformatted string version without having to evaluate any expressions twice.
---
**Related Issues:** #7718
=> Fix double evaluation when using VariableStrings with EffBroadcast.

src/main/java/ch/njol/skript/sections/EffSecShoot.java, src/test/skript/tests/syntaxes/sections/EffSecShoot.sk
This PR aims to fix `EffSecShoot`:
- When using a section, the shot/spawned entity data did not have the velocity set.  Due to the consumers not setting the velocity.
- 1.20.1- `World#spawn` with Consumer used Bukkit consumers
Adds tests for each `CaseUsage` via spawning a fireball, projectile, and an entity, from both a living entity shooter and a location shooter, matching the velocities.
---
**Related Issues:** #7824
=> EffSecShoot Fix Sections/Consumers

src/main/resources/lang/default.lang
This PR aims to fix some of the `types` within `default.lang` that had `a`  instead of `an`.
---
=> Lang Types An Fix

src/main/java/ch/njol/skript/effects/EffExit.java
EffExit currently uses the StopSections intent even for `stop trigger`. While stopping *all* sections is technically correct, it is more accurate (and useful) to use the StopTrigger intent.
Simply checks `outerSection == null` (true only for `stop trigger`) and returns the appropriate intent.
No additional tests are needed/applicable.
I planned to use ExecutionIntent in supporting local variable type hints. I ran into this issue.
---
=> Use StopTrigger ExecutionIntent in EffExit when applicable

src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java, src/test/skript/tests/syntaxes/expressions/ExprNoDamageTicks.sk
ExprNoDamageTicks is deprecated, but it does not print a "proper" deprecation warning. Thus, it is not affected by suppressing those warnings. It also spams the tests a lot.
I switched to the proper method from ScriptWarning. The warning itself remains the same.
I did suppress the warning for the existing test script and confirmed that it is no longer printed.
n/a
---
=> Use proper deprecation warning for ExprNoDamageTicks

src/main/java/ch/njol/skript/events/EvtClick.java
If you use the `on right click on %blockdata%` pattern and click on an entity, it always assumes the object is either an entity or an item type, but not block data, which can cause the server to crash.
Moved the blockdata check a bit earlier to fix the issue and added an `instanceof ItemType` check to prevent possible crashes in the future.
Tested `on right click on pig`, `on right click on stone`, `on right click on stone_button[]` and `on right click on stone_button[powered=false]` to ensure nothing was broken with this fix.
---
**Completes:** #7885 
=> Properly Handle Blockdata in Click Event

src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Skript did not have an event value to grab the entity type (EntityData) of an entity for `EntityEvent`
Registers a new event value for `EntityEvent` to get the entity type (EntityData) with event restrictions.
```applescript
on spawn:
broadcast event-entity type
```
N/A
---
**Completes:** #7818 
=> EntityData Event Value

src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
Elements that extend `PropertyCondition` and override `toString` needed  to override `init` to be able to get the expression for the  `toString`
Adds `#getExpr` removing the need for overriding `init` to gain access to the expression.
N/A
N/A
---
=> PropertyCondition#getExpr

src/main/java/ch/njol/skript/effects/EffWorldBorderExpand.java
The old examples did not use the proper syntax (see #7920), this fixes that.
=> Fixes examples of worldborder expand/shrink effect

.github/workflows/update-gradle-wrapper.yml, src/main/java/ch/njol/skript/classes/data/JavaClasses.java, src/test/skript/tests/misc/scientific notation.sk
Scientific notation is a way of easily representing large numbers, such as `1.23e+9` representing `1 230 000 000`. Most major languages have support for representing numbers like this, but Skript doesn't :(
Updates the existing regex for integer and rational numbers to include allowing the use of the format `X[eE][+-]Y`. No implementation changes were necessary, as the existing methods allow this change to pass the tests.
`scientific notation.sk` test added, manually confirmed to be working.
---
**Completes:** #4553 
=> Scientific notation

src/main/java/ch/njol/skript/effects/EffChange.java, src/main/java/ch/njol/skript/lang/Expression.java
EffChange is outdated: filled with oddly structured code, duplicated behavior, and confusing variable names. It is hard to understand what is going on in the class and follow the behavior.
I have cleaned up and rewritten the class. I've expanded variable names, added documentation, optimized behavior, and improved error messages.
No additional tests were added. EffChange is widely used across the tests, and they continue to pass. I am not sure if it is worth adding an EffChange test (it would depend on other syntaxes change implementations).
Sort of depends on https://github.com/SkriptLang/Skript/pull/7891 (I've copied the `Expression#canReturn` changes)
---
=> EffChange Cleanup

src/main/java/ch/njol/skript/conditions/CondIsDivisibleBy.java, src/test/skript/tests/syntaxes/conditions/CondIsDivisibleBy.sk
The divisible by expression is particularly susceptible to floating point error compounding during the modulo operation. This means many common divisions like `0.3/0.1` return false when they should be true, due to slightly fp inaccuracies.
I may have gone a bit overboard. Nearly all reasonable cases can be fixed with a check against Skript.EPSILON, which ensures the result is within 1e-10 of evenly divisible. However, this fails when working with large or small numbers, or a combination of the two. For example, 3,000,000 / (1/3) fails as the error is slightly larger than 1e-10. 
Using ULP is sadly not helpful here, since the ulp for 3 million is 0.25 (way too large) and for 1/3 it is roughly 1e-17 (way too small). A fixed epsilon also fails if the user wants to work with small numbers, …
=> Add tolerance to divisible by condition

src/main/java/ch/njol/skript/expressions/ExprTarget.java
ExprTarget had an incorrect and insufficient description, as well as a pattern that didn't allow the grammatically correct `with a ray size of 5`.
Tweaks the pattern to add `a` and `of` to the ray size section and re-writes the part of the description mentioning displays to properly describe how ray size works.
None.
---
=> Tweak the pattern and description of ExprTarget

build.gradle, gradle.properties, src/main/resources/lang/default.lang, src/test/skript/environments/java21/paper-1.21.6.json
N/A
Updates `build.gradle` and `gradle.properties` by changing `1.21.5` -> `1.21.6`
Adds `paper-1.21.6.json` for the testing environment
Updates `default.lang` for new entries in enums/registries
N/A
N/A
---
=> Paper 1.21.6 Update

src/main/java/ch/njol/skript/structures/StructVariables.java, src/main/java/ch/njol/skript/test/runner/StructParse.java
#7963 Variables were attempting to be set asynchronously when using the async script loader setting.
Changes StructParse and StructVariables to enforce using the main thread when changing variables.
Manual testing with the existing test scripts and the async loader enabled.
This is very much a bandaid and not a comprehensive fix of async loading. There are no doubt many more issues with it.
---
**Completes:** #7963 
=> Enforce main thread when changing variables during structure loading

src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java, src/main/java/org/skriptlang/skript/lang/arithmetic/Arithmetics.java, src/test/skript/tests/syntaxes/expressions/ExprArithmetic.sk
Currently, ExprArithmetic does not properly consider Converters (Converted Arithmetic Infos) when determining return types along with UnparsedLiteral resolutions. This led to some unexpected test failures when working on https://github.com/SkriptLang/Skript/pull/7892
I added two new methods, `lookupLeftOperations` and `lookupRightOperations` for performing OperationInfo lookups (with converters) when only partial information is available. I used `lookup` as that method seems to be used when Converters are considered, whereas `get` is for exact looksup.
I have added a test case in `ExprArithmetic.sk` that tests the behavior against Experience. Here's what goes wrong currently:
When parsing for the line starts, the Operation information is `Experience + UnparsedLiteral (Object)`. When …
=> Fix ExprArithmetic Type Resolutions

src/main/java/ch/njol/skript/variables/FlatFileStorage.java, src/main/java/ch/njol/skript/variables/Variables.java
FFS has a special save method that just pulls all variables and saves them on shutdown, bypassing the normal methods of variable saving. This is poor design but fixing it is out of scope for this pr.
Adds checks for ephemeral vars in the FFS save treemap method.
Manual testing
---
**Completes:** #8004 
=> Prevent FFS from saving ephemeral vars on shutdown

src/main/java/ch/njol/skript/lang/Expression.java
Addons that directly implement Expression had to be recompiled since `simplify()` moved from Expression to the Simplifiable interface.  
Providing a default implementation of simplify() removes the need to recompile.
Developers should keep in mind that implementing simplify is still highly recommended if possible, since leaving it to the default impl means no simplification can be done.
---
**Completes:**  https://github.com/SkriptLang/skript-reflect/issues/141 
=> Implement default simplify() on Expression

src/main/java/ch/njol/skript/doc/HTMLGenerator.java
When using the `@Example` annotation, text blocks (multiline strings) are not properly formatted:
This PR rewrites how the combined examples string is formatted. The existing `replace` calls were not working correctly nor do they appear to be necessary. I removed them. Tabs are already handled later on in the code, and replacing them with spaces would not actually work (would need to be nbsp)
Additionally, an extra blank line is inserted between different `@Example`s for clarity on the docs.
I manually generated the docs and confirmed the issue was resolved:
---
**Completes:** #7813
=> Fix Docs Example Formatting

src/main/java/ch/njol/skript/expressions/ExprValueWithin.java
#7879 changed the load priority for many syntaxes and caused an undesired change in parsing around ExprBlocks.
`size of blocks within x and y` would be parsed as `size of (blocks within x) and (y)` instead of `size of (blocks within x and y)`.
Changes ExprValueWithin's priority to PROPERTY from COMBINED to give other syntaxes priority over it.
manual testing completed. Couldn't get a regression test replicating the issue for some reason, maybe due to the use of `player` being important.
---
=> move ExprValueWithin to PROPERTY priority

src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java, src/main/java/ch/njol/skript/lang/function/Functions.java, src/test/java/ch/njol/skript/lang/function/FunctionRegistryTest.java
**Bug explanation**
When removing functions from the FunctionRegistry, the `remove` method would attempt to get the namespace of the function being removed. To do this, it uses the script of the signature of the function. Functions registered in Java have no script, but functions registered in Skript do. 
Therefore, if a function was previously registered and unregistered, it would leave an empty namespace in the `namespaces` map. The old `remove` logic would then incorrectly assume that this is the namespace of the function being removed, since the Skript-based function has a non-null script, and then not do anything.
Since all unit tests are made using Java, remove would work fine for Java functions, as the namespace is always null. 
**Scope enforcement**
Also changes the register …
=> Fix bad FunctionRegistry#remove logic

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/skript/tests/regressions/7861-overzealous literal type specification.sk
Literal type specification was exiting parsing early if it failed instead of allowing later stages to try. #7861 
Stops the code from exiting early if literal type specification fails to parse. Only returns if it succeeded. Added an extra error about bad classinfo for more helpful error messages.
Added regression test.
---
**Completes:** #7861 
=> Fix overzealous literal type spec. parsing

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java, src/main/java/ch/njol/skript/lang/function/FunctionReference.java, src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java, src/main/java/ch/njol/skript/lang/function/Functions.java, src/test/java/ch/njol/skript/lang/function/FunctionRegistryTest.java, src/test/skript/tests/misc/function overloading.sk, src/test/skript/tests/syntaxes/structures/StructFunction.sk
1. Fixes overloading for functions with no parameters. Previously, passing no parameters to `getFunction` or `getSignature` would match any function with the specified name. Now, passing no parameters will only match functions that also have no parameters.
2. Fixes overloading for functions with array parameters. Previously, if a function had an array as parameters, any function with the same name of the function would be matched. This would not allow for two version of, for example, `clamp` to exist. Now, instead of matching any function with the same name, the arguments are actually checked 
3. Removes outdated documentation for FunctionIdentifier (fixes #8031)
4. Adds more detailed error messages to the "function already exists" error (fixes #8030)
1. Updates `candidates` to avoid …
=> Function overloading fixes and improvements

src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java, src/test/skript/tests/regressions/8070-single list parameter functions can fail to resolve.sk
Function calls for single list parameter functions could fail to resolve. Consider the example:
```applescript
function test(p: potion effect types):
stop
on load:
test(night vision and glowing)
```
The function registry should be able to resolve this, but it fails to do so. However, this does not occur with all types. After some investigation, I found that the `converterExists` check for resolving these single list parameter functions had the parameters mistakenly swapped.
I swapped the parameters which resolved the issue.
I have included a regression test.
---
**Completes:** #8070 
=> Fix potential resolution failure with single list parameter function calls

src/main/java/ch/njol/skript/lang/Statement.java
When parsing a statement, if it contained a section expression, and that section expression successfully parsed and claimed a section (but the statement itself failed in init), the claim on the section would not be released. As a result, any future attempts to parse a section expression would fail as it believed the section to already be claimed.
When a section expression may be parsed, the Statement iterator is wrapped such that the "owner" of the section context is cleared when the next element of the iterator is returned.
tested in game using a combination of addons that exposed the issue. testing is a bit complex as it would require usage of priorities which isn't currently possible with test syntax. if it is really wanted i can probably make it happen
---
**Completes:** none …
=> Fix expression section claim releasing

src/main/java/ch/njol/skript/effects/EffEquip.java, src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java, src/test/skript/tests/regressions/8086-happy ghast equipment.sk
Could not use `EffEquip` nor `ExprArmorSlot` to set/clear/equip/unequip the body slot of a  HappyGhast -  Harness
Updates `EffEquip` and `ExprArmorSlot` to allow `HappyGhast`s
`8086-happy ghast equipment.sk`
N/A
---
**Completes:** #8084 
=> Happy Ghast Equipment

src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java, src/test/skript/tests/regressions/8085-rounding nan.sk
#8085 showed using NaN can cause issues with the round function.
I've added checks for non-finite inputs and return either the value if the value was non-finite, or NaN if the placement was too large for BigInt to handle.
Added a regression test.
---
**Completes:** #8085 
=> catch rounding edge cases

src/main/java/org/skriptlang/skript/registration/SyntaxRegister.java
https://github.com/SkriptLang/Skript/pull/7879 changed syntax ordering so that it was no longer dependent on when the syntax was registered. However, most syntax is not using Priority yet, meaning more complex syntax (i.e. harder to parse) such as EffVisualEffect is being attempted early on in some cases (when it should instead be saved for last).
While these more complex syntaxes should have a higher priority, I have created a simple metric for determining the "complexity" of a syntax. Currently, the metric simply considers how many percent signs a pattern contains (they have not yet been compiled and i didn't think it was worth doing that). The idea is that `percent signs = expressions` and `more expressions = more complex` (harder to parse) which is generally true
n/a
--- …
=> Improve default syntax ordering

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/skript/tests/misc/literal specification.sk
Literal specification didn't work so well in function parameters: `func(red, black (color))` would fail to parse.
Enforces stricter regex match rules (no {}()\"' and so on in the literal, and only letters, numbers, and spaces in the codename).
Also ensures the two parseSingleExpr implementations are unified in behavior, as previously only one would attempt specified literals. Pulled duplicate code into a helper method.
added to literal specification.sk
---
=> Limit literal specification regex pattern to improve matching behavior.

src/main/java/ch/njol/skript/expressions/ExprLoopValue.java, src/test/skript/tests/regressions/8108-exprloopvalue losing converter info.sk
In specific cases, `loop-value` failed to convert to the expected type due to a loss of converter info that lead to simplification ultimately determining that it only needed an Object -> Object converter, which is effectively `return this`. This lead to issues like #8108 where the name of loop-value could not be determined due to an ItemStack being returned, which is not AnyNamed, rather than the ItemStack being converted to AnyNamed via ItemType.
The problem stemmed from ExprLoopValue#getConvertedExpression, which had a special implementation that at one point was probably useful? It effectively just made a dynamic converter using Converters.convert to attempt each possible to type in order. 
Sharp-eyed viewers may note this as being what ConvertedExpression#newInstance does during init, …
=> Fix loss of converter info with ExprLoopValue

src/main/java/ch/njol/skript/effects/EffFireResistant.java
This PR fixes a small documentation issue by removing an extra colon 
from the "Make Fire Resistant" example in EffFireResistant.java.
- Removed extra colon from the example:
```diff
- make player's tool fire resistant:
+ make player's tool fire resistant
=> Remove extra colon from fire resistant documentation example

src/main/java/ch/njol/skript/util/Direction.java
If your syntax has nullable expressions `[%-direction% %-location%]` and used directly `expression = Direction.combine((Expression<Direction>) exprs[0], (Expression<Location>) exprs[1]);` it'll throw a null pointer on use.
Rather than having to check if both expressions are null before calling the combine method, you can now properly do the single line call, and the returned expression will be the expected null if the syntax was wanting the expression to be null if not present.
---
=> Fix nullable direction combine

src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java
Previously, EntryDataExpression used T as the generic parameter for both the default value and the return types, this causes generics issues and didn't allow sub types to be used
Allow sub types.
---
**Completes:** none that i'm aware of
**Related:** none that i'm aware of
=> Allowed Sub Types in EntryDataExpression

src/main/java/ch/njol/skript/lang/Section.java
Testing in the addon development channel has revealed an issue when attempting to manually parse expressions, often as parts of sections or structures. The core issue is the inability for an addon to update SectionContext and tell the parser what section it's parsing. This manifests in different ways depending on the use case. In SkCheese, an infinite parsing loop can be created with the `new string` expression section where not updating the SectionNode in SectionContext leads to the same Node being parsed again and again, but always being given its parent node in init(). In Oopsk, it can manifest where a field in a struct instance section containing a section expression claims its parent section leading to a double-claim. In Jake's unreleased packet addon, it leads to a strange error …
=> Expose SectionContext

src/main/java/ch/njol/skript/lang/ExpressionList.java
During the implementation of type properties, I had some issues with determining the possible return types of a converted ExpressionList. If I converted `me and {tool}` to Player and ItemType, it would give me a EL with the possibleReturnTypes of Player and Object. In getConvertedExpression, it was taking `getReturnType` of the component expressions and using that for possible return types, rather than asking for `possibleReturnTypes` to get the most accurate information.
The solution was to add all the possibleReturnTypes from the elements into a set and use that as the list's possible return types. This avoids unnecessary supertypes and gives the most accurate information.
Manual confirmation. This will be tested further once type properties is implemented.
---
**Completes:** none …
=> Ensure ExpressionList#possibleReturnTypes is accurate after getConvertedExpression

src/main/java/ch/njol/skript/Skript.java
The `expressionType` parameter is misnamed. While other register methods use `conditionClass`, this method uses `expressionType`, which can be mistaken with the `ExpressionType` class
Renamed the parameter to match other register methods
-
---
=> Change registerExpression() parameter name

src/main/java/ch/njol/skript/lang/SkriptParser.java, src/test/skript/tests/regressions/8187-functions behave wrong with all default args.sk
When attempting to parse function arguments, SkriptParser uses a "shortcut" to determine whether parsing the input as a single expression is necessary. Those cases were determined to be:
- The function has only 1 parameter
- The function has only 1 required parameter (e.g. all others have default values)
However, I failed to consider the case that a function might have 0 required parameters. For a function like that, with multiple parameters that are all optional, the case where that function is called with only one argument could not be parsed properly.
This is a single-character fix so that single expression parsing is also attempted for functions with 0 minimum arguments.
I have implemented a regression test for this behavior. I confirmed that it failed before the fix (with the same …
=> Fix type-aware function parsing for functions with only optional arguments

src/main/java/ch/njol/skript/entity/EntityData.java, src/main/java/ch/njol/skript/entity/MinecartData.java
`minecart` maps to the Minecart.class which is an interface... You can't spawn an interface.
Update the MinecartData class with proper handling of the different Minecart classes.
I also moved the `WORLD_1_17_CONSUMER` outside the try catch, because it doesn't need to be doing a try catch every time an entity is spawned.
All of these would fail prior to this pull request aside from the spawning of a storage minecart:
```vb
spawn a minecart at player # spawns RidableMinecart
if last spawned minecart is a storage minecart: #false
if last spawned minecart is a minecart: #true
if last spawned minecart is a regular minecart: #true
spawn a storage minecart at player # spawns StorageMinecart
if last spawned minecart is a storage minecart: #true
if last spawned minecart is a minecart: #true
if …
```
=> Fixes and update Minecarts

src/main/java/ch/njol/skript/doc/Documentation.java, src/main/java/ch/njol/skript/doc/DocumentationIdProvider.java, src/main/java/ch/njol/skript/doc/HTMLGenerator.java, src/main/java/ch/njol/skript/doc/JSONGenerator.java, src/main/java/ch/njol/skript/lang/function/Functions.java
Fix `Functions#getJavaFunctions` causing casting errors on call.
Makes sure that only `JavaFunction`s are returned when calling `getJavaFunctions`. This does not include `DefaultFunction`s, as `getFunctions` should be used.
Manual testing.
---
=> Fix getting java functions causing casting errors
